### ISSUE TITLE
Add RR Details to eCR Metadata section

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1012]
## Action Requested
Add the complete "RR Details" sub-section to the eCR Metadata section in the eCR Viewer.

## Acceptance Criteria
The following fields are included in the eCR Viewer:

* Reportable Conditions list
* RCKMS Trigger Summary (Also known as RR Reportability Rules)
* List of jurisdictions eCR was sent to

## Testing
Unit testing will be required.

## Background & Context
The RR information is some of the most important to understand why and eCR was sent to a jurisdiction.

## Additional Information
We may not be converting all information from the RR at present (like the list of jurisdictions). Part of this ticket will be updating the [add_rr_data_to_eicr](https://github.com/CDCgov/phdi/blob/main/phdi/fhir/conversion/convert.py#L26) function to pull out more of the RR data, as well as updating the FHIR converter to ensure all data is correctly processed during conversion. Only once that is complete can we work on adding the fields to the viewer.

The [Reportability Response Artifact Guide](https://build.fhir.org/ig/HL7/case-reporting/artifacts.html#reportability-response-profiles) will be an important reference to use during conversion. We may need to add an RR composition to the bundle, in addition to the eICR Composition already being used.

**Comment by BobanL** [comment]
Data has been pulled out with ticket #1092, but the designs have been updated to include a table which has not been done yet.
