### ISSUE TITLE
Add Symptoms List & Diagnosis to "Symptoms and Problems" sub-section

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1081]
## Action Requested
Add the "symptoms list" and "diagnoses" fields of the "Symptoms and Problems" sub-section of the eCR Viewer.

## Acceptance Criteria
The following fields are included in the eCR Viewer:

* Symptoms List
* Diagnoses

## Testing
Unit testing will be required.

## Background & Context
Both of these fields will be lists.

## Designs
<img width="806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1hVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca545d4e27ac57942b8a6bac7853304f6ffbdb4a/Screenshot%202024-01-17%20at%208.52.48%E2%80%AFAM.png" alt="Screenshot 2024-01-17 at 8.52.48 AM.png" />

** these designs are WIP and likely to change by the time this ticket is being worked on ** 

## Additional Information
We need to validate that these sections are being correctly converted to FHIR. Neither appear to be in the default message parsing schema, so it's possible some FHIR conversion work will be required.

**Comment by sarahtress** [comment]
I've removed these sections from the design altogether, it seems like they are all lumped into the Problems List. so this ticket can be closed. I've noted as a future feature improvement that we can look into associating problems with encounters as a way to help give the problem list a little more nuance, but I don't think this is a priority at this time!
