### ISSUE TITLE
Add Administered Medications to eCR Viewer

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1107]
## Action Requested
Add the "Administered Medications" field to the eCR Viewer.
>eCR Viewer
>> Clinical Info
>>> Treatment Details
>>>> Administered Medications

## Acceptance Criteria
Administered Medications information is displayed for eCRs that have the field.

## Testing
Unit testing will be required.

## Background & Context
This field may be a list of sub-fields.

## Designs
[Figma Designs](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=1024%3A136062&mode=design&t=lClwL7CnvrviunUF-1)
[Figma Clickable Prototype](https://www.figma.com/proto/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?page-id=871%3A2283&type=design&node-id=1606-27619&viewport=1011%2C558%2C0.05&t=sGUJKIN0MXVFYIfm-1&scaling=min-zoom&starting-point-node-id=1606%3A27619&mode=design)

<img width="833" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUhpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--718e661a6751913177149797cb62dc4a1610f0ed/Screenshot%202024-01-19%20at%202.19.26%E2%80%AFPM.png" alt="Screenshot 2024-01-19 at 2.19.26 PM.png" />

## Additional Information
We'll need to test to see whether or not this field is already being converted to FHIR, or if we'll need to complete both FHIR conversion and adding to the eCR Viewer.

Administered Medications may be a list, so if it seems difficult to incorporate all available information into the design, please chat with Sarah.

**Comment by angelathe** [comment]
@sarahtress For discussion when you get back!

<img width="1071" alt="Screenshot 2024-04-01 at 15 44 47" src="https://github.com/CDCgov/phdi/assets/40042932/1410ce34-95bf-4086-b045-da00acaa6b39">

**Comment by angelathe** [comment]
Next Steps:
- Spike on what information can be pulled from administered medications (& how). Currently, HTML eCRs have several different versions of what is included in the tables. Get back to Sarah about what information could be made into the columns.
  - Examples: see seed data that begins with 0141cf, 1dd100, 015ac, 6100896d
- Note: Sarah says that this information should be a table.

**Comment by aviars** [comment]
Hello World.
