### ISSUE TITLE
Add Patient Emergency Contact to eCR Viewer

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1120]
## Action Requested
Add a field for Patient Emergency Contact to the eCR Viewer.
> eCR Viewer
>> Patient Info
>>> Demographics
>>>> Emergency Contact

## Acceptance Criteria
Patient emergency contact is displayed for all eCRs where the information is available.

## Testing
Unit testing will be required.

## Designs
[Figma link](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=871-2283&mode=design&t=sxIe5Umchzr49IHv-0)

<img width="644" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFBpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc72aae235c5b97490c4f7876f42119b59b16d72/Screenshot%202024-01-19%20at%204.10.28%E2%80%AFPM.png" alt="Screenshot 2024-01-19 at 4.10.28 PM.png" />

## Background & Context
This field may not be covered by our FHIR Converter, so we may need to update that before adding to the eCR Viewer.

**Comment by KennethSkylight** [comment]
It is currently not in the FHIR converter.

Search the xml files for: `1.2.840.114350.1.13.297.3.7.2.827665` to see the emergency contacts
