### ISSUE TITLE
Create a contact tracker to manage communications with STLTs

### ISSUE THREAD

**Issue by jankimo** [CDCgov/phdi#1124]

**Comment by emmastephenson** [comment]
Done! https://cdc.sharepoint.com/:x:/r/teams/OPHDST-IRD-DIBBs/_layouts/15/Doc.aspx?sourcedoc=%7BC0563A36-7917-4DF8-B105-2F5E521A9780%7D&file=eCR%20Viewer%20Pilot%20Outreach%20Tracker.xlsx&action=default&mobileredirect=true
