### ISSUE TITLE
Add design for tooltips in eCR viewer

### ISSUE THREAD

**Issue by jankimo** [CDCgov/phdi#1139]

**Comment by sarahtress** [comment]
put content for tooltips into this sheet: [eCR Viewer Field Mapping.xlsx](https://cdc.sharepoint.com/:x:/r/teams/OPHDST-IRD-DIBBs/Shared%20Documents/CDC%20DIBBs%20Project/Streamline%20Team/1%20-%20Pilot%20eCR%20Viewer%202024/5%20-%20Research%20%26%20Design/Design/eCR%20Viewer%20Field%20Mapping.xlsx?d=w80a53c04215840b6a7762dfc8b7267c9&csf=1&web=1&e=SKYtQw&nav=MTVfe0M2RUYzOTY4LURCMzMtNDIzNS05NUE0LUMyNzU1MDExQjE4Nn0)

**Comment by sarahtress** [comment]
adding Mary Alice to this ticket to review the tooltip content!

**Comment by maryyeh** [comment]
reviewed! looks good to me!

**Comment by sarahtress** [comment]
keeping this in the review column because i'm waiting on Matt to review too! should be done this week
