### ISSUE TITLE
Implement a _build_observation method on PHDCbuilder

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1146]
In order to build the ClinicalInformation section of the PHDC we need to be able to build individual observations. Let's implement an internal helper method called `_build_observation` on `PHDCbuilder to achieve this. We should also create an `Observation` dataclass to hold the input data required to build an observation.

Acceptance Criteria:

GIVEN the `PHDCbuilder` class
WHEN `_build_observation` is called with an instance of an `Observation` class
THEN and observation element like the example below is returned

```
<entry>
	<observation classCode="OBS" moodCode="EVN">
		<code code="INV147" codeSystem="2.16.840.1.114222.4.5.1" codeSystemName="NEDSS Base System" displayName="Investigation Start Date"/>
		<value xsi:type="TS" value="19931110"/>
	</observation>
</entry>
```

**Comment by robertandremitchell** [comment]
noting that there is also a typeCode on the `entry`, at least in the `SamplePHDC_1.xml`

```python
					<entry typeCode="COMP">
						<observation classCode="OBS" moodCode="EVN">
							<code code="NBS269" codeSystem="2.16.840.1.114222.4.5.1" displayName="Patient State HIV Case Number"/>
							<value xsi:type="ST">35433453533</value>
						</observation>
					</entry>
```

**Comment by robertandremitchell** [comment]
`value` also has a potential subelement of `translation`
<entry typeCode="COMP">
<observation classCode="OBS" moodCode="EVN">
<code code="INV169" codeSystem="2.16.840.1.114222.4.5.1" displayName="Condition"/>
<value xsi:type="CE" code="10311" codeSystem="1.2.3.5" displayName="Syphilis, primary">
<translation xsi:type="CE" code="710" codeSystem="L" codeSystemName="STD*MIS" displayName="Local Label"/>
</value>
</observation>
</entry>
