### ISSUE TITLE
Render associated lab information in eCR Viewer Summary

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1157]
## Action Requested
When given an eICR ID and SNOMED condition code in the eCR Viewer, show "lab results relevant to associated condition" in the eCR summary.

## Acceptance Criteria
The "lab results relevant to reportable condition" field is filled out for all eCRs where the information is available.

## Testing
We'll need to test the new parameter in addition to the rendering (see below).

## Designs
[Figma designs](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=871-2283&mode=design&t=LpQrioiHotZiGBxo-0)

![Screenshot 2024-01-25 at 3 39 21 PM](https://github.com/CDCgov/phdi/assets/80282552/f1d97484-cd7d-4718-b9c6-222497744f04)

There are three separate types of labs that could be triggered here: a lab organism or substance (something in the lab results), a lab order, or a lab result/observation. We should consult with Sarah to see if these should all be listed out or separated in some way. 

## Background & Context
When NBS sends a request to the eCR Viewer, it will include two pieces of information: the eICR ID and the SNOMED code for the specific condition a user is viewing. (The condition code is necessary because some eCRs have multiple conditions associated to the RR). Given these two pieces of information, our viewer should be able to render the eCR viewer and the "lab results relevant to reportable condition".

To do this, we'll need to scan relevant portions of the FHIR bundle for SNOMED codes matching the condition_code parameter. 

## Additional Information
This ticket is likely to have a few components:
- Add support for sending a `condition_code` parameter to the eCR Viewer
- Find all lab results relevant to the condition
- Display those results in the summary

**Comment by lina-roth** [comment]
It wont let me unassign :(
