### ISSUE TITLE
Write a new config file in `default_configs/`to specify the FHIR to PHDC workflow

### ISSUE THREAD

**Issue by robertandremitchell** [CDCgov/phdi#1195]
https://github.com/CDCgov/phdi/blob/main/containers/orchestration/app/default_configs/sample-orchestration-config.json

GIVEN: A new configuration file that calls ingestion, standardization, and message parser services for a FHIR bundle
WHEN: A payload that specifies a PHDC XML request
THEN: The orchestration service will read this new configuration file and convert FHIR to PHDC XML.

**Comment by robertandremitchell** [comment]
@bamader , reviewing tickets to pick up today. We can mark this as complete with this work, right?

**Comment by bamader** [comment]
I don't think we have a workflow that takes input all the way through the fhir to PHDC path. We have one sample that outputs a parsed message variant, but no workflows that end in PHDC. So I actually think this is a valid ticket to pick up!
