### ISSUE TITLE
Session 1 - Clean verbatim transcript, scrub PII, & analysis

### ISSUE THREAD

**Issue by maryyeh** [CDCgov/phdi#1199]
### clean and scrub
Things to change:
- Remove “ums”
- Change name to participant code (in participant tracker)

Words that transcript captures incorrectly, often:
- NBS (N BS)
- RCKMS (RC KMS)
- eCR (ECR)
- EMSA (M SA)
- PHA (P HA)
- ELR
- AIMS (Ames)
- eCR
- Epitrax (EPI tracks)
- eiCR (E IC R)
- SFTP
- HCOs (HC OS)
- Epi 
### analysis:
- write the top 3-5 main ideas from an interview to take into synthesis
- highlight and tag "good quotes"

**Comment by maryyeh** [comment]
Dovetail name: 082924_NM_s01_p1

@sarahtress I'm starting on scrubbing now - I say we can close the ticket once I've done the cleaning, and you've done a listening pass? we can just keep in touch via comments?

**Comment by maryyeh** [comment]
I have done a first pass cleaning and scrubbing the transcript. This one was a bit tricky, so I haven't done key takeaways, yet!

**Comment by sarahtress** [comment]
sounds good - keeping track through the comments sounds like a plan! thanks for setting it up

**Comment by sarahtress** [comment]
added a column to track our key takeaways as 1 note per interview. feel free to change if you prefer a different structure!

**Comment by sarahtress** [comment]
wrote up key takeaways, marking this one as completed!
