### ISSUE TITLE
SPIKE: Consult Streamline team about why they didn't user a docker-compose file for orchestration

### ISSUE THREAD

**Issue by bamader** [CDCgov/phdi#1229]

**Comment by bamader** [comment]
Right now, we prefer using docker files and docker-compose as a way to locally build functioning and up to date images of each of our BB Services. However, the orchestration service relies on a `.sh` script to build things, which gives all kinds of weird vibes when it comes to testing. We also don't currently have an easy way to specify environment variables since we're not using a docker file for local building. This is a spike ticket devoted to discussing this issue with the streamline team. Following up with Emma or Gordon should provide some insight as to any challenges, limitations, or other technical considerations we might be missing around why they didn't opt for a docker file.

**Comment by robertandremitchell** [comment]
checked in here: https://skylight-hq.slack.com/archives/C05B5R8K0TF/p1706798876611489

Will confirm this afternoon during eng check-in, but we should be okay to proceed with https://app.zenhub.com/workspaces/skylight-dibbs-viper-6480ba23b5a07644e0e46d23/issues/gh/cdcgov/phdi/1196, assuming no red flags raised.

**Comment by robertandremitchell** [comment]
Per 2/2 engineering call, there is no compelling reason not to try to pursue making a docker-compose.yml
