### ISSUE TITLE
Side Nav design tweaks

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#1264]
# Action Requested

A few more design changes need to be made to the side navigation to match the designs:

- Vertical Alignment: the side navigation shouldn't go above the content on the right. when at the top of the page, the top of the side navigation and the top of the "eCR Summary" text should be at the same height. I attached a screenshot below to show this alignment
- Active Sections: as you scroll the page, it should be responsive to show where you are on a page with bolded blue text and a blue vertical line. [good example is on this page](https://designsystem.digital.gov/components/side-navigation/) for the component, the right side navigation is responsive as you scroll the page (... I see the styling of that component is different though and matches my original styling... perhaps there is a different component with this functionality built in??)

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1F0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8437d1edcfbc2b9a90c28180c58bee254061bfd4/300588600-3f3fe92a-f038-41c3-a353-7849c2a20db9.png" alt="300588600-3f3fe92a-f038-41c3-a353-7849c2a20db9.png" />

if the styling can actually match the USWDS component shown in this screenshot, that would be great:

<img width="390" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1V0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9ad3f23e198d785be5d013b41311f4dd745dfbd/Screenshot%202024-02-05%20at%204.46.52%E2%80%AFPM.png" alt="Screenshot 2024-02-05 at 4.46.52 PM.png" />

let @sarahtress know if you'd like to pair at all or clarify anything with this ticket

# Acceptance Criteria

Side Navigation matches Figma design

**Comment by angelathe** [comment]
@sarahtress @emmastephenson Thoughts on adding the bug fix for "sections/sub-sections with no data shouldn't appear in side nav" here? Or is the scope of the ticket too big already?

**Comment by sarahtress** [comment]
> @sarahtress @emmastephenson Thoughts on adding the bug fix for "sections/sub-sections with no data shouldn't appear in side nav" here? Or is the scope of the ticket too big already?

it makes sense to me to include it here, but I'll leave it to @emmastephenson to make the final call (though she's OOO today, so that's not the most helpful I realize 😅 )
