### ISSUE TITLE
Create AWS ecr-viewer release

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1272]
## Action Requested
Write Terraform to publish the DIBBs pipeline, eCR Viewer, and S3 bucket to an AWS subscription.

## Acceptance Criteria
It's possible to hit the `/process` endpoint with a ZIP file of eCR data, then view that data in the eCR Viewer.

Unauthenticated requests to `/view-data` should be rejected.

## Testing
Lots of manual testing on AWS will be required.

## Background & Context
NBS needs the eCR viewer working more or less end-to-end in AWS to be able to develop locally against it. (The "less" is that we won't need a function app to trigger the pipeline; they'll just hit the `process` endpoint manually.)

## Additional Information
There's a good chance this should be split into smaller tickets! But a mitigating factor is that Nick C. has been working to publish the pipeline to AWS for some time now, so the main resources we'll need to create should simply be:
* Adding the eCR viewer Helm chart into the EKS instance
* Creating the S3 bucket
* ~Ensuring all the env vars are in place for authentication~ (blocked by auth spike)
* Ensuring that networking works for the eCR Viewer (we may need to include a middleware redirect for AWS - see #1193 for details)

**Comment by emmastephenson** [comment]
Kenneth and Mary C. to pair on this work to get started.

**Comment by marycrawford** [comment]
@emmastephenson do we know what json data should be saved in the s3 bucket?  Would the modified file have the same output that the `fhir-converter` container currently creates or something else?

I am asssuming the s3 bucket will need to have the following permissions accessible:
PUT/POST for orchestration
UPDATE for fhir-converter
GET for ecr-viewer

Is this a correct assumption?

**Comment by marycrawford** [comment]
Spoke with @emmastephenson and will hold off on the Unauthenticated requests to /view-data should be rejected AC since there is a spike in the backlog that will determine how we should handle this portion of the work. See [#1267](https://app.zenhub.com/workspaces/streamline-ecr-6480bf2ee530095ab41ebbe9/issues/gh/cdcgov/phdi/1267).

**Comment by marycrawford** [comment]
Initial PR https://github.com/CDCgov/phdi-playground/pull/53.

**Comment by marycrawford** [comment]
PR updating the orchestration and ecr-viewer services version; as well as all of our services container appVersion https://github.com/CDCgov/phdi-charts/pull/33.

**Comment by marycrawford** [comment]
[PR](https://github.com/CDCgov/phdi-playground/pull/64) updating `ecr-viewer` and the `orchestration` services (as well as the `eks` and `s3` modules) in `phdi-playground`.

**Comment by marycrawford** [comment]
Latest PRs for the phdi-chart (https://github.com/CDCgov/phdi-charts/pull/34) and ecr-viewer for phdi-playground (https://github.com/CDCgov/phdi-playground/pull/66)
