### ISSUE TITLE
Add columns to Immunization History table for eCR Viewer

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#1286]
## Action Requested
Add the following fields to the Immunization History table in the eCR Viewer:
- Dose Number
- Manufacturer
- Lot Number

Structure:
>eCR Viewer
>> Clinical Info
>>> Immunizations
>>>> Immunization History

## Acceptance Criteria
The immunization History table should display all 5 columns (and available data) for eCRs that have the field.

## Testing
Unit testing will be required (update snapshot test).

## Background & Context
Continuation of [Github Issue #1111](https://app.zenhub.com/workspaces/streamline-ecr-6480bf2ee530095ab41ebbe9/issues/gh/cdcgov/phdi/1111). The Immunization History table has already been built, listing prior immunizations (each with a name and administration date). During 02/07/24 discussion with Sarah, it was confirmed to add these 3 additional columns.

## Designs
[Figma Designs](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=1024%3A136062&mode=design&t=lClwL7CnvrviunUF-1)
[Figma Clickable Prototype](https://www.figma.com/proto/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?page-id=871%3A2283&type=design&node-id=1606-27619&viewport=1011%2C558%2C0.05&t=sGUJKIN0MXVFYIfm-1&scaling=min-zoom&starting-point-node-id=1606%3A27619&mode=design)

Immunizations should be ordered by administration date (most recent first), with alphabetical ordering used if immunizations were administered on the same date.

<img width="841" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHJNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99b72d5c547efdc1f91ba419514b48fb68b6baf7/Screenshot%202024-03-11%20at%2011.02.37%E2%80%AFAM.png" alt="Screenshot 2024-03-11 at 11.02.37 AM.png" />

## Design Review
things to look for:
- capitalization and field names match design
- ordering of fields from left to right matches order of design
- ordering of immunizations is most to least recent when reading top to bottom down the table
- if data isn't available, it isn't totally blank

## Additional Information
We'll need to add these fields to the FHIR conversion & add to the eCR Viewer.

**Comment by sarahtress** [comment]
this one is pretty low priority
