### ISSUE TITLE
Better error handling for process endpoint in Orchestration

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#1296]
## Action Requested
Error handling is kinda non-existent around the process endpoint. It just throws 500s when getting anything unexpected. We should improve error handling by throwing a specific error and providing useful feedback when e.g. an incomplete request comes in

## Acceptance Criteria
When can we call this done?
Given a bad request call to the process endpoint, error messaging is returned which specifically mentions missing fields etc.

## Testing
Does this ticket have unusual testing requirements, or new tests that will need to be created?
This needs a test

## Designs
Are there designs to reference for this ticket?
Nah

## Background & Context
So what? Why is this functionality important to the user?
The total opacity of the endpoint makes figuring out what you're doing wrong extremely difficult.

## Additional Information
What else does the person picking up this work need to know about?

**Comment by emmastephenson** [comment]
Closing since VIPER has changed things; will re-open if it's still an issue.
