### ISSUE TITLE
Add Vital Status to eCR Viewer

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#1342]
## Action Requested
Add a field for Vital Status to the eCR Viewer.
> eCR Viewer
>> Patient Info
>>> Demographics
>>>> Vital Status

## Acceptance Criteria
Vital Status is displayed for all eCRs that have a vital status field.

## User Value
For certain conditions, it's useful or required by the CDC to have the patient's Vital Status. The Vital Status should either be "Alive" or "Deceased"

## Testing
(Sarah does not know this info)

## Designs
[Figma Designs](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=1024%3A136062&mode=design&t=lClwL7CnvrviunUF-1)
[Figma Clickable Prototype](https://www.figma.com/proto/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?page-id=871%3A2283&type=design&node-id=1606-27619&viewport=1011%2C558%2C0.05&t=sGUJKIN0MXVFYIfm-1&scaling=min-zoom&starting-point-node-id=1606%3A27619&mode=design)

<img width="917" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0YyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e62818b190dad791e6b94ac9ea208363d21e2480/Screenshot%202024-02-20%20at%205.31.40%E2%80%AFPM.png" alt="Screenshot 2024-02-20 at 5.31.40 PM.png" />

## Design Review
Things to look for:
- check field name and capitalization match design
- check for ordering (should be below current age, or DOB if current age ticket hasn't been picked up yet)

## Background & Context
Not sure if this is currently converted

**Comment by JNygaard-Skylight** [comment]
Do we have any examples of ECRs of a deceased individual?

**Comment by sarahtress** [comment]
> Do we have any examples of ECRs of a deceased individual?

I'm not sure - have you used Emma's python script to run through the LAC sample data? that would be the way to find out
