### ISSUE TITLE
Validate requests to the /api/fhir-data

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#1356]
## Action Requested
As an engineer, I want requests to a deployed `/api/fhir-data` endpoint to be authenticated so that only the right people get access to the data. It should return 401 Unauthenticated when the token is invalid. All other endpoints should be left open. 
As an engineer developing locally, I want my `/api/fhir-data` requests to work without auth. 

## Acceptance Criteria
 - [ ] **Scenario: Authenticated requests to /api/fhir-data**
  - Given a valid token is provided
  - When a request is made to /api/fhir-data
  - Then the response should be successful and contain the requested data
- [ ] **Scenario: Unauthenticated requests to /api/fhir-data**
  - Given an invalid or missing token is provided
  - When a request is made to /api/fhir-data
  - Then the response should be 401 Unauthenticated
- [ ] **Scenario: Other endpoints are open without auth**
  - Given a request is made to any other endpoint
  - When no token is provided
  - Then the response should be successful and contain the requested data
- [ ] **Scenario: Local development without auth**
  - Given the developer is working locally
  - When a request is made to /api/fhir-data without a token
  - Then the response should be successful and contain the requested data
  
## Testing
- Standard test suite

## Background & Context
We need to secure the /fhir-data endpoint to make sure that only authenticated users get access.

## Additional Information
- This can be done using [NextJs Middleware](https://nextjs.org/docs/app/building-your-application/authentication#authorization). 
- NextJs Middlware works with [jose package](https://github.com/panva/jose) and [not jsonwebtoken because it relies on packages that are not available in the middleware](https://github.com/vercel/next.js/discussions/38227#discussioncomment-3063432). 
- [Example code snippet](https://github.com/CDCgov/phdi/compare/boban/spike-auth#diff-aabb3c8667e3c0058c76a6480d26fc86104ce966c1a824e8f819fe1b1e38ce60)

**Comment by emmastephenson** [comment]
Nick and Lina have a PR out for this.

**Comment by emmastephenson** [comment]
PR open; going to mob on additional tests for this endpoint.
