### ISSUE TITLE
Write csv file with geocoding results

### ISSUE THREAD

**Issue by IDS-BIA** [CDCgov/phdi#137]
### Description

import pandas as pd
from phdi.geospatial.core import BaseGeocodeClient, GeocodeResult
from phdi.fhir.geospatial.core import BaseFhirGeocodeClient
from phdi.geospatial.smarty import SmartyGeocodeClient
from phdi.fhir.geospatial.smarty import SmartyFhirGeocodeClient

# Read the data
GeoCodingDataSet = pd.read_csv("GeocodeTest2.csv")

for i, row in GeoCodingDataSet.iterrows():
    location = str(GeoCodingDataSet.at[i,'INPUT ADDRESS'])
    
    #if location == "":
           # raise ValueError("Address is missing ")

                                     
   
    #Identify the Auth_Id and Token
    auth_id = ['']
    auth_token = ['']
    license =  ["us-standard-cloud"]

    smarty_coder = SmartyGeocodeClient(auth_id, auth_token, license)
    
    geo_result = smarty_coder.geocode_from_str(location)
    
     
print(geo_result)

    #print(geo_result)
#geo_result = smarty_coder.geocode_from_str(location)

#lat = geo_result[0]["GeocodeResult"]["lat"]
#lng = geo_result[0]["GeocodeResulty"]["lng"]
#print('Latitude: '+str(lat)+', Longitude: '+str(lng))

### Desired Help

Hello, 

I am having difficulties with writing a new csv file with the input address and the output Geocoding results on the same row with additional columns name "lat" and "lng". Please provide me with some examples on I can write the csv file with an additional without overwriting the original address.

Thank you so much.

**Comment by m-goggins** [comment]
@IDS-BIA Hi there, it sounds like you might be having difficulty with writing data to a CSV file. You might find the [docs](https://docs.python.org/3/library/csv.html) for `csv` or [docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) for adding data to a pandas df helpful.
