### ISSUE TITLE
Add environment variables to eCR Viewer and orchestration for S3

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1376]
Both of these services need:
* Name of S3 bucket
* Region
* Secret key
* ~ID of the IAM role~
* ~Switch for data storage mode~

Adding these environment variables in AWS will ensure the services can talk to S3.

**Comment by emmastephenson** [comment]
Environment variables needed for auth key:
* NBS_PUB_KEY (has to match private key)
* NODE_ENV

Env variables needed for data storage:
* NEXT_PUBLIC_SOURCE
* Name of S3 bucket
* Region
* Secret key
* ID of the IAM role
* Switch for data storage mode

**Comment by marycrawford** [comment]
@nickbristow and @BobanL, I was able to add the `Region`, and both the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (which will be stored in our Github secrets).  In addition, I saved `NEXT_PUBLIC_SOURCE` as a variable.  

However, will need your assistance in finding the values for `NBS_PUB_KEY` (which will be stored in github secrets) and confirm the `NODE_ENV`.  

I am assuming that these variable will need to be stored for both `phdi-playground` and `phdi`, is that correct?  Right now, I have saved them in `phdi-playground` until I get confirmation.

**Comment by marycrawford** [comment]
Confirmed with Nick Clyde that these variables only need to be in the `phdi-playground` repository.

**Comment by marycrawford** [comment]
Thanks @BobanL for providing me with the `NBS_PUB_KEY`.  I have saved it as a variable in the `phdi-playground` repository.

**Comment by marycrawford** [comment]
thanks @KennethSkylight for confirming that we can cross out the `Switch for data storage mode` in the accepted criteria since it is a duplication of the `NEXT_PUBLIC_SOURCE` variable.

**Comment by marycrawford** [comment]
thanks @KennethSkylight for confirming that we can cross out the `ID of the IAM role` in the acepted criteria since since it is a duplicate request of the Secret Key (which in AWS is the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

**Comment by marycrawford** [comment]
@nickbristow @BobanL @KennethSkylight I think this ticket is just requesting that we add this to the GitHub variables and secrets so we can talk to the services (s3 bucket, ecr-viewer and orchestration service).  This has been done.  Let me know if there is something else that needs to be done here. 

<img width="1452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM09oQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ab9684a99981d727322b5424f8f81a5d8e4af32/Screenshot%202024-02-29%20at%202.34.46%E2%80%AFPM.png" alt="Screenshot 2024-02-29 at 2.34.46 PM.png" />

<img width="1905" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1NoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d33a8aba0398cd3d3ccfd608531e846761570a9b/Screenshot%202024-02-29%20at%202.34.35%E2%80%AFPM.png" alt="Screenshot 2024-02-29 at 2.34.35 PM.png" />
