### ISSUE TITLE
Pair with Sarah on small design tweaks

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1389]
There are a few small design tweaks Sarah has mentioned for the eCR Viewer (capitalization, spacing, removing the header, etc). Pair with Sarah directly to address these issues.

**Comment by gordonfarrell** [comment]
This is for small changes only, don't be afraid to spin off larger tickets if need be.

**Comment by gordonfarrell** [comment]
This is for small changes only, don't be afraid to spin off larger tickets if need be.

**Comment by angelathe** [comment]
Action items from 4/9 conversation below: @sarahtress @JNygaard-Skylight 

- HEADER:
    - we got rid of this in the design bc side navigation is getting cut off in the page size
    - [ ]  Option 1 (preferable): Remove header
    - [ ]  Option 2: removing whitespace between the header, and removing EZ from title
- SIDE NAV
    - [ ]  make all the side nav lines the same (get rid of the thicker lines → thin)
    - [ ]  Have vertical bar (indicating current location) follow 1) if best: sub-sections, 2) at least the Document sections (i.e., Patient Info)
        - [ ]  When you click on sub-section, should also move vertical bar to that subsection
- ECR SUMMARY
    - Facility Contact:
        - [ ]  Figure out why it doesn’t show No Data
    - Encounter Date/Time
        - [ ]  Hide `End:` if no end date
    - Lab results relevant to reportable condition
        - [ ]  NOTE/QUESTION (SARAH): Check status on priority of getting the lab results to reportable condition?
    - Clinical sections relevant to reportable condition
        - [ ]  bolded title
        - [ ]  should be above `lab results relevant to reportable condition` (order is flipped)
    - RCKMS Trigger Summary
        - [ ]  title should say RCKMS Rule Summary
- ENCOUNTER DETAILS
    - Encounter Date/Time
        - [ ]  Check Invalid Date in Encounter Date/Time (End)? (Seed data: 1.2.840.114350). It didn’t exist in the eCR.
- UNAVAILABLE INFO (more of a final check after all fields have been converted)
    - [ ]  do all the fields (if tally’ed up: available + unavailable): match the design?
    - [ ]  if we have no data on a field, check that it shows up in unavailable info?
    - [ ]  check ordering or unavailable fields
- GENERAL FORMATTING
    - Subsection & Padding:
        - [ ]  More spacing between
            - [ ]  Ex. eCR Summary section: “About the Patient”, “About the Encounter”, “About the Condition”
                - something between 28px - 32px
            - [ ]  Subsections: i.e., Demographics
        - [ ]  Get consistent spacing of padding
            - Ex. Right now, it's 36 above Social History, and 20 something above Demographics
    - No Data notes
        - [ ]  Compile a list of ways of notes saying there is no data: → Convert this to say No Data
            - Not on file
            - Not on file documented in this encounter
            - ???
    - field titles
        - [ ]  set a max width on field title
        - [ ]  padding to right of field (?)
- STANDARDIZING FORMAT
    - [ ]  ACTION: create a ticket to pair w/ Sarah on field output & to look into adding standardization building block in `convert.sh`
    - [ ]  QUESTION (SARAH): Figure out what to do for bugs on our end. If we have issues in conversion, do we want to standardize whether we 1) don’t show data?, 2) showing a warning that data was available but couldn’t convert....
    - [ ]  QUESTION (SARAH): Standardizing time zones. Currently, if time zones are available, it will show in viewer’s local time zone. But will there be times where we need to see the time zone of the related org (i.e., lab)?

**Comment by emmastephenson** [comment]
@sarahtress for this one:
> NOTE/QUESTION (SARAH): Check status on priority of getting the lab results to reportable condition?

It's high priority but we needed all the fields to be converted to FHIR first, which should be done by end of sprint. There's also a chance VIPER will take this work on to help us out, as they need a similar service.

**Comment by angelathe** [comment]
PR with part 1 changes merged -- this issue is still ongoing
