### ISSUE TITLE
Add link to orchestration docs on DIBBs site

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#1416]
The orchestration docs aren't linked on our site's products page, lets add them. This work will take place in the dibbs-site repo

Autogenerated docs needing a link: https://cdcgov.github.io/phdi/latest/containers/orchestration.html

Page needing updating, at the bottom in the Building Blocks section: https://cdcgov.github.io/dibbs-site/products

Acceptance criteria: Dibbs site product page has a working link to orchestration docs and a basic description of orchestration's functionality.

**Comment by lina-roth** [comment]
<img width="1453" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2phQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53a4bc30f8c8bd6bfe530db693700e93f783531a/Screen%20Shot%202024-03-13%20at%203.14.00%20PM.png" alt="Screen Shot 2024-03-13 at 3.14.00 PM.png" />
<img width="1448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3JhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d61169de30fdd043f6027cac4203d9671bc1cb13/Screen%20Shot%202024-03-13%20at%203.13.43%20PM.png" alt="Screen Shot 2024-03-13 at 3.13.43 PM.png" />
@sarahtress

**Comment by sarahtress** [comment]
> @maryyeh @sarahtress This is ready for design review! Thank you
> 
> https://cdcgov.github.io/dibbs-site/products
> 
> <img alt="Screen Shot 2024-03-13 at 3.14.00 PM.png" width="1453" src="https://camo.githubusercontent.com/1146a22073249db7303d6e2d0c11a0d4a8682ea75e65acf8f650142f9adaf810/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424c3270685158633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d353361346263333066386338626436626665353330646236393337303065393366373833353331612f53637265656e25323053686f74253230323032342d30332d31332532306174253230332e31342e3030253230504d2e706e67">
> 
> <img alt="Screen Shot 2024-03-13 at 3.13.43 PM.png" width="1448" src="https://camo.githubusercontent.com/bd5af09b797ce74e1b4de11583d2c0322228a41777ae8b4c9de13254cd1c22e4/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424c334a685158633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d643631313639646533306664643034336636303237636163343230336439363731626331636231332f53637265656e25323053686f74253230323032342d30332d31332532306174253230332e31332e3433253230504d2e706e67">

@lina-roth this looks good to me, the screenshots didn't load for some reason 🤔 but it looked good to me directly from the website. thanks!
