### ISSUE TITLE
Installation Guide for NBS 6 team

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1437]
## Action Requested
Create an installation guide for our AWS deployment of the eCR Viewer and DIBBs pipeline.

## Acceptance Criteria
A doc exists that lays out the steps to install our AWS resources, including specific commands. (`terraform init`, `terraform apply`, etc)

This should reference our API docs for the viewer and `process` endpoint.

## Testing
Manual testing of the guide will be needed

## Background & Context
NBS 6 will deploy our AWS resources via TF, but they have not worked with it before, and have requested a guide.

**Comment by marycrawford** [comment]
@emmastephenson should this installation guide be a Google, Word or Confluence document?  What is our standard practice?

**Comment by marycrawford** [comment]
Thanks @emmastephenson for the clarification.  I will save it to a Google document and you and/or @KennethSkylight can transfer it to our CDC documents.

**Comment by marycrawford** [comment]
@emmastephenson here is the draft [DIBBS Installation Guide](https://docs.google.com/document/d/1Y5l3MtzDPA73GQpPeIS2scsVxjV66uu3xgI1WrBwNWs/edit).  I am awaiting feedback from the Cloud Enablement team.  Is it safe to assume DIBBS engineers know how to store their AWS Credentials locally?  If that is not a good assumption, then I can write a section on how to add and store their AWS Credentials securely on their local machine as well.

**Comment by emmastephenson** [comment]
@marycrawford thanks so much! I don't think the NBS devs will know how to store the AWS credentials locally, so it may be good to add a section about that as well. Thank you!

**Comment by marycrawford** [comment]
@emmastephenson here is the final revision for the [NBS Installation Guide](https://docs.google.com/document/d/1Y5l3MtzDPA73GQpPeIS2scsVxjV66uu3xgI1WrBwNWs/edit).
