### ISSUE TITLE
Pair with NBS 6 devs to get DIBBs infrastructure in their AWS instance

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1438]
## Action Requested
Pair with NBS 6 devs to get DIBBs infrastructure in their AWS instance (help them execute the Terraform and debug any issues).

## Acceptance Criteria
NBS 6 team has access to fully-running DIBBs pipeline and eCR Viewer in their own AWS environment.

## Background & Context
NBS 6 has not used Terraform before, so this will all be new to them.

## Additional Information
This will take place the week of the 18th - pairing to be scheduled.

**Comment by marycrawford** [comment]
Worked with NBS System Engineer, Kai Tiffany, on Friday, 3/29/2024.  Here are the following things we did:

- Update Terraform files to set up NBS backend for AWS
- Created Branch to Store Changes
- Successfully ran the terraform init and terraform plan
- Started troubleshooting terraform apply issues

1. Had to run a terraform init -upgrade to resolve state lock and version issues.
2. Started to troubleshoot permission issues for the iam user. 
-  It appears we may have to add (1) IAM user `arn:iam::785145133354:user/TulluriD`; and (2) dynamoDB privilege `dynamodb:CreateTable` for that user.
-  See screenshot of error<img width="1383" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGdsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c20f5ecb4bda30a2e9b739ab00df0c8d24283081/image.png" alt="image.png" />


@emmastephenson when you follow up with NBS, can you confirm that `arn:iam::785145133354:user/TulluriD` is the IAM user they will need privileges for or if it is another universal user.

**Comment by marycrawford** [comment]
<img width="1315" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVpPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf565db710502481a1a550f5e1bb119193b97ebc/Screenshot%202024-04-10%20at%2011.51.33%E2%80%AFAM.png" alt="Screenshot 2024-04-10 at 11.51.33 AM.png" />

**Comment by marycrawford** [comment]
<img width="1053" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemRPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--939f140ad7c46a8cc61d8cb1c2515d0ae70513eb/Screenshot%202024-04-10%20at%2011.54.53%E2%80%AFAM.png" alt="Screenshot 2024-04-10 at 11.54.53 AM.png" />

**Comment by marycrawford** [comment]
Moving this to done.
