### ISSUE TITLE
SPIKE: Build Familiarity with OpenTelemetry

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1461]

**Comment by robertandremitchell** [comment]
Python-specific resources: 
* https://opentelemetry.io/docs/languages/python/
* https://opentelemetry-python.readthedocs.io/en/latest/
* https://stackify.com/a-basic-introduction-to-opentelemetry-python/

Fast API-specific resources:
* https://www.youtube.com/watch?v=5GdWixsopeg
* https://www.youtube.com/watch?v=R2VX2T1WB-I
* https://tillepille.io/posts/otel-fastapi/

**Comment by robertandremitchell** [comment]
Python-specific resources: 
* https://opentelemetry.io/docs/languages/python/
* https://opentelemetry-python.readthedocs.io/en/latest/
* https://stackify.com/a-basic-introduction-to-opentelemetry-python/

Fast API-specific resources:
* https://www.youtube.com/watch?v=5GdWixsopeg
* https://www.youtube.com/watch?v=R2VX2T1WB-I
* https://tillepille.io/posts/otel-fastapi/
