### ISSUE TITLE
SPIKE: How will we deploy Prometheus and Grafana in the cloud?

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1528]

**Comment by robertandremitchell** [comment]
https://grafana.com/docs/grafana/latest/datasources/

**Comment by robertandremitchell** [comment]
https://github.com/ahamedyaserarafath/terraform_prometheus

**Comment by robertandremitchell** [comment]
https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/terraform-provisioning/

**Comment by robertandremitchell** [comment]
https://hvalls.dev/posts/prometheus-grafana-server

**Comment by robertandremitchell** [comment]
https://registry.terraform.io/modules/terraform-aws-modules/managed-service-prometheus/aws/latest

**Comment by robertandremitchell** [comment]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_alert_prometheus_rule_group

**Comment by robertandremitchell** [comment]
https://faultbucket.ca/2023/06/azure-managed-prometheus-and-grafana-with-terraform-part-1/

**Comment by robertandremitchell** [comment]
https://yetiops.net/posts/prometheus-service-discovery-aws-gcp-azure/

**Comment by robertandremitchell** [comment]
To integrate Terraform with Prometheus, I think these were the best resources I found: 

* https://blog.devops.dev/monitoring-using-prometheus-and-grafana-on-aws-ec2-which-is-built-with-terraform-f05cdd67a0ef. 
* https://yetiops.net/posts/prometheus-service-discovery-aws-gcp-azure/

I'm gonna go through and log in the #phdi-playground where I believe we need to update.

**Comment by robertandremitchell** [comment]
https://medium.com/@gayatripawar401/deploy-prometheus-and-grafana-on-kubernetes-using-helm-5aa9d4fbae66

**Comment by robertandremitchell** [comment]
Update:
* https://github.com/CDCgov/phdi-playground/blob/main/terraform/azure/implementation/main.tf
* https://github.com/CDCgov/phdi-playground/blob/main/terraform/aws/implementation/modules/eks/main.tf

**Comment by robertandremitchell** [comment]
My current understanding is that for each terraform, we'll need to use helm to install prometheus and grafana

```
resource "helm_release" "grafana" {
  name       = "grafana"
  chart      = "grafana"
  repository = "https://grafana.github.io/helm-charts"
  namespace  = "monitoring"

  set {
    name  = "service.port"
    value = "4000"
  }
}

Copy code
resource "helm_release" "prometheus" {
  name       = "prometheus"
  chart      = "prometheus"
  repository = "https://prometheus-community.github.io/helm-charts"
  namespace  = "monitoring"

  set {
    name  = "server.service.port"
    value = "9090"
  }
}
```
