### ISSUE TITLE
SPIKE: Using XPath and etree select desired sections of an XML document

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1534]

**Comment by m-goggins** [comment]
### **Background**:
Implementing XPath parsing using etree should be fairly straightforward. Etree offers two primary ways for parsing elements from Trees and Elements but I propose we start with the `.find()*` approach:

- `.xpath()`: `r = tree.xpath('./ClinicalDocument/recordTarget)`

- `.find()*`: `r = tree.find('./ClinicalDocument/recordTarget)`

Element.findall() finds only elements with a tag which are direct children of the current element. 
Element.find() finds the first child with a particular tag, and Element.text accesses the element’s text content. 
Element.get() accesses the element’s attributes

The .find*() methods are usually faster than the full-blown XPath support. They also support incremental tree processing through the .iterfind() method, whereas XPath always collects all results before returning them. They are therefore recommended over XPath for both speed and memory reasons, whenever there is no need for highly selective XPath queries. 

### **Schema**:
The absolute minimal schema would include the elements you wish to return and the xpath. This schema would assume that you want all sub-elements under the elements listed, i.e., everything in recordTarget including all attributes. 
```
schema = {
    "recordTarget": {
        "xpath": "./recordTarget",
    },
    "realmCode": {
        "xpath": "./realmCode",
    },
    "administrativeGenderCode": {
        "xpath": ".//patient/administrativeGenderCode",
        "attributes": ["displayName"]
    },
}

```

### **Approach**:
The general approach should follow these steps:

1. Read in and parse the eCR 
`root = ET.fromstring(xml_string)` or use our `utils.parse_file_from_test_assets` function.

2. Create a new Element for the minified eCR 
`result_root = ET.Element(root.tag)`
Iterate through the schema and attach all elements and subelements in the schema to the new Element
Use `.iter()`
If we only want specific attributes, we could add an attributes section to the schema and if we only wanted to return certain subelements we could add a `secondary_schema` like we implemented in the message parser. For example, if we only wanted to return the zip code of an address, we could set up the schema like:
```
schema = {
    "address":{
        "xpath": ".//patientRole/addr",
        "attributes": ["use"],
        "secondary_schema": {
            "zip": {
                "xpath": ".//postalCode",
            },
        }
    }

}

```
Then check for a `secondary_schema` and, if present, use find/findall for only those subelements. 

3.Attach the `result_root` to a new ElementTree
`result_tree = ET.ElementTree(result_root)`
4. Save/write/export result_tree


### **Additional Considerations:**
- For this first round of just grabbing sections, I believe we can use .find() and .findall() interchangeably but we would have to take more care if we wanted to select more common elements (like addr which is used for both patient and facility). We could just use more specific Xpaths or make the XPaths conditional  
- I haven’t fully explored this, but we could also leverage namespaces when parsing
