### ISSUE TITLE
Improve performance of `evaluateLabInfoData` method

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#1543]
## Action Requested
Investigate and fix performance with eCR Viewer

## Acceptance Criteria
Add performance tests to ensure performance does not get impacted in the future.

## Additional Information
- One of the main culprits is how `evaluateLabInfoData` is making indirect calls to  `getLabJsonObject` for each value that is being extracted. The call should only be made once and passed into the appropriate methods. 
  - Example: [`returnAnalysisTime`](https://github.com/CDCgov/phdi/blob/b5fc4fe30e1c212d8d0998f7bcb393485ab34a05/containers/ecr-viewer/src/app/labs/utils.tsx#L221-L232) should accept LabJson and no longer be making a call to `getLabJsonObject`

**Comment by emmastephenson** [comment]
Reference the Lighthouse scans for potential improvements as well. (Could also bump our Lighthouse passing score up after this ticket is complete).
