### ISSUE TITLE
Implement new GH Workflow(s) for CI

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1563]

**Comment by DanPaseltiner** [comment]
@robertmitchellv will add details

**Comment by robertmitchellv** [comment]
# Pull Request Slowness 🐌 

Given that we have three DIBBs teams working on different parts of the codebase often our PRs really only affect a corner of the repo we're currently working in; however, our PR CI runs tests for everything and this can often slow down developer progress.

See issue for more context:
- #1494 

In the spike I worked on a draft PR to test a way forward with testing only what is necessary based on the changes being made. There is a path forward for a `pullRequestCI.yaml` workflow that uses `workflow_call` as a way to trigger jobs that determine the changes being made, create `json` objects with added metadata that downstream jobs can use by filtering what they need to perform workflows on changed files only.

See draft PR:
- #1513 

We will likely still need to run all of our tests on pushes to `main` as a matter of maintaining quality across the codebase. The implemented changes will be a developer quality of life improvement.
