### ISSUE TITLE
Add OpenTelemetry to eCR Viewer

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1571]
## Action Requested
Add OpenTelemetry logging to the eCR Viewer.

## Acceptance Criteria
OpenTelemetry logging is implemented on the eCR Viewer and can track things like page visits, page clicks, etc.

## Background & Context
OpenTelemetry is the service we're using across containers to log metrics. It's widely supported by a number of different tools (CloudWatch, Azure Application Monitoring, Prometheus/Grafana, etc). We need to add it to the eCR Viewer to see usage and metrics for the viewer.

## Additional Information
OpenTelemetry has already been implemented on the orchestration service; we should be able to use that as a guide.

**Comment by gordonfarrell** [comment]
This is not creating all logs, just setting up the system for logging
