### ISSUE TITLE
Given a lab result observation, display lab comments

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#1593]
## Action Requested
Add a new column for Lab Comments in Lab Results table. If Lab Comments are present for a given row, the user will be able to click "View Comment" to see the full comment

## Acceptance Criteria
(not sure)

## Testing
(not sure)

## Background & Context
I didn't realize Lab Comments were associated with each row in a results table, so the field needed to be redesigned given this new info

## Designs
[Figma Designs](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=2771%3A43987&mode=design&t=krtjxIZYAAAL6epd-1)
[Figma Clickable Prototype](https://www.figma.com/proto/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?page-id=2771%3A43987&type=design&node-id=2771-43988&viewport=647%2C4421%2C0.43&t=6Pn2HJ58Sf8ivU9m-1&scaling=min-zoom&starting-point-node-id=2771%3A43988&mode=design)

Collapsed (Default):
<img width="776" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHhhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eccc16aecd4a100cb0585de27c8acdccec066a60/Screenshot%202024-04-12%20at%203.57.06%E2%80%AFPM.png" alt="Screenshot 2024-04-12 at 3.57.06 PM.png" />

Expanded:
<img width="627" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDFhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--552b53557b92847d987d6771a7118d009fdbe1b3/Screenshot%202024-04-12%20at%203.59.02%E2%80%AFPM.png" alt="Screenshot 2024-04-12 at 3.59.02 PM.png" />

**Comment by gordonfarrell** [comment]
If there are no comments, a greyed out No Data as we use elsewhere
