### ISSUE TITLE
[BUG] Dynamically created side navs don't go to the correct location

### ISSUE THREAD

**Issue by KennethSkylight** [CDCgov/phdi#1600]
In Lab orgs, the sections with headers created by a variable do not allow the sidenav to go to it.

## How to Reproduce
- Pull up phdi
- Navigate to ecr-viewer in the terminal
- Run in the terminal `npm run dev`
- Navigate to `http://localhost:3000/view-data?id=0a0b1da9-7ac6-4668-a448-c66012afae3b`
- Try to click on Lab from HOAG
- Observe that it does not move your screen to the corresponding section.

**Comment by gordonfarrell** [comment]
Lab info in particular is the issue. Could be the same class/ID starting with a number breaking CSS styling

**Comment by BobanL** [comment]
Looks like it works as expected -> 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2w2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9776f960470ad2a89eb2df01be8b50ae1aac3122/Screenshare%20-%202024-04-19%204_07_29%20PM.mp4)
