### ISSUE TITLE
Create Elastic Container Service running DIBBs pipeline

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#1611]
## Action Requested
We have an idea now of what our standard suggested AWS architecture for pilots will be, and as KY, TN, and likely ME will be using it or something very similar we should create our own terraform and deployment for testing this setup. This is the first of a series of tickets building out an architecture matching the below diagram. 

## Acceptance Criteria
For this ticket, please create terraform for an Elastic Container Service(ECS) running our pilot group of building blocks: Orchestration, Validation, FHIR Converter, Standardization & Geocoding, and the eCR Viewer.

## Designs
Overall Standard Pilot Architecture diagram for reference.
<img width="1163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjQ5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bd819c1870f7d3d964cd67b9314b80f61fba4f7/Screenshot%202024-03-22%20at%2012.50.34%E2%80%AFPM.png" alt="Screenshot 2024-03-22 at 12.50.34 PM.png" />

## Background & Context
This new deployment matching our pilot architecture will be used for load testing, debugging, demoing, etc. once deployed.

## Additional Information
N/A

**Comment by marycrawford** [comment]
@emmastephenson @gordonfarrell I think there was a discussion regarding the creation of a new Github repository for the work associated with this ticket, correct?  If so, do we know what name we want to call the new repository?

**Comment by emmastephenson** [comment]
@marycrawford yes! I already requested it, and you should have access: https://github.com/CDCgov/dibbs-aws

**Comment by gordonfarrell** [comment]
This should be stored in the new repo and also in its own AWS resources group

**Comment by marycrawford** [comment]
WIP [DIBBS Elastic Container Service](https://github.com/CDCgov/dibbs-aws/pull/1)

**Comment by marycrawford** [comment]
[Current Architectural Design](https://github.com/CDCgov/dibbs-aws/assets/29112142/7d43d3c1-5d61-41b8-a1c3-bb4884073825) and [Prospective Final Architectural [Design].](https://github.com/CDCgov/dibbs-aws/assets/29112142/1a28b5a6-758d-41c7-b16a-454e64858e7c)
