### ISSUE TITLE
Pair with Sarah on spacing/padding issues

### ISSUE THREAD

**Issue by nickbristow** [CDCgov/phdi#1655]
Pair with Sarah to make spacing between sections more consistent 

## Action Requested
- Check that spacing between sections/subsections is consistent with Figma designs -- make any adjustments as necessary
- Check that spacing between field titles and values are consistent and readable -- make any adjustments as necessary

## Ongoing list of changes:
1. `h3` `summary-box-key-information`
    - Spacing between About the Patient ↔ About the Encounter should be 28px, not 20px
    - same with About the Encounter ↔ About the Condition
2. Spacing between `eCR Summary` and `eCR Document` sections should be 89px, not 48px
3. Spacing between Demographics & Social History is too large
    - Currently: padding-bottom-3 (1.5 rem, or 24px) + margin-top (1 em, or 16.96px) = ~41px.
    - Should be: 16px spacing total between Demographics & Social History

....

## Additional Information
- This ticket is a continuation of #1389

**Comment by KennethSkylight** [comment]
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHAwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84fefc9a06607c8f63a130b5f2fe7d2ce9a10753/image.png" alt="image.png" />

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHQwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27b31a37b371092a135c657c8fec61db148b7317/image.png" alt="image.png" />
