### ISSUE TITLE
SPIKE: Determine our data model/schema for the eRSD values

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1663]
Now that we have a solid understanding of the eRSD value sets we need to consider how we want to model this data in our terminology service. What should the schema of the database that we load the value sets into be? Do we follow the model proposed in the XLSX file from APHL? Should we explore another option? Our current need is to perform queries for the codes for all clinical services pertinent to a given condition. We should also be able to group code by clinical service type e.g. "These are all the codes for COIVD labs".

Acceptance Criteria:
Based on our work in #1661 propose a schema for database that the terminology service will use so that we can discuss and review as a team.

**Comment by robertandremitchell** [comment]
@DanPaseltiner , attached are the first pass at just creating a rough look at what the two-table structure could look like. I think the main thing to note is the size: value_set.csv is about 10.4MB and conditions.csv is 30.7MB. 

conditions.csv can definitely become much smaller. With the way that both files are structured, they have a `compose.include` and `expansion.contains` sections that I think we both observed when looking last Friday had duplicates. Based on just a quick look, I would say about 50% of the codes in them are duplicates. The main difference between them, as far as I can tell, is just the description. For example, `772212002` appears twice, but in the `compose.include` has a `Rubella suspected (situation)` while the `expansion.contains` is blank. That should be relatively easy to refine and collapse. Below is a quick guesstimate showing we get to a 50% in the size of the file:

```python
>>> c
                                    id                               name  ...              code                                      display
0         2.16.840.1.113762.1.4.1146.6          DiphtheriaDisordersSNOMED  ...         194945009  Acute myocarditis - diphtheritic (disorder)
1         2.16.840.1.113762.1.4.1146.6          DiphtheriaDisordersSNOMED  ...          15682004         Anterior nasal diphtheria (disorder)
2         2.16.840.1.113762.1.4.1146.6          DiphtheriaDisordersSNOMED  ...  1086051000119107  Cardiomyopathy due to diphtheria (disorder)
3         2.16.840.1.113762.1.4.1146.6          DiphtheriaDisordersSNOMED  ...           7773002           Conjunctival diphtheria (disorder)
4         2.16.840.1.113762.1.4.1146.6          DiphtheriaDisordersSNOMED  ...          18901009              Cutaneous diphtheria (disorder)
...                                ...                                ...  ...               ...                                          ...
87941  2.16.840.1.113762.1.4.1146.2164      MumpsSuspectedDisordersSNOMED  ...         772145009                                          NaN
87942  2.16.840.1.113762.1.4.1146.2165  PertussisSuspectedDisordersSNOMED  ...         772146005              Pertussis suspected (situation)
87943  2.16.840.1.113762.1.4.1146.2165  PertussisSuspectedDisordersSNOMED  ...         772146005                                          NaN
87944  2.16.840.1.113762.1.4.1146.1440    RubellaSuspectedDisordersSNOMED  ...         772212002                Rubella suspected (situation)
87945  2.16.840.1.113762.1.4.1146.1440    RubellaSuspectedDisordersSNOMED  ...         772212002                                          NaN

[87946 rows x 12 columns]
>>> c.nunique()
id                     1346
name                   1346
title                  1346
status                    1
description            1346
use_context_system        1
use_context_code        209
use_context_text        209
system                    5
version                   6
code                  34358
display               34263
dtype: int64
>>> c.drop_duplicates(['id', 'code'])
                                    id                               name  ...              code                                            display
0         2.16.840.1.113762.1.4.1146.6          DiphtheriaDisordersSNOMED  ...         194945009        Acute myocarditis - diphtheritic (disorder)
1         2.16.840.1.113762.1.4.1146.6          DiphtheriaDisordersSNOMED  ...          15682004               Anterior nasal diphtheria (disorder)
2         2.16.840.1.113762.1.4.1146.6          DiphtheriaDisordersSNOMED  ...  1086051000119107        Cardiomyopathy due to diphtheria (disorder)
3         2.16.840.1.113762.1.4.1146.6          DiphtheriaDisordersSNOMED  ...           7773002                 Conjunctival diphtheria (disorder)
4         2.16.840.1.113762.1.4.1146.6          DiphtheriaDisordersSNOMED  ...          18901009                    Cutaneous diphtheria (disorder)
...                                ...                                ...  ...               ...                                                ...
87936  2.16.840.1.113762.1.4.1146.1441       SARSSuspectedDisordersSNOMED  ...    12591000132100  Suspected severe acute respiratory syndrome (s...
87937  2.16.840.1.113762.1.4.1146.1441       SARSSuspectedDisordersSNOMED  ...    12601000132105  Probable severe acute respiratory syndrome (si...
87940  2.16.840.1.113762.1.4.1146.2164      MumpsSuspectedDisordersSNOMED  ...         772145009                        Mumps suspected (situation)
87942  2.16.840.1.113762.1.4.1146.2165  PertussisSuspectedDisordersSNOMED  ...         772146005                    Pertussis suspected (situation)
87944  2.16.840.1.113762.1.4.1146.1440    RubellaSuspectedDisordersSNOMED  ...         772212002                      Rubella suspected (situation)

[43973 rows x 12 columns]
```

We can also definitely refine further based off what column names we want/need. Some are definitely redundant or could be compressed into a single json column in whatever schema we ultimately end up with. Curious if this is more or less right for what you think we'll need?

Also, to answer the question from standup, I did a quick aggregate and did not encounter any cases where a single condition had multiple code systems.

[scratchwork.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNytJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5aef71400921e63575a098ef94fd5089ed5ebf5/scratchwork.zip)

**Comment by robertandremitchell** [comment]
https://drive.google.com/file/d/1nxm0HpiJsONizM5NzvSIH2dbUCcDif6f/view

per conversation: pare down to this as the ERD. We will also be using the message-parser to build.
