### ISSUE TITLE
Conduct accessibility audit of eCR Viewer (dev)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1672]
Run axe testing and lighthouse audit for the eCR Viewer.

**Comment by gordonfarrell** [comment]
Make a list of issues to be fixed as you find them

**Comment by gordonfarrell** [comment]
Built in chrome lighthouse checker will do a lot for you!

**Comment by BobanL** [comment]
#1750 #1752 #1753 #1754 have been created!
