### ISSUE TITLE
Bug: Investigate and remove table rows with no data

### ISSUE THREAD

**Issue by nickbristow** [CDCgov/phdi#1675]
Certain rows have no data in any column. This can apply to any table. 

As a rule, any row with no data in any column should not be displayed.

Investigate why this is happening, and if we are not converting certain data, or have data columns not shown.
* Contact sarah

Example of this bug:
http://localhost:3000/view-data?id=1.2.840.114350.1.13.478.3.7.8.688883.230886

**Comment by gordonfarrell** [comment]
Look at Active Problems table for a possible fix idea

**Comment by gordonfarrell** [comment]
Look into how tables are being rendered and see if we have an issue with too many ways of doing it, we can make a ticket to consolidate
