### ISSUE TITLE
SPIKE: Review current STI Connectathon Use Case

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1769]
We would like to ensure that the TEFCA Viewer supports the current STI use case that will be tested at the Connectathon in Dallas. Let's review the docs on the track confluence page to determine what (if any) additional work we need to do to support this use case.

**Comment by m-goggins** [comment]
I believe we've covered all of the elements in this [spec for the STI use case](https://docs.google.com/spreadsheets/d/1m4YTTMYBNMTwXWPG1EkpkY7iWIUHT0Ul4MXU2DTGP94/edit?pli=1#gid=1877733207) from the Helios call but are missing the following data elements from the [MI Spec](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVBNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d2431d4e12b26521cd22b20ff572c46cd700e4e/20240116_Jan_MI%20STI%20FHIR%20Query%20Information.docx) from January for Chlamydia and Gonnorhea:

### Patient Information
- Patient Status/Patient Status Date (Patient.deceased[x])
- Preferred Name: Patient.name where Patient.name.use =- “usual”
- Parent/Guardian: Patient.contact where Patient.contact.relationship is an appropriate value
- Referral Information
- Primary Physician: Patient.generalPractitioner, including Practitioner.name.last, Practitioner.name.given, Practitioner.telecom.value where Practitioner.telecom.system= “phone”, Practitioner extension Practitioner.telecom.value Extension (ContactPoint Extension) where Practitioner.telecom.system = “phone”,  Practitioner.telecom.value where Practitioner.telecom.system= “email”, Practitioner.address (may contain address information depending on which address (provider or affiliated organization) is desired)

### Clinical Complications
- Active problems where Condition.clinicalStatus = "active"
- Identify conditions that correspond to Chlamydia-related sequelae, Lymphogranuloma venereum (LGV), Pelvic Inflammatory Disease (PID), History of Chlamydia infection, History of Gonorrhea co-infection, History of Syphilis co-infection (Note that co-infections may require comparison of Condition.onset and/or Condition.abatement relative to other problems to identify a co-infection)

### Treatment Information
- Medication requests where the intent=order
- Only show medications where status is not `on-hold` or `stopped`
- Medication requests related to Doxycycline, Azithromycin, Levofloxacin, Other relevant medications
- Medication Requester: name, phone, extension, email, address, city, county, state, zip

### Partner Treatment
### Case Management Data
- Pregnancy Status
- HIV status
- Does the patient have a history of STD?
- Insurance status (Coverage)
- Case Notes

**Comment by m-goggins** [comment]
I think we should discuss which of these are in scope for work we can accomplish before the connectathon
