### ISSUE TITLE
List all eCR  on homepage

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1779]
## Action Requested
All eCRs available in the backing datastore (S3 or Postgres) are available in a list view on the eCR Viewer homepage.

## Acceptance Criteria
* Homepage of viewer lists all eCRs in the bucket.
* When an ID is clicked on, you're taken to the viewer for that eCR.
* Table shows IDs and date of addition for each eCR.

Searching by ID and pagination will be covered in separate tickets!

## Testing
* Will need to test with both local installations (Postgres) and on the cloud.
* Unit and e2e tests required.

## Designs
See the [Figma prototype](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=3160-36760&mode=design&t=OrkjS29Lxcdxw1M8-0). 

## Background & Context
See the epic for more information about this body of work.

**Comment by angelathe** [comment]
@gordonfarrell FYI, AWS stores `Last-Modified` -- "The object creation date OR the last modified date, whichever is the latest." Is this sufficient for specifying the `date of addition`?

**Comment by sarahtress** [comment]
> @sarahtress @gordonfarrell FYI, AWS stores `Last-Modified` -- "The object creation date OR the last modified date, whichever is the latest." Is this sufficient for specifying the `date of addition`?

I think this will be fine to start! we can always change if we heard differently from Philly later
