### ISSUE TITLE
[SPIKE] Add support for OAUTH

### ISSUE THREAD

**Issue by nickbristow** [CDCgov/phdi#1786]
## Action Requested
Add support for OAUTH on top of the support for JWT.

## Acceptance Criteria
Access to data is blocked without proper OAUTH access.
This can be configured so we can turn this off and on.

Create a ticket with context

## Background & Context
We should have a dev way of testing this locally. We may need a test oauth provider

**Comment by KennethSkylight** [comment]
I have experience in next-auth if whoever picks this up wants help

**Comment by aviars** [comment]
User auth will be handled elsewhere, no?  Why is authentication needed here?
