### ISSUE TITLE
Implement /get-value-sets

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1788]
Now that the database is available and we have the function(s) required to query it let's implement the `/get-value-sets` endpoint. When this endpoint is queried with a condition code we should produce a JSON formatted response containing codes grouped by clinical service type that are pertinent to the condition. This response should look something like:

```
{
  "clinical_service_type1": [
    {
      "codes": [
        "code1",
        "code2"
      ],
      "system": "some-system"
    },
    {
      "codes": [
        "code1",
        "code2"
      ],
      "system": "some-other-system"
    }
  ]
  "clinical_service_type2": [
    {
      "codes": [
        "code1",
        "code2"
      ],
      "system": "some-system"
    }
  ]
}
```

Acceptance Criteria:
GIVEN the `/get-value-sets` endpoint
WHEN a client makes a request with a condition code
THEN we respond with a JSON object like the one above containing all codes grouped by clinical service type that are pertinent to the given condition

**Comment by robertandremitchell** [comment]
@DanPaseltiner , working on the related function now and am wondering if we want just the code or if we'll need the code display name as well? Should be pretty easy to as a dict or tuple in `codes`, but I was curious if we would want the name to be present.

**Comment by robertandremitchell** [comment]
Another thought/consideration: in the event 2+ SNOMED codes are provided, do we need those codes anywhere in the return, as the first key for example? Or is the thought that the 2+ SNOMED codes will always be related anyway (i.e., I'm looking at SNOMED codes for Types 1 and 2 diabetes) so the fact the codes will all be co-mingled is not a problem?

**Comment by DanPaseltiner** [comment]
> @DanPaseltiner , working on the related function now and am wondering if we want just the code or if we'll need the code display name as well? Should be pretty easy to as a dict or tuple in `codes`, but I was curious if we would want the name to be present.

I think we can scope to just the codes for now as that is all that will be needed by the eCR Refiner and TEFCA Viewer.

**Comment by DanPaseltiner** [comment]
> Another thought/consideration: in the event 2+ SNOMED codes are provided, do we need those codes anywhere in the return, as the first key for example? Or is the thought that the 2+ SNOMED codes will always be related anyway (i.e., I'm looking at SNOMED codes for Types 1 and 2 diabetes) so the fact the codes will all be co-mingled is not a problem?

Can we scope this function to a single condition? If we need to handle multiple conditions we can call this function multiple times.
