### ISSUE TITLE
Pair w/ Sarah on standardizing field output in Ingestion BB

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#1801]
## Action Requested
Pair w/ Sarah on field output & look into adding the standardization building block in `convert.sh`

## Acceptance Criteria
When can we call this done?

## Additional Information
We want to make sure we are standardizing as many fields as possible to ensure the user sees data in a consistent and easy to read format throughout the eCR viewer

**Comment by angelathe** [comment]
@sarahtress Would you say this kind of a duplicate of what we just worked on?

**Comment by sarahtress** [comment]
> @sarahtress Would you say this kind of a duplicate of what we just worked on?

this one seems to be about specifically stuff like Phone Number, Patient Name, etc and making sure they're all consistently formatted. I think we already figured out what they need to be though, so I don't think I need to pair with somebody again, instead somebody just needs to work on fixing the problems we identified

lmk if I misunderstood your question though!

**Comment by angelathe** [comment]
Closing this ticket (already did this work in #2042, will FUP with more work in a future issue)
