### ISSUE TITLE
SPIKE: Determine how to implement fine grained condition-specific filtering

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1803]
The goal of our condition specific filter is to retain only the elements in an eICR that are pertinent to the condition(s) that it was reported for. At a high level the filter will operate with 2 steps:

1. Take the conditions reported in the RR (likely provided to the service in the body of the POST request) and use the Trigger Code Reference service to lookup the codes by clinical service type that are relevant. 
2. Remove all elements in the eCR body that aren't identified with codes obtained in step 1.

Currently the specifics of how we implement step 2 are an open question. We need to take the time to review:

- The way the eCR Refiner currently operates
- The capabilities and documentation for libraries like `lxml` that might be useful
- The eCR spec
- Some example eICRs

to determine how we want to design and implement this part of the codebase. Should we have single function that applies this filter to the entire eCR document? Should this filter be applied before, after, or in conjunction with the course grained filter? Should we have condition-specific filtering functions that are targeted at certain sections of the eICR body e.g. labs, reason for visit, etc...? Which types of clinical service should we look for in each section of the eICR?

Acceptance Criteria:

Let's document answers to as many of these questions as we can in this ticket and wrap things up with a proposal and eng team conversation about how we move forward.

**Comment by robertandremitchell** [comment]
I _think_ based on the structure of the XML, and the xpathing already used in the refiner, we should be able to write something like:
```python
# Function to process and find matching XML elements based on the code systems dictionary
def find_matching_elements(root, code_systems):
    matching_elements = []
    
    for category, entries in code_systems.items():
        for entry in entries:
            system = entry['system']
            for code in entry['codes']:
                # Constructing XPath query to match elements with specific code and codeSystem
                xpath_query = f"//*[local-name()='code'][@code='{code}' and @codeSystemName='{system}']"
                found_elements = root.xpath(xpath_query, namespaces=root.nsmap)
                
                # Collect all found elements
                matching_elements.extend(found_elements)
                print(f"Found {len(found_elements)} elements for code {code} and system {system} under category {category}")

    return matching_elements
```
This would loop through and check each element for a code/codeSystemName match. At least based on the sample data, we might need to use some kind of internal dictionary for codeSystemName. For example. in `codeSystemName` it is `LOINC`, whereas the ersd.db table stores the URL `http://loinc.org`. 

The refiner works in 4 steps:
1. It loads and confirms the XML is valid.
2. It loops throughs the sections provided by the input message, first checking to confirm it matches one of the 9 section LOINCs currently coded.
3. It uses a similar xpath expression `xpath_expression = (f"//*[local-name()='section'][hl7:code[{sections_xpath_expression}]]")` to start parsing through and building a new XML based on whether the section meets the criteria provided in step 2. This step also rebuilds a header for the XML.
4. Finally, it runs the validation step again to confirm that a valid XML has been build.

I'm gonna look more closely at some sample LAC eICRs today. I think the bones of the mockup function should mostly work, but I think we will need to be more targeted in what sections we look at. We could also be more thoughtful based on the provided sections what codes to look at. I think we should be able to piggyback off Brandon's work there in linking the six clinical service types to the 9+ LOINC sections. That way, we would only look for codes in the relevant sections.

**Comment by robertandremitchell** [comment]
The exact xpath_expression will likely differ based on section, so we could do the fine grain filtering in step #3 based on the section code(s) provided to further refine.

**Comment by robertandremitchell** [comment]
xpath_query = f"//*[local-name()='code'][@code='{code}' and @codeSystemName='{system}']"
that should cover Observations that have `code`

We might also need this for `translation`? 
//*[local-name()='translation'][@code='{code}' and @codeSystemName='{system}']
