### ISSUE TITLE
Implement fine grained condition-specific filtering

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1823]
Based on the result of the SPIKE #1803 let's implement the fine grained filter

Acceptance Criteria:
GIVEN and eCR and condition code(s)
WHEN they POSTed to `/ecr`
THEN the condition specific filter is applied.

**Comment by robertandremitchell** [comment]
```python
RESOURCE_TO_SERVICE_TYPES = {
    "Observation": ["dxtc", "ostc", "lotc", "lrtc", "mrtc", "sdtc"],
    "Condition": ["dxtc", "sdtc"],
    "Immunization": ["ostc", "lotc", "lrtc"],
    "DiagnosticReport": ["dxtc", "ostc", "lotc", "lrtc", "mrtc", "sdtc"],
}
```
DiagnosticReport xpath should be straightforward of just looking at code: https://hl7.org/FHIR/diagnosticreport-definitions.html#DiagnosticReport.code
Condition should be similarly straightforward: https://hl7.org/FHIR/condition-definitions.html#Condition.code
Observation xpath (on prior ticket) _should_ just be code, though based on convos with @bamader , we might also have to filter on valueCodeableConcept
Immunization: per work by Brandon, vaccineCode: https://hl7.org/FHIR/immunization-definitions.html#Immunization.vaccineCode

**Comment by robertandremitchell** [comment]
for future use: for the `message-refiner` sample message, here are some clinical service codes that currently exist:
```python
>>> import sqlite3
>>> import xml.etree.ElementTree as ET
>>> 
>>> tree = ET.ElementTree(ET.fromstring(string))
>>> root = tree.getroot()
>>> ns = {"cda": "urn:hl7-org:v3"}
>>> 
>>> # Extract all codes within the recordTarget section
>>> record_target = root.find("cda:recordTarget", ns)
>>> codes = []
>>> if record_target is not None:
...     for elem in record_target.iter():
...         if "code" in elem.attrib:
...             codes.append(elem.attrib["code"])
...
>>> conn = sqlite3.connect("/Users/rob/phdi/containers/trigger-code-reference/seed-scripts/ersd.db")
>>> query = "SELECT * FROM clinical_services"
>>> df = pd.read_sql(query, conn)
>>> df[df.code.isin(codes)].code.tolist()

['76078-5', '76080-1', '76078-5', '94500-6', '94309-2', '76078-5', '76080-1']
```

**Comment by robertandremitchell** [comment]
That means these are the value set IDs that we could look up in the conditions table:

['2.16.840.1.113762.1.4.1146.1142', '2.16.840.1.113762.1.4.1146.798', '2.16.840.1.113762.1.4.1146.336', '2.16.840.1.113762.1.4.1146.1565']

which means we can use any of the following condition codes to look up and test against that _should_ return data:

['661761000124109', '541131000124102', '6142004', '719590007', '43692000', '541131000124102', '840539006', '895448002', '7180009']
