### ISSUE TITLE
[EPIC] Implement cloud based patient record linkage

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#183]
# Why are we building this? What problem does this work solve for the user?
Patient record linkage or deduplication of records is a huge problem in public health - it’s the “holy grail” for patient data to be properly deduplicated between records. A proper implementation of patient record linkage would enable public health departments to understand a given person’s entire medical history, and identify if a record belongs to a new patient or existing patient. This would help case managers eliminate manual work to associate records together.

We have developed an algorithm to perform record linkage, which based on testing will work well for an MVP. The next steps with this work is to productionize this algorithm to make patient record linkage available to LAC in our ingestion pipeline.

# What is the entry point for users to the service? How will they interact with it?
Patient record linkage will be a building block, and will be containerized similarly to our other building blocks.

Unlike some other building blocks, this one is not stateless - it needs to interact with existing data about patients. This data is stored in a master patient index (MPI), and the algorithm will need to both read from and write to an MPI. 

- The building block will read from the MPI to see if a patient is a person already known to the public health department.
- The building block will write to the MPI once a match has been found, or if there is no match, the building block will create a new person record.

In addition, the building block will need a way to merge or associate different records together - either within our pipeline, or within a STLT’s case management system. How this association will work in the case of LAC and IRIS is TBD. @DanPaseltiner and @sarahtress to take point on this association, with input from LAC.

# Acceptance Criteria
The goal of this work is to create the minimum viable building block that can be incorporated into LAC’s ingestion pipeline. There will likely be a great deal of optimization that we do NOT attempt to undertake as part of this epic, since the ultimate goal is to deliver a working patient linkage solution to LAC. With that in mind, the following are deliverables for this body of work:

- Patient records can be linked to a single “person” record, stored in the MPI.
- The association of patient records is communicated to all pipeline endpoints (the FHIR server and our eCR data store).
- The above code is running as part of LAC’s ingestion pipeline.

# Engineering Solution
There are several components to consider as part of the overall solution for LAC. [This diagram](https://drive.google.com/file/d/1auCHbVG121WDofGwpxaHffpt-nQD4s9S/view?usp=sharing) represents a high-level view of the solution, as well as the areas still undecided.
![Record Linkage Cloud impl.jpg](https://images.zenhubusercontent.com/604699209bfd9306195da0d7/0900d4ed-a8bc-4b04-b49c-0a102c923aac)

Single patient records will pass through the DIBBs pipeline as FHIR bundles. Within the record linkage container, fields from that bundle will be compared to existing records in the MPI. If there’s a match to an existing cluster of patient records, that bundle will be considered a “person”. If there’s no match, the BB will consider this patient to be a new person, and update the MPI accordingly. For more details about how this linkage is performed, including the fields on a patient record that are used for linkage, see [this doc](https://docs.google.com/document/d/13y8I3LAo7mSZsrg105D4Qp-k8c0jd8WSQ6W_sMveB_o/edit?usp=sharing).

STLTs will occasionally have an MPI external to their case surveillance system, but LAC does not. To ensure our solution is extensible to other STLTs, we will develop a base MPI in Postgres but allow for other MPI implementations to be brought into the pipeline as required by STLTs.

## Base MPI Schema
There will be two tables in the MPI - patient and person. Patient represents a single encounter, while person represents a bundle of encounters all linked to the same person. The patient table will be used in the MVP for the building block, and will have the following columns:

- A UUID to represent the patient’s ID within the DIBBs pipeline (this should be the same ID associated with the patient resource in the FHIR bundle)
- A foreign key to the person table
- Patient details, as represented in jsonb - these could include name, date of birth, address, etc. This jsonb will likely come directly from the FHIR bundle representing an encounter.

The person table will have the following columns:

- A UUID used to represent the person
- An optional external id provided by LAC (such as the person’s ID in IRIS)

## Work Required
At a high level, this architecture will require:

- New functions for the record linkage algorithm to interact with the MPI
- A data access layer (DAL) between the container and MPI (this will help ensure the functions don’t have to handle overhead like maintaining a connection to the database, keeping transactions isolated, etc)
- The infrastructure for our base MPI, as a Postgres database
- Containerization of the record linkage algorithm into a building block
- Associating records [TBD]

# Future Work
Some things we have floated for future discussion/development:

- Using a version control system like Liquibase to store the base MPI schema
- Adding indexes to lookup columns on the patient table
- Using the person table for lookups instead of the patient table

**Comment by aathwal3** [comment]
**Sprint Goals:**
- If there are multiple fields within a patient record linkage, they are merged appropriately

**Comment by emmastephenson** [comment]
Need to confirm if the PR dealing with multiple fields actually handles them when reading out of the MPI.

@emmastephenson to capture prior discussions around the cadence of running record linkage in a further comment.

**Comment by emmastephenson** [comment]
Summary updates from the week of 4/10:
* We will treat incoming records from the seed data as we would any other incoming records, with the addition of special logic for adding/updating the IRIS external ID.
* Patient-level record linkage will only run once on a given record, as it first passes through the pipeline. Re-running records after the MPI has been updated is NOT in scope for the pilot. (It's a potential improvement later.)
* Incident level matching will be handled in a Synapse job, not a container.
* Data passed to the eCR data store will include the patient id, person id, and IRIS external ID. When incident matching occurs, we'll re-join on the person table to see if the external id has been updated. (This will account for the case that an eCR message goes through record linkage on a Monday and MPI seeding of the same patient happens on a Friday -- the person ID for both will be the same, and we'll do a query of that Person record to see if the external ID is updated).

[Full notes available here.](https://docs.google.com/document/d/12pYchBtEliB_ufteRlhkaChLLogd4XEOOvg4Tju-zT8/edit?usp=sharing)

**Comment by emmastephenson** [comment]
Goal for the next sprint: Manual testing of the record linkage building block is complete.

The final two tickets (#432, #416) will be nice-to-haves before end of pilot.

**Comment by emmastephenson** [comment]
Update as of 4/24: Bug was found this morning in the record linkage service; it's causing failures in the e2e testing. Fixing that bug is also part of sprint goals.
