### ISSUE TITLE
Multiple content tags in an observation result in some data not being displayed

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#1874]
## Action Requested
If an observation has multiple content tags, we want to grab the data from all, not just the first

## Acceptance Criteria
Data from all content strings attached to the observation are viewable in the app

## Testing
Unit test covering this edge case

## Additional Information
What else does the person picking up this work need to know about?

This seed eCR has an example of this in an observation: http://localhost:3000/view-data?id=1.2.840.114350.1.13.478.3.7.8.688883.230886

Specifically at: "Observation/01340f1e-7fd5-59f5-ced7-4137c18d199d" Not showing all the data, Missing (POSITIVE) in second content tag

**Comment by emmastephenson** [comment]
Going to close this; will re-open if needed after QA.
