### ISSUE TITLE
Address lab fields issues in the eCR Viewer

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#1938]
## Action Requested
Address issues related to the lab observations in the eCR Viewer. 

### 1. Newlines instead of spaces
- We want values (that had to be concatenated) to be concatenated using newlines instead of spaces. The current HTML view of eCRs separates the texts with newlines, but we've currently been doing spaces.
- **Example** for seed data `61f13d32-b25c-4fb6-998b-73de2dbf87f2`: <img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1pCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--460c007c65a25f7c5b978c73444d67df0459b87a/Screenshot%202024-06-06%20at%2010.06.07.png" alt="Screenshot 2024-06-06 at 10.06.07.png" />
- **Relevant code**: The `ConcatStrings` custom filter (which joins strings via `" "` instead of newlines) is applied to the returned `valueStringObject` in `Resource/_Observation.liquid`

### 2. Add interpretation codes to values
- Lab interpretation text is not being included in the FHIR conversion. 
- **Example** for seed data `61f13d32-b25c-4fb6-998b-73de2dbf87f2`: <img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3RCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5b9986199c9262c3fbc4992be14dd6d79db77a7/Screenshot%202024-06-06%20at%2009.39.13.png" alt="Screenshot 2024-06-06 at 09.39.13.png" />
- **Example** for seed data `09f39529-69b8-4937-8e01-596b7e966d87`: <img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFpDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca3f5c82003aa67f5a068e9accfddb2338582656/Screenshot%202024-06-06%20at%2010.23.32.png" alt="Screenshot 2024-06-06 at 10.23.32.png" />
- **Relevant code**: The snippet below shows how the interpretation code text appears in the XML. If the interpretationCode text is present in an observation, it needs to be added to `valueString` (surrounded by parentheses to match the HTML text) during FHIR conversion.

>                                     <value xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>                                         xsi:type="ST">Staphylococcus aureus</value>
>                                     <interpretationCode code="A" codeSystem="2.16.840.1.113883.5.83">
>                                         <originalText>POSITIVE</originalText>
>                                     </interpretationCode>
- **Relevant files**: `Resource/_Observation.liquid`

## Acceptance Criteria
1. For a given lab observation, value strings that had to be concatenated are joined using newlines instead of spaces.
2. For a given lab observation, if an observation also has an interpretation code, it must be included in the value string.

## Additional Information
This ticket came out of PR #1921 (scope was getting too big so we moved addressing these issues into a new ticket)

**Comment by gordonfarrell** [comment]
Split this into two separate tix, closing this one
