### ISSUE TITLE
Documentation update: Updating the steps to cut a release of PHDI: https://github.com/CDCgov/phdi/blob/main/RELEASE.md

### ISSUE THREAD

**Issue by robertandremitchell** [CDCgov/phdi#1942]

**Comment by bamader** [comment]
@robertandremitchell Could you clarify what steps you're looking to update here? Is it the deployment aspect, or the branch management, or something else? Also, I'm not sure if we're still maintaining PyPI publishes so I'd lowkey love to be able to delete that.

**Comment by robertandremitchell** [comment]
I think it would be to pretty just delete/remove the https://github.com/CDCgov/phdi/blob/main/RELEASE.md#phdi-release-process if we aren't maintaining PyPi and just replace it with documentation of the two places in the code we're actually supposed to update when making a PR to create a new release. I think the stuff on Major/Minor is still useful, but I may or may not have lost an afternoon trying to figure out PyPi, so this may just be an annoyance I have with this still being on our RELEASE.md.
