### ISSUE TITLE
Address eCR Viewer Build failure

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#2019]
Currently the eCR Viewer is failing to build during the release process. Depending on the order that building blocks get scheduled for builds this can block the release of other DIBBs services.

**Comment by robertandremitchell** [comment]
Relevant slack thread: https://skylight-hq.slack.com/archives/C06SXT5PXSQ/p1719002688632059

Meeting planned for 6/28 to pair.

**Comment by robertandremitchell** [comment]
just for documentation's sake:

Met with Boban and Nick B. to go over the `dibbs-resources` (TBD). We were able to successfully get `dibbs-resources` implemented into `ecr-viewer`. So, ideally, that should remove the need for `shared-resources`. 

GitHub is having some issues, so still trying to figure out which errors in the PR are a result of that.

Ideally, can fully view/test Monday. We might also want to meet again about next clean-up tickets and whether it is worth exploring whether to use the turborepo solution. Boban mentioned wanting to do some initial testing to see if that could be a more elegant solution, so will plan to check in next week, as well.

cc @bamader

**Comment by robertandremitchell** [comment]
met with Boban, Brandon, and Nick B. to compare dibbs-resources option to proposed work with turbo repo: https://github.com/CDCgov/phdi/pull/2044. Per that conversation, and some of the concerns about the way dibbs-resources could impact local development for both tefca and ecr viewer, we decided to pursue turborepo.

This should allow the removal of symlinks from our github actions processes. So once that PR is merged, we should be able to more seamlessly cut a release. We will close this ticket once that PR is merged and a release is able to be made and successfully deployed.
