### ISSUE TITLE
SPIKE: Explore UI and React Component Testing Options

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#2032]
Currently we have growing coverage and an established testing pattern for pure functions in the TEFCA Client. We need to consider what approach we want to take for testing the UI and individual React Components.

Some general thoughts to help guide this exploration:

- We do not want tests that are deeply coupled to implementation details
- Not every line of code necessarily needs its own test. Some kind of integration test that covers several react components may be sufficient
- Based on the conversation today during parking lot we like the idea of eventually implementing end to end tests in the UI

Acceptance Criteria:
Possible approaches for testing are documented in this ticket. A discussion is facilitated with the team to decide how we should move forward.

**Comment by bamader** [comment]
Here's a doc summarizing my research findings and recommendations: https://docs.google.com/document/d/1hXwXwAtqpOKQbpFyKtiOhQ0N5A6fY_gjOJNnsd5vCa4/edit
