### ISSUE TITLE
Pair with Sarah to explore design and FHIR conversion issues

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#2042]
## Action Requested
Sarah would like to spend some time pairing with a dev reviewing design implementation and quality of FHIR conversion in the eCR Viewer. Connect with Sarah, find a time to pair, and explore the app. Very small issues can be fixed live, larger issues should be documented and sent to Gordon to be turned into tickets

## Acceptance Criteria

- [x] Paired with Sarah
- [x] Small visual tweaks can be taken care of in the pairing sesh if they're easy
- [x] Larger/very numerous visual issues documented (included specific eCR being viewed/repro steps)
- [x] Before/After comparison of XMLs to what's visible in the Viewer to look for gaps in the data being displayed

**Comment by angelathe** [comment]
## Standardizing Fields TODO
General q: should we be standardizing these ourselves (or will eventually be using the standardization service)?
- [ ]  Action: Patient Name should not be all caps
    - [ ]  eCR Summary
    - [ ]  Patient Info → Demographics
- [ ]  Action Demographics info → needs to be Upper Case
    - [ ] Demographics → Sex
    - [ ]  Demographics → Emergency Contact name
- [ ]  Address should not be all caps or all lower case (should Upper Case)
    - [ ]  eCR summary
    - [ ]  Patient Info → Demographics → Patient Address
    - [ ]  Patient Info → Demographics → Emergency Contact
- [ ]  Date (overall) should be mm/dd/yyyy
    - [ ]  DOB in Patient Info → Demographics
- [ ]  Phone Numbers
    - Home: & Mobile: (should have colon)
    - Phone numbers should have dashes (to break them up) → +1-615-999-9999
    - [ ]  Patient Contact
    - [ ]  Patient Info → Demographics → Contact AND Emergency Contact
- [ ]  eCR Document title is really small (should be the same as eCR summary)

Examples for these issues: ([Link](http://localhost:3000/view-data?id=1.2.840.114350.1.13.478.3.7.8.688883.230886) to eCR Viewer)

**Comment by angelathe** [comment]
@emmastephenson @gordonfarrell @nickbristow The only outstanding item left is turning the standardization to-do items into a ticket. I'm not sure what's needed to modify the standardization service, so just flagging for y'all if any of you could write this ticket for me -- Thank you!!

Otherwise, I finished writing all the other issues into tickets, so closing this out!
