### ISSUE TITLE
Create more realistic newborn screening data

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#2047]

**Comment by m-goggins** [comment]
From email exchange with Craig:
Patient 1

57700-7 (Hearing loss newborn screening comment) – any free text comment like “baby sleeping”

58232-0 (Hearing loss risk indicator) – SNOMED code 178280004 (Postnatal Infection)

54109-4 (Newborn hearing screening of Ear – right) – SNOMED code 164059009 (Pass)

54108-6 (Newborn hearing screening of Ear – left) – SNOMED code 183924009 (Refer)

 

 

Patient 2

54109-4 (Newborn hearing screening of Ear – right) – SNOMED code 262008008 (Not Performed)

54108-6 (Newborn hearing screening of Ear – left) – SNOMED code 262008008 (Not Performed)

73742-9 (Newborn hearing screen reason not performed – right) – SNOMED 103709008 (Attempted but unsuccessful – technical fail)

73739-5 (Newborn hearing screen reason not performed – left) – SNOMED 103709008 (Attempted but unsuccessful – technical fail)

 

Patient 3 (or added to either Patient 1 or 2)

73700-7 (CCHD Newborn Screening Interpretation) – LA18593-6 (Out of Range)

57713-0 (Infant factors that affect newborn screening interpretation) – LA12419-0 (Infant in ICU at time of specimen collection)
