### ISSUE TITLE
Create create storage resource to hold eCR records

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#205]
### Why are we doing this?
As an IT engineer, I need to pass tsv eCR data that matches the IRIS required fields to LAC’s import utilities to seed IRIS and make that data available to case managers.

The easiest way for the DIBBs pipeline to support this is through the creation of an eCR database. 

### Action Requested
1. Determine the database type best suited for this eCR database (Postgres? Another DB?)
2. Create the resources needed to support this type of resource in Azure.

### Acceptance Criteria
Database resources exist and are available for the pipeline to write to.

### Additional Information
See discussion in [this document](https://docs.google.com/document/d/1-prnFmiSEStdZjJT-XjAFXda_3p1AWwSaacpB_PtZZg/edit?usp=sharing) for additional details.

**Comment by DanPaseltiner** [comment]
@DanPaseltiner  re-write to reflect our actual approach.
