### ISSUE TITLE
Look into Lighthouse Performance Descrepancies

### ISSUE THREAD

**Issue by JNygaard-Skylight** [CDCgov/phdi#2061]
## Action Requested
Currently in our Github pipeline Lighthouse tests 3 eCRs:

- `cf9e1db8-fcc5-4cbc-96cd-043d3fd65bac`
- `1dd10047-2207-4eac-a993-0f706c88be5d`
-  `1.2.840.114350.1.13.297.3.7.8.688883.567479`

The eCR `1dd10047-2207-4eac-a993-0f706c88be5d` consistently gets performance scores >0.55
, whereas the other <=0.45. We should investigate why there is such a discrepancy, and either improve the performance of the 2 slow eCRS or create tickets to address them.

## Acceptance Criteria

- [ ] Determine the source of the discrepancy.
- [ ] If appropriate make code changes to improve the performance of the 2 slow eCRs or create tickets to address it.

## Additional Information
Examples of Lighthouse results for the 3 eCRs (They're `.txt` files because Zendesk doesn't like it if it ends in `.html`, but they are html files.:
- [cf9e1db8-fcc5-4cbc-96cd-043d3fd65bac](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM214QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0dd8e917a198227faed633fb1b58f52676a802ee/cf9e1db8-fcc5-4cbc-96cd-043d3fd65bac.txt)
- [1dd10047-2207-4eac-a993-0f706c88be5d](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3F4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59c2aedd671d14ca6be544b77a37e5bfe8c7e8d8/1dd10047-2207-4eac-a993-0f706c88be5d.txt)
-  [1.2.840.114350.1.13.297.3.7.8.688883.567479.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3V4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab8f7bef3a8c9240b76dccc960e70b1b6408c014/1.2.840.114350.1.13.297.3.7.8.688883.567479.txt)

**Comment by emmastephenson** [comment]
Closing in favor of #2869.
