### ISSUE TITLE
eCR Summary section should appear in SideNav

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2071]
## Action Requested
AS a user, I want to be able to see the eCR Summary section in the side navigation bar
SO THAT I can quickly access and view the section from anywhere in the eCR viewer.

## Acceptance Criteria
GIVEN the eCR viewer
THEN the eCR Summary section should always appear in the side nav bar.

## Testing
`SideNav.test.ts` tests may or may not need to be updated.

## Designs

Designs can be found on [Figma](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=871-2283&t=7Jnce8DdwwLvMVZI-0), & screenshot below.

<img width="287" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFc1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74508cbfc0046e02827e31163b952e3daeb44e85/Screenshot%202024-07-05%20at%2009.16.29.png" alt="Screenshot 2024-07-05 at 09.16.29.png" />

## Background & Context

Currently, users have to manually scroll (up) to view the eCR Summary section, when all other sections are included in the side navigation.

## Additional Information

**Relevant files:**
- `src/app/view-data/components/SideNav.tsx`

**Comment by JNygaard-Skylight** [comment]
This will be fixed by #2064.

**Comment by JNygaard-Skylight** [comment]
This was not resolved by #2060, so unclosing the ticket.
