### ISSUE TITLE
Fix breaks in Lab comments and narratives

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2082]
## Action Requested

Lab comments and narratives currently do not maintain the original breaks/newlines, making it more difficult to read.
As a user, I want to see the breaks that separate the text so that it’s easier to read.

## Acceptance Criteria

GIVEN an eCR with lab info
WHEN a lab result has a narrative and/or comment(s)
THEN the viewer should keep the original spacing/new lines of the text.

What should be changed:
- Lab Info → Components table → Lab Comments (if available)
- Lab Info → Narrative (if available)

## Testing

Test fixtures, snapshot, and other unit tests may need to be updated.

## Designs

[Figma designs](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=871-2283&mode=design&t=LpQrioiHotZiGBxo-0)

**NOTE From Sarah**: Even if the original has too many breaks between text, we would rather have all the breaks than none at all.

## Background & Context

Examples below from `61f13d32-b25c-4fb6-998b-73de2dbf87f2` ([Link](http://localhost:3000/view-data?id=1.2.840.114350.1.13.478.3.7.8.688883.230886#treatment-details) to eCR viewer)

**Example: Lab Comments (see: Hepatitis C IgG w/Rfx PCR)**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUsvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44ef32c0a734acb0f5b2a360879947f5d20de577/image.png" alt="image.png" />

**Example: Lab Narrative (see: FISH ALL PnL)**
<img width="1775" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU8vQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa0ea21ce381544d59bcf7b95a58fd78e36a34bf/image.png" alt="image.png" />

**Comment by gordonfarrell** [comment]
Look at Nick's recent PR #2049 for Labs for a similar situation

**Comment by sarahtress** [comment]
opening this ticket up again because it still seems to not be showing line breaks

**Comment by mcmcgrath13** [comment]
This was fixed in https://github.com/CDCgov/phdi/pull/2931
