### ISSUE TITLE
UAT Testing with sample eLR and eCR data

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#209]
### Why are we doing this?
Any new functionality being built, LAC wants more folks from their side involved in smoke testing so that more people are exposed to the Azure resources.

### Action Requested
Run ELR and eCR data that LAC county has provided through the pipeline.

Writing instructions for how to run with sample data in the UAT environment and handing to the LAC engineers to test.

Sarran: working through Azure access issues this week; should be able to run the pipeline next week. Thinking manual testing given that the Rhapsody piece is a month or two away. 

### Acceptance Criteria

**Comment by millzpaugh** [comment]
Closing in favor of https://app.zenhub.com/workspaces/dibbs-63f7aa3e1ecdbb0011edb299/issues/gh/cdcgov/phdi/456
