### ISSUE TITLE
Update IDs across eCR Viewer to use eCR data (not FHIR UUIDs)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2092]
## Action Requested
Currently, the IDs present in the eCR Viewer show the FHIR UUID values rather than the ID values that came in with the eCR directly. The FHIR UUIDs have no meaning to our users, but the native ID values do. The ask is to update the fhirpaths for eCR Viewer to reference the eCR ID value, not the FHIR ID value.

## Acceptance Criteria
* All IDs across the eCR Viewer reference the value present from the original eCR
    * Patient ID is known to need an update, but there may be others - part of this ticket will be looking through the Viewer to determine what other ID fields are present and if they need to be updated.
* No FHIR UUIDs are shown to end users

## Testing
Manual testing across several eCRs will be required to ensure the updated FHIR paths work correctly.

## Designs
No designs, but here is an example of what is being shown/what should be shown:
<img width="892" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3JIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e3ed3e526a933da59670df18f60cef2b6094d4f/Screenshot%202024-07-09%20at%205.10.18%E2%80%AFPM.png" alt="Screenshot 2024-07-09 at 5.10.18 PM.png" />

## Background & Context
As a case investigator, I want the IDs present in an eCR to use data from the native eCR (not the FHIR UUIds) so that they are meaningful data.

## Additional Information
The IDs _should_ be converted from FHIR correctly, and we just need to update the FHIR paths that are referenced in the eCR Viewer. But this needs to be confirmed with a few sample eCRs. 

One example from the FHIR bundle:
```
“identifier”: [
          {
            “value”: “urn:uuid:8589d447-a267-11ec-81e0-9e7eef92c510”,
            “system”: “urn:ietf:rfc:3986”
          },
          {
            “value”: “0000016868”,
            “system”: “urn:oid:1.3.6.1.4.1.24310”
          }
        ],
```
We should be extracting the second `value` (where the `system` references an OID) rather than the first value out of the `identifier`.

**Comment by angelathe** [comment]
Note: Ticket already open for fixing Patient IDs specifically (#2075)

**Comment by BobanL** [comment]
`patientIds` were fixed part of #2075, `facilityID` and `eicrIdentifier` already use the proper identifier. No other IDs are used in the ecr viewer.

**Comment by angelathe** [comment]
@BobanL I think for `facilityID` and `eicrIdentifier`, we're still pulling in the wrong ID. We're not showing a generated UUID, but we are displaying the OID -- we actually want the ID that precedes "OID: [OID]" (see this [thread](https://skylight-hq.slack.com/archives/C04T9HFFETX/p1720558576642529?thread_ts=1720548366.309189&cid=C04T9HFFETX)). If only the OID is given, then we don't want to show anything. Can you confirm @sarahtress?

**Comment by sarahtress** [comment]
> @BobanL I think for `facilityID` and `eicrIdentifier`, we're still pulling in the wrong ID. We're not showing a generated UUID, but we are displaying the OID -- we actually want the ID that precedes "OID: [OID]" (see this [thread](https://skylight-hq.slack.com/archives/C04T9HFFETX/p1720558576642529?thread_ts=1720548366.309189&cid=C04T9HFFETX)). If only the OID is given, then we don't want to show anything. Can you confirm @sarahtress?

so, we want to display _only_ the OID for `eicrIdentifier` and _only_ the ID that precedes OID for the Facility IDs (the same thing Josh is doing for the Patient IDs)

does that make sense? I believe eICR ID is then correct as is, but Facility IDs are not. but if somebody could screenshot these fields in the current Viewer I could highlight what is isn't right!

**Comment by BobanL** [comment]
Facility id - out of the couple examples I looked at I don't see that value anywhere in the eicr HTML file provided by LAC. There is only one ID provided. 
![image](https://github.com/user-attachments/assets/147977bc-efc1-4d9a-97f6-4a357f95d7e1)
![image](https://github.com/user-attachments/assets/18282b2a-3e53-44e6-a08b-23edd1f25a75)


eicrIdentifier
![image](https://github.com/user-attachments/assets/4061d50a-5302-4963-8547-0c397db26807)
![image](https://github.com/user-attachments/assets/9b862e1c-8336-42ee-b766-98535bba24cc)

**Comment by sarahtress** [comment]
> @sarahtress
> 
> Facility id - out of the couple examples I looked at I don't see that value anywhere in the eicr HTML file provided by LAC. There is only one ID provided. ![image](https://private-user-images.githubusercontent.com/10108172/348860985-147977bc-efc1-4d9a-97f6-4a357f95d7e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODAxNzIsIm5iZiI6MTcyMTA3OTg3MiwicGF0aCI6Ii8xMDEwODE3Mi8zNDg4NjA5ODUtMTQ3OTc3YmMtZWZjMS00ZDlhLTk3ZjYtNGEzNTdmOTVkN2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIxNDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZjJjYWEzYzdiMDkwYzQyNDIzMmQ1YWIyOWRlYzc0ZDI5YTliZGE0MjRhNTBkNDVkNTg5NTYwOGNjYmQ5ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oP5DlEsiPlreDMHHzksVwFx3T5JF0CNkQnHkM-hKcZI) ![image](https://private-user-images.githubusercontent.com/10108172/348861975-18282b2a-3e53-44e6-a08b-23edd1f25a75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODAxNzIsIm5iZiI6MTcyMTA3OTg3MiwicGF0aCI6Ii8xMDEwODE3Mi8zNDg4NjE5NzUtMTgyODJiMmEtM2U1My00NGU2LWEwOGItMjNlZGQxZjI1YTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIxNDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYWVlODUwNDM5NDEzNTNkN2FmZjMzNWJhYzI1Zjk2NWQzYzgwZmZjMzYyMWMzNGU5NjdmOTAwZjRiNGJiNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.liiQHemGrku7ODmrk7kElQ8y6p-PqPCWywu702Jg5SA)
> 
> `eicrIdentifier` (Correct as is) ![image](https://private-user-images.githubusercontent.com/10108172/348862110-4061d50a-5302-4963-8547-0c397db26807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODAxNzIsIm5iZiI6MTcyMTA3OTg3MiwicGF0aCI6Ii8xMDEwODE3Mi8zNDg4NjIxMTAtNDA2MWQ1MGEtNTMwMi00OTYzLTg1NDctMGMzOTdkYjI2ODA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIxNDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NmQxZWU4MDUwOTA2NWU4ZjhhNmRkMzU2MDJhNGUyZGQxMDkxYmE5NGM0ZTM5NWI1Zjg1NzcxMWM1NDc5MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gElpHvsChmiAB__wpUijeVNcaNMHRaLDHqqebhAyXGo) ![image](https://private-user-images.githubusercontent.com/10108172/348862150-9b862e1c-8336-42ee-b766-98535bba24cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODAxNzIsIm5iZiI6MTcyMTA3OTg3MiwicGF0aCI6Ii8xMDEwODE3Mi8zNDg4NjIxNTAtOWI4NjJlMWMtODMzNi00MmVlLWI3NjYtOTg1MzViYmEyNGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIxNDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNzJkZWY3ZDljMDM1NWNhZjQ4OTRlNzI5NjcwNDJhOGU5NjJkZTM4NzhlNjZlYzBiZjM4YTM0ZDAxN2M4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IT1vyeJ3rhs0KdAA655Vdapf-HMBAJWZMfSwklf4ZDA)

so the eICR HTML has many spots where they're not displaying the right info or the right info for users so it's not a proper "source of truth" and in the case of IDs, it's displaying the wrong stuff often. I'm not the expert on reading code, but I believe what we'd want to display here is what comes after `extension` _only_ (so that would be the 101000148 number)

basically, the numbers that have periods separating the ID is _never_ what we would want to display, except for the eICR ID. we're instead looking for those shorter IDs that are actually the ID. in this case I believe the shorter number should be the Facility's FIN (Facility Identifier Number)... but I would like to gain confidence on if the 101000... number is the FIN or not. if you're not sure, Robert Mitchell was helping me to understand how to read the OID associated with it because all the OID is doing is saying what type of number the other one is. so in the example of the Patient IDs, the number that came before often was a SSN, so then the OID was just saying hey, this is a SSN, but has no intrinsic value to an end user

does that make sense?
