### ISSUE TITLE
Care Team info isn’t converting to FHIR correctly

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2094]
## Background & Context

For this seed eICR `1c1393a3-2481-45a5-8610-392683aaef4a`: [Link](http://localhost:3000/view-data?id=a3266d94-ce19-11ec-81e1-8465ad080d41#treatment-details) to eCR Viewer

- A Care Team member’s name has been duplicated, replacing another unique name (see image below).
- This issue seems to happen during the FHIR conversion process because MCUTLER (the missing member name) does not show up in any of the “Practitioner” FHIR resources in the bundle.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFhIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06d36eaab535a17b22c5ef5bad023ba16dda438d/image.png" alt="image.png" />

## Action Requested

- Investigate where the problem is occurring (i.e. during FHIR conversion?) and why
- Make any changes necessary to match the Care Team data seen in the eICR HTML Care Team table.

## Acceptance Criteria

GIVEN a seed eICR with correct Care Team information
WHEN the FHIR conversion process occurs
THEN the resulting FHIR bundle should accurately reflect the eICR Care Team info, with no duplicated or missing member names.

## Testing

Unit tests may need to be updated.

## Designs

[Figma Designs](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=1606-27619&t=m4g0uC7SKoj5IEaq-1)

## Additional Information

**Related files:**
- `returnCareTeamTable` const in `src/app/view-data/components/common.tsx`
- FHIR conversion: `fhir-converter/Templates/eCR/Resource/_CareTeam.liquid`

**Comment by lina-roth** [comment]
McCutler is located in <encompassingEncounter><responsibleParty><assignedEntity>
