### ISSUE TITLE
Run sample anonymized eCR in test env

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#210]
### Why are we doing this?
LAC has provided us with sample, anonymized eCR data. To kick off the load testing process so we know our pipeline is production ready, we should run this data through the pipeline in a testing environment.

Note: Only eCR data as we don't have access to anonymized ELR data

### Action Requested
Run the sample data through the pipeline in a dev environment, and briefly summarize the results as a comment on this ticket.

### Acceptance Criteria
Sample data has been run through the pipeline, and any notes/takeaways/next steps are documented.

**Comment by DanPaseltiner** [comment]
Ran additional eCR data through pipeline. Discovered FHIR upload failures due to missing observation result codes. This will be addressed as part of the eCR to FHIR validation work.
