### ISSUE TITLE
Check relevant labs & clinical info functionality for a few eCRs

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#2103]
## Action Requested

Once we believe we have completed all work to get Relevant labs & clinical info worked as intended, Sarah would like to pair with a dev to compare the output of the eCR Viewer with the original data in the corresponding eCR. 

This ticket will involve meeting with Sarah to go through 3-5 eCRs that have been processed through the eCR Viewer. We'll be looking at the eCR Viewer and original eCR file (both xml and html for eICR and RR) side by side to try to figure out if the data we're pulling into the Summary actually would make sense to the user. This will help to inform if the terminology service needs to be updated at all to meet the needs of the eCR Viewer before it's ready for end users.

## Acceptance Criteria

Ticket is done once assigned dev pairs with Sarah for 3-5 eCRs, and writes up any corresponding tickets that come out of any issues identified during pairing

## Background & Context

The Relevant lab & clinical info sections in the eCR Summary help epis and case investigators get a sense of what exactly in the whole eCR document caused the eCR to be sent to them. Pulling up these most relevant bits of information to the top can help them to make a decision more quickly about what to do with the document and what data to look for in more detail in the whole eCR. If we don't display the right information there, we may not actually save any time, so we want to make sure that we have a good sense of how this functionality is working for a few eCRs so we can make sure one of the big value propositions of the eCR Viewer is going to work when pilots are in full gear.

## Additional Information

This ticket is currently blocked until the Relevant lab & clinical info sections are fully working as intended. We'll be ready for this ticket when:
- we automatically stamp any eCR processed for display in the eCR Viewer with ALL conditions in the RR for that eCR
- when making an API call for the eCR Viewer with a condition code (i.e. how it will work when NBS integrates eCR Viewer), we show that reportable condition in the eCR Summary and the Relevant lab & clinical info in the eCR Summary corresponds only to the reportable condition that is in the API call and that is displayed in the eCR Summary
  - for eCRs with multiple reportable conditions, we should also be able to change the condition code in the API call and see the info for reportable condition and relevant labs & clinical info change to match the requested info from the API call

**Comment by angelathe** [comment]
Putting this back in the backlog as we still need to fix the resource stamping process

**Comment by angelathe** [comment]
Issues #2597, #2598, #2601, #2604 have been created as a result of this pairing session.

Adding a note here that we saw several examples of eCRs in which we're not pulling up the relevant clinical info because it's related to the miscellaneous notes (text) -- Don't think we can do anything about this right now
[Example eCR](http://localhost:3000/view-data?id=0a094680-9a5d-45b5-bdda-197f79df2d03#clinical-notes)

Closing on 09/20/24 as completed.
