### ISSUE TITLE
Part 2: Pair with Sarah to ID issues when comparing eCR Viewer output with original eCR

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#2104]
## Action Requested

Sarah already paired with Angela to compare 2 eCRs in this [ticket](https://app.zenhub.com/workspaces/streamline-ecr-6480bf2ee530095ab41ebbe9/issues/gh/cdcgov/phdi/2042). The 2 eCRs we already went over are:
- 61f13d32-b25c-4fb6-998b-73de2dbf87f2: [Link](http://localhost:3000/view-data?id=1.2.840.114350.1.13.478.3.7.8.688883.230886#lab-results-from-vumc-cerner-lab)
- 1c1393a3-2481-45a5-8610-392683aaef4a: [Link](http://localhost:3000/view-data?id=a3266d94-ce19-11ec-81e1-8465ad080d41#treatment-details)

This ticket will involve meeting with Sarah to go through another 2-3 eCRs that have been processed through the eCR Viewer. We'll be looking at the eCR Viewer and original eCR file (both xml and html for eICR and RR) side by side to try to figure out if we're not converting any important info or if we have any errors with conversion. All potential problems will be recorded during pairing to be turned into tickets

## Acceptance Criteria

Ticket is done once assigned dev pairs with Sarah for 2-3 eCRs, and writes up any corresponding tickets that come out of any issues identified during pairing

## Background & Context

At a baseline, we want to make sure that if data that could be useful to end users is in an eCR that we are displaying that info in our Viewer. We also want to make sure that the data that we're pulling into fields into our Viewer is actually what we say it is (for ex: in past ticket we were pulling FHIR conversion patient ID rather than the patient ID that comes from the medical record). Doing this QA on the eCR Viewer helps us ensure we're delivering a product that works as promised to our end users!

**Comment by angelathe** [comment]
### Follow-Up Questions/Issues (adding from the last pairing session):
- [ ] **Future Medications** - do we want to display this information? Example: eICR HTML for 1c1393a3-2481-45a5-8610-392683aaef4a
- [ ] **Administered Medications** - re-check how this info is being displayed: Example: eICR HTML for `1c1393a3-2481-45a5-8610-392683aaef4a` vs. [Link](http://localhost:3000/view-data?id=a3266d94-ce19-11ec-81e1-8465ad080d41&snomed-code=840539006#treatment-details) to eCR Viewer
- [ ] **Comment columns** - Do we want the comment column to disappear altogether if there are no comments? (Related areas: comments in  Lab Info & Active Problems)
- [ ] **Review date/time timezone differences between eICR HTML and eCR Viewer**? Example: View the labs in [eCR Viewer](http://localhost:3000/view-data?id=1.2.840.114350.1.13.478.3.7.8.688883.230886&snomed-code=840539006#lab-results-from-vumc-cerner-lab) for `61f13d32-b25c-4fb6-998b-73de2dbf87f2`. Compare Collection/Received Times in labs (UTC) vs. how they appear in eICR HTML (CST)

**Comment by sarahtress** [comment]
this has been covered by QA tickets!
