### ISSUE TITLE
Load test pipeline with production-level eCR data

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#211]
### Why are we doing this?
The Rhapsody tool to send data to the pipeline is not available yet, and won't be for another month or two. Before this tool is available, we need to make sure that the pipeline is able to handle production-level data loads. 

### Action Requested
Manual UAT testing is performed with several days of eCR data to mimic a production-size dataset.

This data should be available as ZIP files from AIMS.

### Acceptance Criteria
Manual UAT testing has been performed as a collaboration between LAC engineers and DIBBs engineers.

**Comment by millzpaugh** [comment]
Closing in favor of: https://app.zenhub.com/workspaces/dibbs-63f7aa3e1ecdbb0011edb299/issues/gh/cdcgov/phdi/456
