### ISSUE TITLE
Add the page header to loading page | eCR Viewer

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#2159]
## Action Requested
Currently the loading skeleton doesn't have a header, so clicking from the homepage into an eCR has an awkward flicker where the header disappears and reappears and the page content jumps up and down. Add the header to the loading experience to fix this

## Acceptance Criteria

- [ ] The loading skeleton has the page header attached at the top

## Testing
Snapshots

## Designs
Same header as the viewer page

## Background & Context
Our loading experience needs some love!

**Comment by sarahtress** [comment]
is there going to be a ticket to address how the loading page doesn't speak at all to the other designs? we're going to keep having design debt with loading if it doesn't comm w the most up to date version of the regular page designs
