### ISSUE TITLE
Increase font size of "eCR Document" header | eCR Viewer

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2170]
## Action Requested
In the eCR Viewer, the `eCR Document` header is really small. It should be the same font size as `eCR Summary`.

**Current font size**: 22px
**Should be**: 40px

**Currently:**
<img width="1478" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHp3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53bb7d72be1a74796c7d924c89351ec78aea7ede/Screenshot%202024-07-18%20at%2009.42.19.png" alt="Screenshot 2024-07-18 at 09.42.19.png" />

## Acceptance Criteria
eCR Document header should be changed to 40px

**Important! Please change this for both:**
- [ ] The main eCR Viewer page
- [ ] The loading page component

## Testing
Snapshot tests may need to be updated.

## Designs
[Figma designs](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=1606-27619&t=BDaWATonROGgZ3So-0)
<img width="1503" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFB3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4753b2834afebb0ebc2d52eea80233786a50b655/Screenshot%202024-07-18%20at%2009.35.14.png" alt="Screenshot 2024-07-18 at 09.35.14.png" />

## Background & Context
`eCR Summary` header uses the code below from `custom-styles.scss`
```
#ecr-summary {
  font-size: 40px;
}
```

## Additional Information
**Related files:**
- `src/styles/custom-styles.scss`
- **Main page**: `src/app/view-data/page.tsx`
- **Loading page**: `src/app/view-data/components/LoadingComponent.tsx`

**Comment by emmastephenson** [comment]
This ended up being a bit more complex because multiple header rules had to change across the app - multiple CSS changes.
