### ISSUE TITLE
Back Button | Non-Integrated eCR Viewer

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#2173]
## User Story

As somebody using the Non-Integrated eCR Viewer, I want to be able to click a back button on an individual eCR, so that I can return to the eCR Library table and see all of the eCRs.

## Acceptance Criteria

- [ ] A back button precisely matching designs exists on the eCR Viewer page
- [ ] The button is gated behind the existing environment variable `isStandalone` so it's only visible when the viewer is in non-integrated mode

## Scenarios

_Write out scenarios that will help to ensure the functionality works as expected_

Scenario 1:
- I am viewing the eCR Library table on the homepage
- I click into an eCR to view it
- I am done viewing this eCR and want to return to the eCR Library
- I click the back button and am taken back to the eCR Library table
 
Scenario 2:
- I click the "View Document" button in NBS
- I am taken to the eCR Viewer and shown my eCR
- I don't see a back button since the eCR library home page is not available to me

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=3160-36762&m=dev&t=9byjUxL08W4VVheL-1)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_

<img width="1617" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2Z4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e316b36fa2ba540da37de9df78c85db89a018738/Screenshot%202024-07-18%20at%203.58.06%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 3.58.06 PM.png" />

**Comment by emmastephenson** [comment]
For integrated eCR Viewer, button/link does not exist and whitespace for it is removed.
