### ISSUE TITLE
FRONTEND eCR Library Pagination Upgrade | Non-Integrated eCR Viewer

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#2190]
## User Story

As somebody viewing the eCR Library table, I want to use pagination to adjust the eCR Library table, so that I can view the amount of eCRs that's best for me and understand how many eCRs match my filtering criteria.

This story is for the frontend portion of pagination, including all styling and the calls to an endpoint (to be written in another ticket) to receive eCRs for display in the Library. Please work CLOSELY with the other engineer writing the backend ticket to align the call and endpoint.

## Acceptance Criteria

- [x] A message displaying the number of eCRs on page and the total number of eCRs. e.g `Showing 25-50 of 757 eCRs`
- [x] Table page selector in the bottom middle, following the default component behavior and guidance from USWDS [here](https://designsystem.digital.gov/components/pagination/)
- [x] A dropdown where a user can choose their pagination values from 25, 50, 75, and 100. Default is 25.
- [x] Pagination is pinned to the bottom of the page and always visible on page resize etc
- [ ] All visuals precisely match the Figma design

## Scenarios

Scenario 1
- I navigate to the eCR Library and see a list of 25 eCRs
- I want to view more eCRs per page, so I click the dropdown in the bottom right
- I select 75 eCRs
- The table updates to show 75 eCRs per page, and all other pagination values update properly (there should be fewer pages overall)
 
Scenario 2
- I am viewing page 1 of the eCR Library with 50 eCRs per page and 200 total eCRs.
- I see a display in the bottom left saying `Showing 1-50 of 200 eCRs`
- I click the option for page 3 at the bottom
- The display text now reads `Showing 101-150 of 200 eCRs`
- I see eCRs 101-150 in my eCR Library

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=5118-14834&m=dev&t=tRxd16EOyHtfXzOf-1)
[Link to Figma prototype](https://www.figma.com/proto/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?page-id=5118%3A14833&node-id=5118-14834&viewport=-2709%2C1674%2C0.61&t=TYxPeZjfUX6UsjQO-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=5118%3A14834&share=1)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_

<img width="1242" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUFoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7458afd0ec62dafc402dfc430f448f342d8f10d8/Screenshot%202024-07-31%20at%209.59.10%E2%80%AFAM.png" alt="Screenshot 2024-07-31 at 9.59.10 AM.png" />

**Comment by emmastephenson** [comment]
Pagination should be handled on the backend, and only returning what's shown on a single page (query for 25, not 200)

**Comment by emmastephenson** [comment]
Cookies will be needed to retain the "eCR per page" value, if the user sets it.
