### ISSUE TITLE
Add demo selection modal

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#2214]
When the `Go to the demo` button is clicked a modal as shown below should be opened to allow users to have "choose your own" adventure approach to the demo they see. Data should be populated into the search form accordingly, but let's leave changes to the search form for another ticket.

<img width="816" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXI3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--317b22bad8f1dfe753769fd74bdea5e3516f97a7/image.png" alt="image.png" />

**Comment by DanPaseltiner** [comment]
Link to designs in Figma https://www.figma.com/design/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Site-Experiences?node-id=2636-10410&t=Fb8msBgVgeoNd6R2-4

**Comment by m-goggins** [comment]
Rob handled this with #2213
