### ISSUE TITLE
Seed Azure Starter MPI with LAC COVID person data

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#224]
### Why are we doing this?
For the record linkage building block to work, we need an MPI that it can reference regularly. This MPI needs to be seeded with real, production patient data to be effective.

Long-term, the team would like to use the data warehouse being developed by LAC to seed this MPI. However, that won't be available for a few months at least, so in the short term we'd like to use the COVID person data LAC does have available. This ticket represents that short term work.

### Action Requested
Seed the MPI with COVID person data, and determine a way to do it on a somewhat regular cadence.

### Acceptance Criteria
- MPI has production patient data in it
- A mechanism has been determined to update the MPI regularly

### Additional Information
See #216 for details.

**Comment by emmastephenson** [comment]
DIBBs doesn't have an MPI ready to be seeded at this point; this ticket will be blocked until then.

**Comment by emmastephenson** [comment]
LAC moving forward with production data warehouse, want to make sure the short-term solution will be easily transferable. 

LAC does have the schema for this data warehouse available, which will help DIBBs in the design. Team to work with Robert to share.

**Comment by emmastephenson** [comment]
Ideal case: this is ongoing seeding. 

If we have a flat spec of identity info we want to put into the MPI, can use the data extract (in the short term) and look at how that will change once data warehouse is in prod. (Ideally EOM for testing)

**Comment by DanPaseltiner** [comment]
closing in favor of #412
