### ISSUE TITLE
eCR Library Table Formatting Part II | Non-Integrated eCR Viewer

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#2244]
## User Story

As somebody viewing the eCR Library table, I want to see a user-friendly table, so that I can easily understand and scan through the eCRs my public health department has received

## Acceptance Criteria

The table must match the Figma designs linked below, specifically:
- [x] There should be a drop shadow below the table header (Y offset: -4px, Blur: 4px, Color: 000000 15% opacity) ~AND below the eCR Library + search panel~
- [x] Alternating grey and white rows, making sure colors in table match Figma designs
- [x] The column widths should look visually similar to the designs. There should be a minimum width on each column such that the column header stays on one line when making the table narrower. If the user makes the browser narrower than the min width, the table should not get any narrower (the user would have to just scroll right and left on the page to see the full page and table) 
- [x] The table should be responsive to resize when the browser is resized
- [x] Set table height so that scrolling is inside the table, not the whole page

## Scenarios

_Use the scenarios below to help in testing the ticket before/during/after design review to ensure it meets the criteria above_

Scenario 1:
- I resize my browser window to be wider and taller
- The table smoothly resizes to match the browser window, the edge of the table following the browser edge (not leaving any padding anywhere)

Scenario 2:
- I resize my browser window to be narrower
- The columns all decrease in width, until they reach their minimum width
- All column headers stay on one line
- When I make it super narrow, the browser forces me to scroll right and left to see the full table and page

Scenario 3:
- I try to scroll while hovering outside of the table
- I should not be able to scroll
- I try scrolling within the table area, below the table header
- I am able to scroll through all of the eCRs, and I see a scroll bar to indicate how far I am in the results
- I also see that every row alternates in background color between white and light gray

## Design Notes

_Owned by design team - Attach link to design in dev mode and/or prototype, as well as any notes on visual details, interaction expectations, accessibility considerations, copy requirements_

[Link to Figma design in Dev mode](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=4955-47612&m=dev&t=zYuGs1ZKcquAFSSW-1)
[Link to Figma prototype](https://www.figma.com/proto/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?page-id=4955%3A47258&node-id=4955-47612&viewport=-4385%2C2455%2C0.95&t=eC6BEpGPg9yXeSuW-1&scaling=scale-down&content-scaling=fixed)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_
<img width="1245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU1PQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b1b7d4ed257c2e32a40c2c8170f43bfa656c3cc/Screenshot%202024-07-25%20at%202.33.04%E2%80%AFPM.png" alt="Screenshot 2024-07-25 at 2.33.04 PM.png" />

**Comment by angelathe** [comment]
Removed criteria to add drop shadow below the eCR Library + search panel since the search panel hasn't been implemented yet. Criterium has been moved to #1780.
