### ISSUE TITLE
Fix alignment of side nav and header and padding above

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#2264]
## Description

The vertical alignment of the side nav and the eCR Summary header is off. This makes the page look visually unpolished, and doesn't utilize vertical real estate well. There is also more padding above the header and the patient banner than there should be

## Steps to reproduce

_List out the steps in detail to reproduce the bug_

1. Open an eCR in the eCR Viewer
2. Observe side nav and eCR Summary header

## Expected Result

It should be aligned like in the designs and have the same padding as in the [designs](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=4337-31741&m=dev&t=jGrs7b7hDp86qfeb-1) (1.5 rem):

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHNTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1d39ba04e5c7083c595bd1a08c33ebcf3da7241/Screenshot%202024-07-26%20at%2010.37.30%E2%80%AFAM.png" alt="Screenshot 2024-07-26 at 10.37.30 AM.png" />

## Actual result

There is a gap and there is more than 1.5 rem of padding:
<img width="1492" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDRTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cf3c3e94000503ef5a689a59562b577cfee4407/Screenshot%202024-07-26%20at%2010.29.49%E2%80%AFAM.png" alt="Screenshot 2024-07-26 at 10.29.49 AM.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [x] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

**Comment by emmastephenson** [comment]
This might be covered by #2271. Closing for now, but will reopen if needed.
