### ISSUE TITLE
Fix spacing between side nav and eCR content

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#2266]
## Description

There is too much spacing between the left side nav and the eCR content. They should be closer so that the content is visually more closely associated and horizontal real estate is well utilized

## Steps to reproduce

_List out the steps in detail to reproduce the bug_

1. Open an eCR in the eCR Viewer
2. Observe side nav and eCR content to the right

## Expected Result

Should look like the design below, with spacing matching [designs](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=4337-31741&m=dev&t=jGrs7b7hDp86qfeb-1) (3 rem):

<img width="1091" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a921ddaee34be6c05a824ccdd5dcde2b926c7f88/Screenshot%202024-07-26%20at%2011.06.22%E2%80%AFAM.png" alt="Screenshot 2024-07-26 at 11.06.22 AM.png" />

## Actual result

The spacing is much larger:
<img width="746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9d4c900c63f972bca03f06c88d3cf3b0fd7caee/Screenshot%202024-07-26%20at%2011.07.16%E2%80%AFAM.png" alt="Screenshot 2024-07-26 at 11.07.16 AM.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

**Comment by angelathe** [comment]
@sarahtress I think this got fixed in #2271? I'll wait for you to confirm before I close this ticket

**Comment by sarahtress** [comment]
> @sarahtress I think this got fixed in #2271? I'll wait for you to confirm before I close this ticket

ah you're right, it does look better in those screenshots! I'll close it
