### ISSUE TITLE
Gitignore data.sql

### ISSUE THREAD

**Issue by lina-roth** [CDCgov/phdi#2270]
## What needs to be done
- Data.sql should be removed from the code base
- Add instructions that everyone needs to run "npm run convert-seed-data" to generate seed data 
- Ensure that pipeline generates seed data so tests pass

## Why it needs to be done
- Data.sql has been causing lots of merge issues because it's such a large file and it can never be auto merged.
-  It should be removed because everyone should be generating their own data.sql so its up to date

## Acceptance Criteria
- Data.sql is no longer in EcrViewer/seed-scipts
- Pipeline tasks still complete

## Technical Notes
- You will probably need to update github tasks to run npm convert-seed-data so that it is able to seed the db for testing

**Comment by emmastephenson** [comment]
@lina-roth or @BobanL, is this still an issue?

**Comment by lina-roth** [comment]
@emmastephenson the data.sql will be removed with Austin's upcoming changes so we can close this

**Comment by emmastephenson** [comment]
Excellent, thanks!
