### ISSUE TITLE
Cookies for storing pagination settings | Non-Integrated eCR Viewer

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#2273]
## User Story

As somebody viewing the eCR Library table, I want my pagination choices to be retained when clicking into an eCR then returning to the eCR library, so that I don't have to constantly reset it to my desired settings.

## Acceptance Criteria

- [x] Using cookies, pagination data is stored for a session
- [x] eCRs per page and the current page being viewed both persist after clicking into and returning from an eCR

## Scenarios

Scenario 1
- I navigate to the eCR Library and see a list of 25 eCRs
- I want to view more eCRs per page, so I click the dropdown in the bottom right
- I select 75 eCRs
- The table updates to show 75 eCRs per page, and all other pagination values update properly (there should be fewer pages overall)
- I click into an eCR to look at it
- When I click the back button and return to the eCR Library it still shows me 75 per page
 
Scenario 2
- I am viewing page 1 of the eCR Library with 50 eCRs per page and 200 total eCRs.
- I see a display in the bottom left saying `Showing 1-50 of 200 eCRs`
- I click the option for page 3 at the bottom
- The display text now reads `Showing 101-150 of 200 eCRs`
- I see eCRs 101-150 in my eCR Library
- I click into an eCR to look at it
- When I click the back button and return to the eCR Library it still shows eCRs 101-150
 
## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=4035-11612&m=dev&t=jHVLwNTSDhSkDGEV-1)
[Link to Figma prototype](https://www.figma.com/proto/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?page-id=3953%3A22895&node-id=4035-11612&viewport=639%2C601%2C0.26&t=1r0gCmA5HFWGB9FR-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4035%3A11612)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_

<img width="1185" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXo4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c601204dbf3caf148da290feaa117a74f68e971a/Screenshot%202024-07-22%20at%202.59.06%E2%80%AFPM.png" alt="Screenshot 2024-07-22 at 2.59.06 PM.png" />

**Comment by BobanL** [comment]
So part of this is done. eCRs per page is saved in [local storage](https://github.com/CDCgov/phdi/blob/e47e68b96036cd1fab5b358fb2f10c7ff619413d/containers/ecr-viewer/src/app/components/EcrPaginationWrapper.tsx#L41) but the current page being viewed is not being saved.

**Comment by JNygaard-Skylight** [comment]
Wait for [this](https://app.zenhub.com/workspaces/streamline-ecr-6480bf2ee530095ab41ebbe9/issues/gh/cdcgov/phdi/2233) to be merged before I work on this anymore:
