### ISSUE TITLE
[EPIC] Documentation Refresh

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#228]
### Why are we doing this?

As a DIBBs team member, I want to have well-structured documentation for our products, so that I can easily navigate through our repos and understand our product offerings

We have lots of documentation, but it hasn't been developed in conjunction with our RDC team. As such, it's not even clear for our own team how we should navigate through the repo and find all of our documentation. Ideally, with well structured documentation, team members will be able to easily find what they're looking for within our repo.

After our documentation is more intuitive to our team, our next step can be making further improvements to our documentation based on ideal user journeys and user feedback.

### Action Requested
- [done] Spike to investigate the current state of our documentation and gather initial internal feedback
- Write up new versions of any documentation we're going to improve in a google doc
- Get team feedback on proposed changes to documentation
- Update documentation on various sites (github repo, github pages, pypi, etc) [might need to be broken down into more than one ticket]

### Acceptance Criteria
- Documentation is easy for our team to navigate through and understand
- We've touched base with the CDC team to make sure that they're ok with any documents or websites that will be CDC-specific.

### Relevant artifacts/links
- Example of another GitHub repo to reference for structure/documentation: [Pandas](https://github.com/pandas-dev/pandas)
- Prior research touching on geocoding documentation: [SDK User Experience Research Plan](https://docs.google.com/document/d/14OQ8WXGs5jWlXSNZB5YkrvMb_tnNFJ7xQTKIqvTvsdM/edit#heading=h.gltdn7lhpdmf)
- @DanPaseltiner and/or @millzpaugh to link relevant documentation for reference here
  - [GitHub Ingestion Container Documentation](https://github.com/CDCgov/phdi/blob/main/containers/ingestion/description.md)
- @mattmgoldberg to add doc he made from spike into existing documentation review
- [ONC Industry Days Slides](https://docs.google.com/presentation/d/1ulNoO-oXd7MkMYOj5VUihiRWpdc_0dmxKHp9zV2HVe0/edit#slide=id.g194e3bca3e4_0_0)

**Comment by mattmgoldberg** [comment]
DIBBs documentatio for the SDK and containerized Building Blocks: https://cdcgov.github.io/phdi/

**Comment by DanPaseltiner** [comment]
@mattmgoldberg is the owner of this body of work and will pull in others as necessary.

**Comment by aathwal3** [comment]
**Sprint Goals**
- Change content in the PiPy website - should align with PHDI Readme 
- Change content on Github pages documentation website - should align with what's in the repo

**Comment by emmastephenson** [comment]
Might be ambitious; will re-assess at grooming next week.

**Comment by emmastephenson** [comment]
Azure readme updated and now working on the getting started guide.

Revised sprint goal: README and Getting Started doc are updated.

**Comment by emmastephenson** [comment]
Execution guide and implementation guide might be good enough considering they've been well tested recently. We might be able to call this done once Getting Started doc is finished.

**Comment by emmastephenson** [comment]
Tentatively closing this epic, unless @mattmgoldberg there's anything left outstanding?
