### ISSUE TITLE
[SPIKE] Documentation check-in

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#229]
### Why are we doing this?
Before we can start doing a documentation refresh, the content team needs a better understanding of what documents already exist and how the engineering team anticipates they will be used.

### Action Requested
Matt does a walkthrough of the existing documentation for the SDK and comes up with a list of problem areas. This will probably involve asking the engineers about their anticipated use case of the documentation, as well as thinking about being an end user who wants to implement DIBBs tools.

### Acceptance Criteria
- [Sarah added in - to be discussed] We have a document/shared resource summarizing what documentation we currently have, what purposes the documentation should serve, and who the intended audience(s) are
- Top issues with our documentation have been identified and tickets created to address them.

**Comment by DanPaseltiner** [comment]
This is done. @mattmgoldberg is working on finalizing a new draft of the CDCgov/phdi README.
