### ISSUE TITLE
Manually integration test record linkage building block in the cloud

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#230]
### Why are we doing this?
The record linkage building block has been implemented in the cloud. Before running production data through this building block, we want to ensure all components are working together as intended.

### Action Requested
Manually test the record linkage building block. This can be with a small amount of dummy data, perhaps 2 HL7v2 messages and one eCR message. The eCR should match to one of the HL7v2 messages, but not the other.

### Acceptance Criteria
When these records flow through the building block, at the end:
1. The MPI is updated as expected
2. FHIR bundles for the matching records are updated as expected

**Comment by emmastephenson** [comment]
Note: this dataset is the one that should be available within Azure Synapse.

**Comment by emmastephenson** [comment]
Not ready yet, as the record linkage building block is not yet ready.

**Comment by DanPaseltiner** [comment]
Need an eval framework. @millzpaugh

**Comment by emmastephenson** [comment]
When doing testing with anonymized data, shouldn't expect to find any matches. 

Testing with prod data will be covered in other quality testing tickets.

3 dummy HL7v2 messages, two that link and one that doesn't. Run them all through and make sure everything is updating as intended (FHIR bundles, MPI updated, etc).

**Comment by emmastephenson** [comment]
@BradySkylight can help to create the sample eCR messages.

We'll want to kick off these messages as XML and HL7v2 messages, to be a true end-to-end test of the pipeline.
