### ISSUE TITLE
eCR Library column widths should be more evenly distributed

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2309]
## What needs to be done

Ensure that the column widths in the eCR Library table are more evenly distributed when the window is wide, particularly the Patient column should be wider

## Why it needs to be done

When the eCR Library window is wide, the column widths are not evenly distributed (it widens the last 2 columns without also widening the first three). 

## Acceptance Criteria

When resizing the browser width, Reportable Condition, RCKMS Rule Summary, and Patient columns should all resize responsively. 

The two date columns should always stay at a constant width.

Refer to designs for relative proportions for each column width

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=4955-47612&m=dev&t=zYuGs1ZKcquAFSSW-1)

[Link to Figma prototype](https://www.figma.com/proto/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?page-id=4955%3A47258&node-id=4955-47612&viewport=-4385%2C2455%2C0.95&t=eC6BEpGPg9yXeSuW-1&scaling=scale-down&content-scaling=fixed)

## Technical Notes
- This ticket follows the work in #2244. Please ensure that the original table designs and functionality are not affected by this ticket's work (see the ticket's acceptance criteria).

**Comment by sarahtress** [comment]
@angelathe sorry totally slipped off my to-do list! will work on it today
