### ISSUE TITLE
Begin populating codes in the query customization page 

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#2311]
Now that the query customization page is built out let's begin taking the limited hard coded sets of codes we currently have and using them to populate this page.

Acceptance Criteria:
When a user clicks on the `Customize Query` button
Then they are brought to the query customization page and the codes we currently have on file for the selected use case query are displayed.

**Comment by bamader** [comment]
Last bit of functionality to add here are the names of the non-chlamydia demo queries that we just landed in the DB, so I'm going to get working on that.
