### ISSUE TITLE
Confirm desired functionality from persistent data store in Starter Kit pipeline

### ISSUE THREAD

**Issue by millzpaugh** [CDCgov/phdi#232]
### Why are we doing this? 
DIBBs is interested in learning more about the value from a persistent data store in this pipeline. 
- Are you interested in aggregating/analyzing data from the FHIR server, ie ELR data? What types of analyses do you envision being useful here?
- Are you interested in using the FHIR server as an audit trail?
- Are there any other scenarios where a DB with preprocessed data would benefit you?

### Action Requested
- Develop list of DIBBs questions around these topics
- Schedule meeting to discuss 

### Acceptance Criteria
- DIBBs understands the value add of a persistent data store outside IRIS 
- DIBBs has decided if those use cases are in scope and if so, how to support them

### Additional Information

**Comment by DanPaseltiner** [comment]
Curious about use cases beyond simply seeding Iris. 

One possibility - ID ELR -> eCR delay

**Comment by DanPaseltiner** [comment]
Will discuss during our sync on Friday (03/24).

**Comment by emmastephenson** [comment]
Discussed during the 3/29 sync - see notes in [this doc](https://docs.google.com/document/d/1i6wfU1llCQ9-X96qpKWC9rHziRSo_nNXgD-YTHoBZzo/edit?usp=sharing).
