### ISSUE TITLE
eCR Library back button fixes

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#2322]
## Description

There are 2 issues with the back button:
* It's a universal browser back button, not a universal link back to the eCR Library
* It's not sticky to the top of the page

## Steps to reproduce

_List out the steps in detail to reproduce the bug_

Issue 1 repro option 1:
1. Open the non integrated viewer homepage
2. Click on an eCR
3. Use the side nav to click on a sub-section
4. Scroll up and click on the back button
5. Directed back to the sub-section of the eCR, not back to the Library

Issue 1 repro option 2:
1. open the non integrated viewer homepage
2. have links to 2 different eCRs
3. open one eCR 
4. then paste a new eCR url into the same browser window
5. click back
6. observe you go back to the first eCR you viewed
7. click back again
8. now you can get back to the Library

Issue 2 repro:
1. Open the eCR Library
2. Open an eCR
3. Scroll down 
4. Notice that you can't see the Back Button anymore

## Expected Result

Back to eCR Library button should always go back to the eCR Library.
Back button should always be sticky to the top of the page.

## Actual result

see video:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelE0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--367faedfc0f5aa0b669905b5d832db821619ddd8/Screen%20Recording%202024-08-05%20at%206.34.21%E2%80%AFPM.mov)

<img width="743" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWJWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b45b22a241e72c69699c3f9f4cc300f27e92427a/Screenshot%202024-09-13%20at%205.58.58%E2%80%AFPM.png" alt="Screenshot 2024-09-13 at 5.58.58 PM.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [x] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

**Comment by emmastephenson** [comment]
This is also an issue if you click on any of the side nav buttons and then scroll up to the top to go back.

This back button shouldn't act as a browser button but instead be a backlink to the eCR Library home page.
