### ISSUE TITLE
Load more eCRs into eCR homepage to make eCR Library feel more realistic

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#2323]
## What needs to be done

We need to load 100 more eCRs into the eCR Library

## Why it needs to be done

We need to load more eCRs into the eCR Library table to allow us to more realistically test the pagination components and replicate the user experience more accurately

## Acceptance Criteria

- [x] Increase amount of seeded eCRs to about 100

## Additional context

It would be nice to include the sample eCRs from TN, KY, and ME as well so we have the full variety of sample data. The rest can be filled with LAC data

**Comment by sarahtress** [comment]
@gordonfarrell if you have time, would love for you to fill in an AC and tech notes! thanks!

**Comment by emmastephenson** [comment]
Want to add the QA eCRs from LAC into this group of tickets.
