### ISSUE TITLE
Update seed-data script to use save data endpoint

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2368]
## What needs to be done

Right now the seed script for the eCR Viewer manually saves data to the database, rather than using the endpoint on the eCR Viewer to do so. It needs to use the endpoint.

## Why it needs to be done

In a deployed scenario, the eCR Viewer is the final phase of the pipeline - it saves both metadata and blob storage for future reading. Right now our seed script doesn't match this user pattern, and instead directly saves data to the database without using the Viewer's endpoint. Since the seed script is the backbone of our local development, this means we're not testing and using the application in the way our users will - which we need to fix.

## Acceptance Criteria

- [ ] Orchestration configuration for seed-data is updated to call the eCR Viewer's `save data` endpoint directly
- [ ] There is NO manual writing to the SQL table in the seed script (excepting any database table setup). Only the Viewer's endpoints are used to interact with the database.

## Technical Notes

Handy links:
* [`create-seed-data.py`](https://github.com/CDCgov/phdi/blob/87f98afcee0ec2218d192bddb316bf2aa7da80dd/containers/ecr-viewer/seed-scripts/create-seed-data.py)
* [`seed-ecr-viewer-config.json`](https://github.com/CDCgov/phdi/blob/87f98afcee0ec2218d192bddb316bf2aa7da80dd/containers/orchestration/app/custom_configs/seed-ecr-viewer-config.json)

**Comment by emmastephenson** [comment]
Considerations from Planning:
* May need to update orchestration service to handle eCR Viewer endpoint
* Need to think about how seed-data interacts with testing config/setup

**Comment by angelathe** [comment]
One more acceptance criteria - Need to remove extraneous schema definitions in `01-init.sql` in this ticket (see [link](https://skylight-hq.slack.com/archives/C05B5R8K0TF/p1723752109454389))

**Comment by angelathe** [comment]
Putting this back into the backlog - still blocked by 2367
