### ISSUE TITLE
Spike: Find samples of known good ECR -> FHIR documents

### ISSUE THREAD

**Issue by nickbristow** [CDCgov/phdi#2377]
## What needs to be done

In order to properly test that our fhir conversion is working as intended, we need a known good before and after sample document.

## Why it needs to be done

Find a Known Good ECR -> FHIR document

## Timebox

1-2 days

## To-do list

- [ ] Find a Known Good ECR -> FHIR document
- [ ] Include in fhir converter source control

**Comment by robertmitchellv** [comment]
Given that both C-CDA and FHIR are conceptual frameworks for modeling data in a healthcare setting, there is no direct analog between the C-CDA eICR 1.1 specification and the FHIR eCR 2.1.2 specification. While both frameworks can represent case report data, they do so using different structures and semantics. Consequently, finding a direct example with an analog between C-CDA and FHIR for eCR is, unfortunately, not fruitful.

My recommendation is to use the COVID-19 test data from the AIMS platform as example C-CDA eICR files. These files can be processed with the Microsoft FHIRConverter to generate FHIR resources. To verify the accuracy of the conversion, we can add the FHIR eCR Implementation Guide to an open-source FHIR server, such as HAPI. By testing the converted documents against the server, we can determine whether they conform to the FHIR eCR profiles. If the server accepts the documents, it indicates that the profiles are correct. Conversely, any errors would suggest issues with the conversion.
