### ISSUE TITLE
Pair with Rin to verify Azure Terraform deployment + update documentation

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2397]
## What needs to be done

Pair with Rin to test the Azure Terraform deployment. This means running the services end-to-end manually, as a user would.

We'll also take this opportunity to dogfood a ["Technical Acceptance Testing" document](https://cdc.sharepoint.com/:w:/r/teams/OPHDST-IRD-DIBBs/Shared%20Documents/CDC%20DIBBs%20Project/Streamline%20Team/1%20-%20Pilot%20eCR%20Viewer%202024/6%20-%20User%20Documentation/Technical%20Acceptance%20Testing%20Guide.docx?d=w16b28bfc6faf4b709eeec5f3fcd2681c&csf=1&web=1&e=0Y2Gtv) that we're planning to use with our jurisdictional partners to test their own installations. This doc is currently a skeleton; please where needed for accuracy.

## Why it needs to be done

The Azure Terraform installation will be used by New Mexico to install DIBBs in their system. Before we turn it over to NM, we need to verify that the installation works as intended. We also need to create a testing guide for our users that will verify installations across a variety of pilot partners.

## Acceptance Criteria

- [ ] Azure installation has been tested end-to-end
    - [ ] eCR run through orchestration endpoint
    - [ ] eCR passes through the entire DIBBs pipeline, as intended
    - [ ] Same eCR is visible in the eCR Viewer
    - [ ] eCR FHIR bundle is present in Azure Blob Storage
- [ ] Technical Acceptance Testing document is updated for accuracy
    - [ ] Document is written for a non-public health, IT-forward audience
    - [ ] No assumptions are made about tooling available to the user, other than the DIBBs AWS infrastructure (i.e., don't assume they're on Macs and have Postman access)
- [ ] A DevOps engineer at a pilot partner could use the Technical Acceptance Testing document to verify their own DIBBs installation

**Comment by rin-skylight** [comment]
A sample URL to get the testing started: http://skylight-dibbs-dev.eastus.cloudapp.azure.com/orchestration/redoc

I've also verified that we can reach the `process-zip` endpoint, which should give us a good next step.

PLEASE NOTE: NO SSL has been hooked up for this. All of this is currently operating unsecured. It will be up to the jurisdictions to ensure proper SSL termination at the gateway with their own certs. (We can change that if needed!)

**Comment by BobanL** [comment]
Documentation has been updated with the proper curl command for the process-zip endpoint.

Right now, @rin-skylight has found a problem with the network connection between the containers, so we're pausing further testing for now.

**Comment by rin-skylight** [comment]
That networking issue was resolved earlier this afternoon. This item is available for further testing.

**Comment by angelathe** [comment]
@emmastephenson Would I need CDC access to pick up this ticket? I can't open/update the Technical Acceptance Testing doc
(Will pick up another ticket in the meantime)
