### ISSUE TITLE
Implement a message parsing service

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#242]
As a user of DIBBs services I would like to be able to extract specific fields from a given message.

**Comment by emmastephenson** [comment]
Give it a mapping between the fields you want and our FHIR server, this message service will determine the paths needed and extract resources from the FHIR server.

This is what we'll use to extract data out of eCR instead of using the tabulation service, which is not ready.

**Comment by DanPaseltiner** [comment]
fixes #242
