### ISSUE TITLE
Identify edge cases for patient-level linkage 

### ISSUE THREAD

**Issue by millzpaugh** [CDCgov/phdi#243]
### Why are we doing this? 
After the record linkage demo and presentation, several edge cases were identified by LAC that our algorithm does not currently handle, including: 
- A person with same name and address (parent & child) 
- A person who has moved

### Acceptance criteria 
- List of all use cases is generated and approved by LAC

### Additional context

**Comment by emmastephenson** [comment]
Added this to the agenda for Wednesday's call.

Request for LAC folks - start a list in advance of the Wednesday meeting.

@emmastephenson to make sure the power point from Friday's demo is shared; @millzpaugh to share the demo recording from Friday in Slack.

**Comment by DanPaseltiner** [comment]
Not blocked, but want to explore once MVP is deployed.

**Comment by emmastephenson** [comment]
Person matching edge cases can be found here: https://lacounty.sharepoint.com/:b:/t/USDSPHDIPilot/Eezvee0sfA5LsYRzX88wc4oBMDjel55lJcmpNffSnXTRIA?e=9NazLn
