### ISSUE TITLE
Create flat schema to seed the MPI

### ISSUE THREAD

**Issue by millzpaugh** [CDCgov/phdi#244]
### Why are we doing this?
If DIBBs/LAC develop the interface needed for seeding the MPI, it will be relatively easy to switch out the source data. 

### Action Requested
SDK team to determine which fields they'll need access to in an MPI, and provide that schema to LAC.

### Acceptance Criteria
LAC has the schema that the DIBBs team has requested for seeding their MPI.

**Comment by emmastephenson** [comment]
@emmastephenson to create followup ticket for provisioning the MPI in IaC.

**Comment by emmastephenson** [comment]
I believe we've come up with the desired database schema for the MPI, which should inform this schema. (See [this diagram](https://drive.google.com/file/d/1auCHbVG121WDofGwpxaHffpt-nQD4s9S/view?usp=sharing) for details).

The next steps on this ticket are therefore to translate those database tables into a schema that LAC can use to create a flat file from their existing COVID data.

**Comment by emmastephenson** [comment]
Schema has been passed to LAC.
