### ISSUE TITLE
BUG: Pulling only first Emergency Contact

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2465]
## Description

Currently, we are only pulling and displaying the _first_ Emergency Contact available. We should be displaying **all** available emergency contacts.

## Steps to reproduce

**Relevant files:**
- `evaluateEmergencyContact` in `src/app/services/evaluateFhirDataService.ts`
- `patientEmergencyContact` in `fhirPath.yml`

## Expected Result

GIVEN a patient's eCR
WHEN there are multiple emergency contacts available
THEN we should be displaying all of them in the eCR Viewer.

## Actual result

We're only pulling the first emergency contact (no examples I've found, but as seen in the FHIR path below). Will have to test this by manually adding +1 emergency contacts
```
patientEmergencyContact: "Bundle.entry.resource.where(resourceType = 'Patient').contact.first()" # HERE
```

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

**Comment by mcmcgrath13** [comment]
I believe this was already fixed in https://github.com/CDCgov/phdi/pull/2909 - okay to close?

**Comment by angelathe** [comment]
Sounds good to me!
