### ISSUE TITLE
SPIKE: Investigate reason for Release 1.6.0 failing

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2466]
## What needs to be done

_Provide a summary of the task that needs to be completed_
- Investigate and provide potential resolution to ensure broken changes are not allowed to get deployed.

## Why it needs to be done

_Describe the importance or impact of completing this task_
- Determine why Release 1.6.0 got passed the github checks

## Acceptance Criteria

_List out all expected functionality/requirements_

- 

## Technical Notes

_Owned by eng team - write out any important technical considerations such as: architecture plan/notes, data dependencies, testing plan, etc. Also link any tickets that are dependent on or related to this task_

- 

## Additional context

[OPTIONAL, delete if not needed] 
_Include any additional context or information here that doesn't fit into other parts of the template_

**Comment by emmastephenson** [comment]
@BobanL is this still an issue?

**Comment by BobanL** [comment]
This is still an issue, I did not have time to investigate.
