### ISSUE TITLE
Add updated language and country info to Patient Demographics

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#2480]
## User Story

As a user, I want to view an updated demographics section, so that I can more easily see details about a patient

## Acceptance Criteria

- [ ] Display "Mode of Expression" and "Proficiency Level" on new lines under Preferred language if they exist
- [x] Add "Country" field according to designs
- [ ] Missing fields are included in the unavailable info section
- [ ] update tests

## Scenarios

- I open an eCR in the viewer
- I now see more detailed language and country information about a patient

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=7006-93&node-type=CANVAS&m=dev)
[Link to Figma design with comments](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=7006-69929&node-type=INSTANCE&m=dev)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_

<img width="774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3U2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6407a18b7f8c240503121123bb20ab4ab467db3e/Screenshot%202024-09-06%20at%203.30.49%E2%80%AFPM.png" alt="Screenshot 2024-09-06 at 3.30.49 PM.png" />

## Additional context

Date of death and expanded race/ethnicity information added in #2518.

**Comment by mcmcgrath13** [comment]
@akintner do you want to create a new ticket for the language part and reduce this ticket down to just country?
