### ISSUE TITLE
Add "Encounter Diagnosis" and "Encounter Reason" to Encounter section

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#2481]
## User Story

As a user, I want to see more info about encounters, so that I can better understand the case report I'm viewing.

## Acceptance Criteria

- [ ] Add "Encounter Diagnosis" to encounter details
- [ ] Add "Encounter Reason" to encounter details
- [ ] Missing fields are included in the unavailable info section
- [ ] Update tests

## Scenarios

- I open an eCR in the viewer
- I now see more detailed information about the encounter

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=7006-93&node-type=CANVAS&m=dev)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_

<img width="693" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1c2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--247850dca1cc4fb9c72dcf21f537ad595ed39778/Screenshot%202024-09-06%20at%203.15.31%E2%80%AFPM.png" alt="Screenshot 2024-09-06 at 3.15.31 PM.png" />

**Comment by emmastephenson** [comment]
Encounter reason is different from reason for visit. 
RFV: clinical provider notes about why the patient visited
Encounter reason: Used as billing codes for insurance; not a free text field.

**Comment by emmastephenson** [comment]
Finding examples should be timeboxed to no more than one day.

**Comment by gordonfarrell** [comment]
Spent a day digging through eCRs trying to find and example of either of these fields with no luck. Gonna stick this in the icebox til Emma is back from OOO to discuss

**Comment by austin-hall-skylight** [comment]
https://github.com/HL7/CDA-phcaserpt-1.3.0/blob/main/examples/samples/CDAR2_IG_PHCASERPT_R2_D3_SAMPLE.xml

This eCR should have encounter diagnosis and encounter reason info.

**Comment by austin-hall-skylight** [comment]
eCR with ID 3e0d3f9b-4b26-47d2-9ddd-3ac4d7045382
ffa9550f-9a88-4348-9da3-4ca4a1e5f554 has encounter diagnosis info

**Comment by BobanL** [comment]
Encounter diagnosis was added but encounter reason wasn't because the field for encounter reason doesn't exist until ecr version 3.1
