### ISSUE TITLE
Add Encounter Care Team Table to Encounter Details

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#2482]
## User Story

As a user, I want to see a new section and table in Encounter Details with Encounter Care team info, so that I can understand who interacted with the patient.

## Acceptance Criteria

- [ ] New field under Encounter Details called `Encounter Care Team`
- [ ] The new field contains a table with 4 columns: Name, Role, Status, Dates
- [ ] Cells without data display No Data
- [ ] Update tests

## Scenarios

- While viewing an eCR, I want to know more about who my patient interacted with during their encounter
- I scroll down to Encounter Details
- I view the new Encounter Care Team table to find my desired info

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=7006-93&node-type=CANVAS&m=dev)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_

<img width="837" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd202Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--410a5800f602a920d664c328191f530e79bd88d2/Screenshot%202024-09-06%20at%203.24.34%E2%80%AFPM.png" alt="Screenshot 2024-09-06 at 3.24.34 PM.png" />

**Comment by emmastephenson** [comment]
This is distinct from the other "care team" field in the eCR - this one is explicitly associated with the encounter.

**Comment by angelathe** [comment]
Examples:
0aa7a9c2-87e4-4115-876e-b0253bb8dabf
8fd139db-e099-4d34-90ad-3c3e70d8704a
8a0d1c4d-6ab6-43b1-8671-cebc15e2d1af
5b491f54-a7d8-46a7-bb2f-4a6a96ca5a86
5ff5928a-6c29-4a0c-bbe5-c96484bbd22c
6a6bcd7d-7bad-48f6-9e0b-39a4ec9e063e
