### ISSUE TITLE
Add eRSD warnings to the eCR Viewer

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2505]
## User Story

As a user of eCR data, I need to be able to see warnings coming from AIMs about eRSD versions so that I can tell my providers that updates are needed.

## Acceptance Criteria

- [x] when available, eRSD warning data/messages are extracted from RRs and added to the FHIR bundle
- [x] eRSD warnings table added within the `eCR Metadata` section 
- [x] Table contains:
    - [x] Warning text
    - [x] Version in use
    - [x] Expected version
    - [x] Suggested solution
- [x] When eRSD warning comes in on an eCR, this table is populated
- [x] Table follows design and meets styling requirements

## Scenarios

_Write out scenarios that will help to ensure the functionality works as expected_
**Scenario 1:** 
- An eCR with eRSD version issues is sent to me from AIMs
- This eCR goes through DIBBs pipeline
- eCR Viewer renders the warning within the `eCR Metadata` section

**Scenario 2:**
- An eCR without any warnings is sent from AIMs
- This eCR goes through the DIBBs pipeline
- eCR Viewer does not render the warnings table

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=7006-93&node-type=CANVAS&m=dev)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_
<img width="771" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWU1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb33bc1af92870958f15082e95045767909f04b6/Screenshot%202024-09-06%20at%202.00.28%E2%80%AFPM.png" alt="Screenshot 2024-09-06 at 2.00.28 PM.png" />

## Additional context

This information was recently added by AIMS to RR files. The intent is that providers will know if their trigger codes are out of date, and update them. AIMs has asked public health departments to monitor these warnings and reach out to providers when they're seen, but surveillance systems (i.e., NBS) aren't processing these warnings yet so most users don't have a way to see them. Adding them to the Viewer will unlock this data for our pilot jurisdictions.

Sarah has more information about where in the RR document the eRSD warnings can be found

<img width="1039" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkRPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44f34cd01c2486bba9f34edc8bf114c34371ccc8/Screenshot%202024-09-12%20at%209.51.06%E2%80%AFAM.png" alt="Screenshot 2024-09-12 at 9.51.06 AM.png" />

**Comment by emmastephenson** [comment]
We'll also need to determine where in the FHIR bundle this warning should live.

**Comment by sarahtress** [comment]
@lina-roth updated this ticket with more details on where to look in xml and html for the data here!
