### ISSUE TITLE
Update query page to let users know when they are executing custom query

### ISSUE THREAD

**Issue by m-goggins** [CDCgov/phdi#2515]
Right now, when a user clicks on the "Apply Changes" button on the customize page, nothing happens. Once users are back on the query page (#2515), we need to signal to users that they are executing a custom query.

Acceptance Criteria:
After clicking "Apply Changes" on the customize page and being rerouted, the query page has some notification to let them know that they are executing the custom query they created (might need design work on this)

**Comment by fzhao99** [comment]
Chatted with @lg-king and we decided we'll use something similar to a SimpleReport pattern where a toast slides in from the side on redirection

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd20vQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e712a6851d9625ae424665b9a7df0219fa5ea185/Screen%20Recording%202024-09-09%20at%202.24.15%E2%80%AFPM.mov)
