### ISSUE TITLE
Bug: fix the up/down arrow on accordions across tabs

### ISSUE THREAD

**Issue by robertandremitchell** [CDCgov/phdi#2521]
https://github.com/CDCgov/phdi/pull/2363#discussion_r1750645386

This will require fixing customize-query component such that the arrow state is dependent on each individual accordion to avoid it inheriting the state of the prior tab's.

**Comment by fzhao99** [comment]
This should get solved once [#2545](https://github.com/CDCgov/phdi/pull/2545) lands
