### ISSUE TITLE
Write back end function that separates DB returned rows by coding system

### ISSUE THREAD

**Issue by bamader** [CDCgov/phdi#2522]

**Comment by bamader** [comment]
Now that we have a DB client set up and can successfully retrieve rows from the postgres instance in TEFCA, we want to be able to filter and group these results according to the coding scheme to which they belong. To do this, we need a back end server function in the `database-service.ts` file that separates results into different groups based on their coding scheme. This function should be called after splitting up the rows into their respective clinical service types (labs, conditions, and meds).

**Comment by fzhao99** [comment]
think the [db client diff](https://github.com/CDCgov/phdi/pull/2507) needs to go in first before we can start work on this
