### ISSUE TITLE
Implement Step Counter

### ISSUE THREAD

**Issue by m-goggins** [CDCgov/phdi#2559]
Using [these ](https://www.figma.com/design/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Site-Experiences?node-id=3576-42191&node-type=frame&m=dev#941920681)Figma designs, implement the step count to let users know where they are in the process

**Comment by fzhao99** [comment]
Will punt until after we implement the patient / query selection screens as discussed in 9/18 standup
