### ISSUE TITLE
Back button isn't sticky to top of page

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#2560]
## Description

When I scroll down in the non-integrated Viewer, the back button isn't sticky to the top of the page, which makes it hard to know how to get back to the Library

## Steps to reproduce

1. Open the eCR Library
2. Open an eCR
3. Scroll down 
4. Notice that you can't see the Back Button anymore

## Expected Result

I should always be able to see the Back button

## Actual result

I can't see the Back button

<img width="743" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWJWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b45b22a241e72c69699c3f9f4cc300f27e92427a/Screenshot%202024-09-13%20at%205.58.58%E2%80%AFPM.png" alt="Screenshot 2024-09-13 at 5.58.58 PM.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [x] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_

**Comment by emmastephenson** [comment]
Closing for #2322
