### ISSUE TITLE
Update TEFCA Viewer Deployment

### ISSUE THREAD

**Issue by m-goggins** [CDCgov/phdi#2565]
Requirements:
- Tefca viewer is looking to be able to run database migrations in AWS using flyway
- Tefca viewer wants to connect the app to rds database in AWS

Notes:
phdi-playground: terraform repo that manages and deploys the tefca viewer to AWS (+ other DIBBS projects)
phdi-chats: charts repo used by helm to deploy to the AKS cluster in AWS

**Comment by alismx** [comment]
phdi-playground: https://github.com/CDCgov/phdi-playground/pull/87
phdi-charts: https://github.com/CDCgov/phdi-charts
