### ISSUE TITLE
Make integration tests spin up postgres DB

### ISSUE THREAD

**Issue by bamader** [CDCgov/phdi#2575]

**Comment by bamader** [comment]
This slack thread describes the state of the problem well: https://skylight-hq.slack.com/archives/C05BEG226RZ/p1726609799147699

The scope of this ticket is to spin up the postgres query database when running integration tests so that our API back end can successfully get value sets from it when executing queries.

**Comment by fzhao99** [comment]
We should probably wait to action this one until we figure out the final plan for our flyway setup as discussed here: https://skylight-hq.slack.com/archives/C05BEG226RZ/p1727375001319769

**Comment by fzhao99** [comment]
made a copy in linear https://linear.app/skylight-cdc/issue/QUE-47/make-integration-tests-spin-up-postgres-db
