### ISSUE TITLE
Review TEFCA SearchForm Name Regex

### ISSUE THREAD

**Issue by robertandremitchell** [CDCgov/phdi#2584]
<img width="733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3pxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54d06c8adac734a26c93d941ac164081deb15441/Screenshot%202024-09-19%20at%201.11.38%E2%80%AFPM.png" alt="Screenshot 2024-09-19 at 1.11.38 PM.png" />

We will want to revisit / determine best way to handle, perhaps akin to what we do with phone where a search is done with and without special characters.

**Comment by m-goggins** [comment]
Same as #2590
