### ISSUE TITLE
BUG: Fix accordion interaction in eCR Summary

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2598]
## Description

In the eCR Summary, there's an odd behavior: when you open accordions under one relevant condition and then move to open the next relevant condition, the page scroll position is lost. (Refer to the Loom video or the section below for steps to reproduce this issue). Please fix this interaction.

## Steps to reproduce

View this eCR: [f3eae968-d262-40f1-b1cb-699dda5b395a](http://localhost:3000/view-data?id=1.2.840.114350.1.13.297.3.7.8.688883.538441)

1. Navigate to the eCR Summary -> Condition Summary
2. Open `Shigellosis (disorder)` accordion -> Open the two accordions under "Lab Results Relevant to Reportable Condition"
3. Open the `Salmonella infection (disorder)` accordion
4. You will see that the page immediately jumps to the bottom of the eCR Viewer instead of viewing the Salmonella accordion.

## Expected Result

WHEN clicking on accordion information
THEN you should not lose your spot on the page, and accordion information should be immediately viewable

## Actual result

See: Steps to Reproduce section

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Example Loom

https://github.com/user-attachments/assets/4f5d48dc-e659-4023-87f8-d758d508f5d5

**Comment by austin-hall-skylight** [comment]
Try creating a new page or new app to test the react uswds accordion component with a clean slate and see if this is a bug with the framework.
