### ISSUE TITLE
Develop base MPI connector class

### ISSUE THREAD

**Issue by m-goggins** [CDCgov/phdi#260]
### Why are we doing this?
We are developing an external MPI for the purposes of record linkage. Users should be able to query the MPI for blocks of data that they can use to check for matches when a new patient record comes in. In anticipation of STLTs wanting to use different setups for their MPIs (or to integrate with an existing MPI), we need to create a connector class that is database-agnostic.

### Action Requested
Develop a database-agnostic class that can connect to a user's MPI database and query (block) for the purposes of record linkage

### Acceptance Criteria
Connector base class is created 
The base class includes an abstract method for blocking data within a given database type
The blocking abstract method returns a LoL of data matching the blocking criteria

### Additional Information
For the MVP record linkage in LAC, we plan to use Postgres for the MPI database.

**Comment by emmastephenson** [comment]
@m-goggins to split this into a base ticket and a Postgres-specific ticket.
