### ISSUE TITLE
SPIKE: Pulling relevant encounters to the Reportable Conditions Summary

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2604]
## What needs to be done

Determine if we can modify the TCR service to stamp Encounter resources and pull this information to the Reportable Conditions summary.

Although we do not currently pull relevant encounter information to the Conditions Summary, this could potentially be useful information for epis and case investigators, especially since we've encountered RCKMS Rules based on encounter information. 

Example eCR: [Link](http://localhost:3000/view-data?id=df33f075-83a1-4d28-ba63-05bcc3339c21#ecr-summary)

<img width="1473" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXZ2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--628598651e70bdbbeb68551ef02be1ff9d4cca10/Screenshot%202024-09-20%20at%2013.01.34.png" alt="Screenshot 2024-09-20 at 13.01.34.png" />

## Why it needs to be done

The Relevant lab & clinical info sections in the eCR Summary help epis and case investigators get a sense of what exactly in the whole eCR document caused the eCR to be sent to them. Pulling up these most relevant bits of information to the top can help them to make a decision more quickly about what to do with the document and what data to look for in more detail in the whole eCR. If we don't display the right information there, we may not actually save any time, so we want to make sure that we have a good sense of how this functionality is working for a few eCRs so we can make sure one of the big value propositions of the eCR Viewer is going to work when pilots are in full gear.

## Timebox

_How much time should be dedicated to this spike?_

## To-do list

- [ ] Check if there are other examples of eCRS with encounters in their triggerable RCKMS rule summary.
- [ ] Are there codes associated with the encounter RCKMS rule? Are there codes associated with the Encounter that could be stamped? Would it be possible to stamp these encounters in the TCR service and bubble this information to the Condition Summary?

## Additional context

**Relevant files:**
- TCR Service: `containers/trigger-code-reference/app/main.py`

**Comment by emmastephenson** [comment]
@angelathe thank you for writing this ticket up! Do we know if the eRSD table that powers the TCR includes encounter information?

**Comment by lina-roth** [comment]
Looks like we should be able to link an Encounter to a condition through Encounter.reasonReference which can be a Condition, Procedure, Observation, ImmunizationRecommendation - Reason the encounter takes place, expressed as a code. For admissions, this can be used for a coded admission diagnosis.

Unfortunately I can't find any example ecrs with an encounter with a reason reference to tie it to a condition 


 https://www.hl7.org/fhir/R4/encounter-definitions.html#Encounter.reasonReference

**Comment by lina-roth** [comment]
Example ecr from hl7 https://www.hl7.org/fhir/R4/encounter-example-f203-20130311.json.html
