### ISSUE TITLE
Check eCR MVP field data correctness for a few eCRs

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#2625]
## Action Requested

Once we believe we have completed all work to get the new and high priority MVP field changes into the eCR Viewer, Sarah would like to pair with a dev to compare the output of the eCR Viewer with the original data in the corresponding eCR to ensure we are converting and displaying those fields correctly (especially Encounter Details and Author Details). 

This ticket will involve meeting with Sarah to go through 3-5 eCRs that have been processed through the eCR Viewer. We'll be looking at the eCR Viewer and original eCR file (both xml and html for eICR and RR) side by side to try to figure out if the data looks correct in our Viewer. 

## Acceptance Criteria

Ticket is done once assigned dev pairs with Sarah for 3-5 eCRs, and writes up any corresponding tickets that come out of any issues identified during pairing

## Additional Information

This ticket is currently blocked until the MVP changes are complete

**Comment by angelathe** [comment]
Adding a note to check this specific eCR for RR relevant conditions: http://localhost:3000/view-data?id=1.2.840.114350.1.13.206.2.7.8.688883.470000397#ecr-summary

**Comment by emmastephenson** [comment]
Specific fields to check:

<img width="722" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUtUQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8374a432bc9fb0ba87587cf485f9f0528d6743a/Screenshot%202024-11-04%20at%2010.38.42%E2%80%AFAM.png" alt="Screenshot 2024-11-04 at 10.38.42 AM.png" />
