### ISSUE TITLE
Philadelphia Documentation for setting up eCR Tables

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2634]
## What needs to be done

Create user documentation (a Word doc or PDF) to guide users through the process of adding our metadata tables to a SQLServer in Philadelphia.

## Why it needs to be done

Philly is using the non-integrated Viewer, which means they'll need to set up the SQL metadata tables. They already have a SQL Server database, so we just need them to run the setup scripts to create our specific tables.

By the time they get to this point of the process, they'll already have worked with our DevOps team to install the core Viewer infrastructure (the DIBBs pipeline and eCR Viewer). However the AWS installation does not account for any of our database infrastructure, since Philadelphia already has a database set up - we just need to make sure the right tables have been added.

## Acceptance Criteria

- [ ] Word doc for Philadelphia's installation has been created and sent to Matt G. for review
- [ ] Doc outlines the specific steps to set up the metadata tables (including Github links) 

## Additional context

These docs should live in Sharepoint here: [Philadelphia Installation Instructions](https://cdc.sharepoint.com/:w:/r/teams/OPHDST-IRD-DIBBs/Shared%20Documents/CDC%20DIBBs%20Project/Streamline%20Team/1%20-%20Pilot%20eCR%20Viewer%202024/6%20-%20User%20Documentation/Philadelphia%20Installation%20Guide.docx?d=wc538c25995f24379bf7fa3da98ed044f&csf=1&web=1&e=UJyBZO).

If you don't have SharePoint access, you can start the doc in GDrive here: https://docs.google.com/document/d/1kriQIMYSVyigCCNn2hMibj7HyFPWC3UUpOzd05pXNgQ/edit?usp=sharing

**Comment by BobanL** [comment]
Reviewed by Matt Goldberg. 

@alismx - Can you take a look when you have a chance? 
https://cdc.sharepoint.com/:w:/r/teams/OPHDST-IRD-DIBBs/_layouts/15/Doc.aspx?sourcedoc=%7BC538C259-95F2-4379-BF7F-A3DA98ED044F%7D&file=Philadelphia%20Installation%20Guide%20-%20Metadata.docx&action=default&mobileredirect=true

**Comment by alismx** [comment]
✅ Signed
