### ISSUE TITLE
eCRs loading times taking over 1 minute

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2679]
## Description

Some eCRs take over 1 minute to load

## Steps to reproduce

_List out the steps in detail to reproduce the bug_

1. View eCR Maine 2: 1.2.840.114350.1.13.206.2.7.8.688883.470000397 http://localhost:3000/view-data?id=1.2.840.114350.1.13.206.2.7.8.688883.470000397

## Expected Result

Loading should take less than 10 - 15 seconds

## Actual result

Loading takes more than 1 minute.

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [x] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

- Add a test to ensure this bug does not occur again.
- 

## Acceptance Criteria
* Bug is fixed OR a ticket is created to address the root cause.

**Comment by gordonfarrell** [comment]
LAC Data 6100896d-b520-497c-b2fe-1c111c679274 also has this issue

**Comment by BobanL** [comment]
Another one - Maine 2 -  http://localhost:3000/view-data?id=1.2.840.114350.1.13.206.2.7.8.688883.470000397
