### ISSUE TITLE
BUG: Side navigation highlights multiple sections when they have the same name

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2681]
## Description

Side navigation highlights multiple sections when sections have the same name. 

Issue: The [lab section ID](https://github.com/CDCgov/phdi/blob/2fb9f57cba737701e1977b07bb5d65d39c515b08/containers/ecr-viewer/src/app/view-data/components/LabInfo.tsx#L49) is not unique. [Side navigation currently generates the ID](https://github.com/CDCgov/phdi/blob/dc691e2dc0733924b00d85fb997fe5e4cfda438b/containers/ecr-viewer/src/app/view-data/components/SideNav.tsx#L142) based on the section title. 

## Steps to reproduce

1. Visit TN2 - http://localhost:3000/view-data?id=0a094680-9a5d-45b5-bdda-197f79df2d03
2. Click on [Lab Results from Stonecrest Medical Center -](http://localhost:3000/view-data?id=0a094680-9a5d-45b5-bdda-197f79df2d03#lab-results-from-stonecrest-medical-center--) in the side nav

## Expected Result

Only one section is highlighted.

## Actual result

Two sections are highlighted.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/e2c5ba65-ec89-41fa-a509-8e19d2b707fc">

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [x] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

- Side navigation will need to be refactored to get the proper ID.

**Comment by mcmcgrath13** [comment]
Looks like this was already fixed by the fix to name truncation
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeC9iQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbd2b36a69b434a4c49016bf921d4b9e81c72c37/image.png" alt="image.png" />
