### ISSUE TITLE
BUG: Only the first travel history appears in the eCR Viewer

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2682]
## Description

Only the first travel history appears in the eCR Viewer

Issue: All travel history is properly saved in the FHIR bundle :), but we are only looking at the first result from our [fhir path](https://github.com/CDCgov/phdi/blob/951a0974c2ba086c94b2a2b580c97ce71cbe600c/containers/ecr-viewer/src/app/services/evaluateFhirDataService.ts#L162-L165). 

## Steps to reproduce

_List out the steps in detail to reproduce the bug_

1. Visit [4aca74f4-c3b7-49ce-a437-1c8594451926](http://localhost:3000/view-data?id=1.2.840.114350.1.13.572.3.7.8.688883.102910)
2. View Social History -> Travel History

## Expected Result

- All travel history appears like in the eiCR html

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/ba1e55a7-e385-406d-ac67-db1a847ced5f">

## Actual result

- Only the first travel history appears
<img width="670" alt="image" src="https://github.com/user-attachments/assets/734a2706-c8a4-47af-994a-e22902e393dd">

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [x] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

- Design to provide guidance on how to display multiple entries.
  - Put all Location, Start Date, End Date, Purpose, into a table 
- Ensure that it still works with a single entry travel history

**Comment by sarahtress** [comment]
@BobanL sorry just getting to this now. could we just make travel history into a table with the columns being:
- Location
- Start Date
- End Date
- Purpose

**Comment by BobanL** [comment]
Yep that should be doable! Thanks!

**Comment by BobanL** [comment]
> @BobanL sorry just getting to this now. could we just make travel history into a table with the columns being:
> 
> * Location
> * Start Date
> * End Date
> * Purpose

Yep that should be doable! Thanks!
