### ISSUE TITLE
BUG: Missing smoking information

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2683]
## Description

Missing smoking information in the social history section when it's only available in table. FHIR conversion work will be required to convert from table elements to proper FHIR elements.

## Steps to reproduce

_List out the steps in detail to reproduce the bug_

Missing tobacco use (not a smoker):
1. Visit [ffa9550f-9a88-4348-9da3-4ca4a1e5f554](http://localhost:3000/view-data?id=a28c8b0e-b06a-11ec-81e0-9e7eef92c510) OR [7f02b35a-b172-4845-af55-d173574e5579)
](http://localhost:3000/view-data?id=ad06575f-c7fe-11ec-81e1-8465ad080d41)
2. Social History -> Tobacco Use

Missing additional information:
1. Visit  [0aa7a9c2-87e4-4115-876e-b0253bb8dabf](http://localhost:3000/view-data?id=1.2.840.114350.1.13.202.3.7.8.688883.324) (smoker)
2. Social History -> Tobacco Use

## Expected Result

_Explain how it should function if the bug was fixed. Attach screenshot if applicable_

## Actual result

_Explain what's happening now when the bug is present. Attach screenshot if applicable_
1. 
![image](https://github.com/user-attachments/assets/ae73850d-e4a4-4614-8281-28097370f6e5)
![image](https://github.com/user-attachments/assets/27bf6a3e-9cb0-41b7-a514-e5817895a568)
2. Missing additional information on how they smoke:
<img width="421" alt="image" src="https://github.com/user-attachments/assets/b53e82b4-3ac1-4fa3-9c10-eb1bc16f14c7">
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/06b10ec0-53f9-4215-bf78-8ac80f68e6b5">

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [x] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_
- Example of one that works - http://localhost:3000/view-data?id=1.2.840.114350.1.13.202.3.7.8.688883.486

**Comment by sarahtress** [comment]
@BobanL this one is a little trickier. do you know which of the fields we could convert to FHIR out of what is shown?

**Comment by BobanL** [comment]
> * [7f02b35a-b172-4845-af55-d173574e5579)
>   ](http://localhost:3000/view-data?id=ad06575f-c7fe-11ec-81e1-8465ad080d41)

I believe all of the data can be converted to FHIR, but most of the eICR examples we have only have that First "Smoking Status" column.

**Comment by BobanL** [comment]
> @BobanL this one is a little trickier. do you know which of the fields we could convert to FHIR out of what is shown?

I believe all of the data can be converted to FHIR, but most of the eICR examples we have only have that First "Smoking Status" column.

**Comment by sarahtress** [comment]
@BobanL can we make a table with the following columns:

- Smoking Status
- Duration
- Type
- Amount
- Observation Date

where:
- duration is calculated from start date to end date, or just total number of years. 
- type would be cigarettes, etc
- amount is # of packs per day, or whatever else could be a possible data input there
- and observation date is just the date is was added to the medical record

**Comment by mcmcgrath13** [comment]
I've split off the request to make a table with more data to #2883, while this ticket will just address the missing smoking status data
