### ISSUE TITLE
Make the convert-seed-data script async

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2687]
## What needs to be done

- Convert seed data scripts should make async requests to the orchestration service

## Why it needs to be done

- The script can take 10+ minutes depending on the user's computer

## Acceptance Criteria

- Convert seed data script makes async requests to the orchestration service.
- Convert seed data is noticeably quicker.

## Additional context

- Test on multiple machines, @lina-roth has an intel mac.

**Comment by emmastephenson** [comment]
@mcmcgrath13 apparently we had a backlog ticket for this the whole time!

**Comment by mcmcgrath13** [comment]
oh nice! done.
