### ISSUE TITLE
Add additional regression testing to the eCR Viewer

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2693]
## What needs to be done

- Create tests for the eCR viewer to ensure no regression has occurred

## Why it needs to be done

- Regressions have been introduced recently in unrelated eCRs.
  - #2679
  - #2672  

## Acceptance Criteria

- Tests run during CI to ensure no regressions occur.
- Bundles should be freshly generated for the test
- At least 1 eICR from every jurisdiction should be used.
- Should be expandable to add additional bundles in the future.

## Technical Notes

- Could possibly be creating snapshot tests using [playwright](https://playwright.dev/docs/test-snapshots).
- Could also expand existing jest snapshot tests, but add additional steps to regenerate those bundles.

**Comment by emmastephenson** [comment]
Closing this in favor of the broader playwright testing spike discussed in our tech debt meeting.
