### ISSUE TITLE
[EPIC] Personas

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#271]
### Why are we working on this? 
As a member of the DIBBs team, I need to have personas, so that I can better understand our users 

As we are trying to integrate RDC into our team, our first step is being able to become experts on our users (or potential users). Personas are a critical artifact for UX to clearly communicate and align on who our users are, what they care about, and what their pain points are. 

### What problem does it solve?
Right now, our team does not have the ability to write user stories for tickets/epics because we're lacking a clear understanding of our users. We also cannot conduct other key research and design activities without having in depth knowledge of our users.

### Acceptance Criteria (Requirements)
- Have a draft of personas ready for team review
- Create list of questions and next steps needed to continue to build out personas, if needed
- Our team starts to become aligned on who are users are

**Comment by aathwal3** [comment]
**Sprint Goals**
- Gather information from other LAC research efforts to validate personas
