### ISSUE TITLE
BUG: Missing Associated Diagnosis

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#2711]
## Description

The plan of treatment table is showing no data in the Associated Diagnoses column when data exists in the eCR.

## Steps to reproduce

_List out the steps in detail to reproduce the bug_

1. Open one of these eCRs: 10e5b07b-5d3f-426f-a7e1-13ea909ff5a5 or 8a0d1c4d-6ab6-43b1-8671-cebc15e2d1af
2. Under Treatment Details look for the Plan of Treatment table
3. Observe the Associated Diagnosis column and its sad state of "No Data"

## Expected Result

We should see the table populated with the Associated Diagnosis data

## Actual result

<img width="1551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVV3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--499f9c78568dc4f6dbfe89058dfaa7786f26308c/5.png" alt="5.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [X] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_

**Comment by lina-roth** [comment]
Looked into this and both ecrs look good

<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW5UQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e658a6a563af3f5b6ad1d040761e24ecc292913/Screen%20Shot%202024-11-20%20at%2010.33.24%20AM.png" alt="Screen Shot 2024-11-20 at 10.33.24 AM.png" />
