### ISSUE TITLE
BUG: Missing Administered Medication info

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/phdi#2712]
## Description

Administered medication data is present in an eCR but showing as missing data in the eCR viewer.

## Steps to reproduce

1. Open the following eCRs: 2ff3119d-b933-4236-8746-53726e291449, 7f02b35a-b172-4845-af55-d173574e5579, ffa9550f-9a88-4348-9da3-4ca4a1e5f554, TN_sample eCR4, 0aa7a9c2-87e4-4115-876e-b0253bb8dabf, 3d607116-9e59-4e42-a084-c5cff4b023f1
2. No data for administered medications is displayed under treatment details

## Expected Result

We should see administered medications data properly displayed

## Actual result

<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBell3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3e35f26aacfa400ded07587923284ebdb88c419/8.png" alt="8.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [X] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_

**Comment by emmastephenson** [comment]
This should be covered by #2772 and #2799
