### ISSUE TITLE
BUG: Add interpretation codes to Ref Range column in lab tables

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2716]
## Description

We do not currently display interpretation codes for reference ranges for lab observations. We need to convert this to FHIR and display it if a lab component (observation) has this information.

## Notes

Note: This ticket specifically adds the interpretation code for the lab component tables' **Ref Range** column (we already added the interpretation code for the Value column).

**Acceptance criteria:**
- [ ] FHIR conversion for the `<interpretationCode>` information _under_ the `<referenceRange>` information. Please check the R4 FHIR spec to determine where this information should live.
- [ ] If available, ensure that the Ref Range column displays the interpretation code in the table (similar to how the Value column displays their interpretation codes).
- [ ] Add tests

**Relevant files/functions:**
- `_Observation.liquid`
- `observationReferenceRange` path in `fhirPath.yml`
- `evaluateDiagnosticReportData` in `labsService.tsx`

## Steps to reproduce

Example eCR:
- TN_sample eCR2: [Interpretation code for lab ref range is not displayed when info is available](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724877751862769)

## Expected Result

If an interpretation code exists for a **Ref Range** in the lab component table, it should be displayed.

## Actual result

Example from `TN_sample eCR2`:
<img width="1795" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFV3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d943bb935d85cf8b212c1e450875e0c865946fa7/image.png" alt="image.png" />

## Priority

_Provide a estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [x] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

**Comment by mcmcgrath13** [comment]
What does it mean for the reference range to be low here? Are we sure this isn't really just duplicate info with the value's interpretation code? @angelathe @ashton-skylight @emmastephenson

**Comment by mcmcgrath13** [comment]
Should we close this out as a data issue?

**Comment by angelathe** [comment]
Works for me unless Ashton/Emma have any thoughts

**Comment by ashton-skylight** [comment]
Good to close
