### ISSUE TITLE
Update  ecr viewer to use core schema

### ISSUE THREAD

**Issue by lina-roth** [CDCgov/phdi#2719]
## What needs to be done
 ~We need to remove the local schema / or update the local schema to match the core schema. Ideally we would only use one schema~

Turns out the core schema hasn't been implemented at all yet, changing this ticket to do that

## Why it needs to be done
~We need to store conditions and rule summaries not in 1 string so we can display them better. Our local schemas should match what the clients will use~

Core schema ecr_data table is critical to our future implementation of filtering etc on the eCR library

## Acceptance Criteria
- [ ] The core schema is used to save
- [ ] Convert seed data works
- [ ] Update data retrieval
- [ ] eCR Library still functions normally
- [ ] Tests

## Technical Notes
- Core Schema - https://github.com/CDCgov/phdi/blob/6c23889adfea6e9771bdd5b2c8389142355b523f/containers/ecr-viewer/sql/core.sql
- Local Schema - https://github.com/CDCgov/phdi/blob/c0e7dd7973b2fd89abf7021c64c754d9cfc77f71/containers/ecr-viewer/seed-scripts/sql/01-init.sql#L10-L22

**Comment by gordonfarrell** [comment]
Updated this ticket with new AC based off of some findings from Angela and myself as we dug into doing what this was originally supposed to be.
