### ISSUE TITLE
Add marital status to eCR Viewer

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2721]
## What needs to be done

- Convert marital status in the fhir bundle 
- Add marital status 

## Why it needs to be done

- Missing data from the eICR html

## Acceptance Criteria

- Marital status appears in the [FHIR bundle](https://www.hl7.org/fhir/R4/patient.html#:~:text=for%20the%20individual-,maritalStatus,-0..1).
- Marital status appears on the eCR viewer
- Design matches Figma

## Technical Notes

- Matches [figma designs](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=7006-1040&node-type=instance&m=dev) - Located in social history

## Additional context

- Examples with [Marital Status](https://github.com/search?q=repo%3ACDCgov%2Fphdi+%3CmaritalStatusCode&type=code) 
- TN_sample_eCR3 and TN_sample_eCR6

**Comment by emmastephenson** [comment]
Duplicate ticket
