### ISSUE TITLE
BUG: Patient phone number isn't converting correctly

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2730]
## Description

In the example eCR below, the patient's phone number is not converting correctly to FHIR format. Investigate the cause of this issue and implement a fix.

Note: The phone number provided is invalid. Please verify that this is not a data quality issue before addressing the FHIR conversion problem.

## Steps to reproduce

`TN_sample_eCR3`: [phone number not being converted successfully](https://skylight-hq.slack.com/files/U03LFU8BJJ0/F07KZSRPW9G/screen_shot_2024-09-04_at_8.49.39_pm.png)

## Expected Result

If any patient contact information is available, it should be correctly converted to FHIR and displayed in the eCR Viewer.

## Actual result

Example from `TN_sample_eCR3`: Phone number is not displayed
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWd5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e7d40df02e10d2692706be17417bfc2e74841d3/image.png" alt="image.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [x] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

FHIR conversion may be required for this ticket.

**Comment by mcmcgrath13** [comment]
I don't have access to the tennessee data, but based on the screenshot added this telecom node to another patient's eCR and it does convert as I'd expect

```
{
      "system": "phone",
      "value": "+1-111-111-111",
      "use": "mobile"
}
```

I believe the telephone formatting service is rejecting this as invalid. @ashton-skylight @emmastephenson in this case do we want to do something else other than null it out? maybe pass it through, but with some sort of invalid caveat?
