### ISSUE TITLE
BUG: Patient ethnicity doesn't show additional details

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2731]
## Description

Patient ethnicity only displays first listed and doesn't include any additional details. Please display all available ethnicity information.

Ex. From the Patient resource in the example eCR below --  we display only "Not Hispanic or Latino", not "White" or "Mixed"
```
{
    "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
    "extension": [
        {
            "url": "ombCategory",
            "valueCoding": {
                "code": "2186-5",
                "display": "Not Hispanic or Latino"
            }
        },
        {
            "url": "detailed",
            "valueCoding": {
                "code": "2106-3",
                "display": "White"
            }
        },
        {
            "url": "text",
            "valueString": "Mixed"
        }
    ]
},
```

## Steps to reproduce

`7f02b35a-b172-4845-af55-d173574e5579`: [Ethnicity only displays first listed & doesn’t include extra info, (under “detailed” or “text”)](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724725756665179)

## Expected Result

All available ethnicity information about a patient should be displayed if available.

## Actual result

Example from `7f02b35a-b172-4845-af55-d173574e5579`:
<img width="1411" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmt5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86c4f7d63dbe1438168507069c8e277b19d939a4/image.png" alt="image.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [x] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

No FHIR conversion should be required.

**Comment by emmastephenson** [comment]
We think this is already done - this ticket will just be to confirm functionality with this eCR.

**Comment by angelathe** [comment]
Closing ticket as completed because we already display the primary + detailed Race values. The extra text “Mixed” is generated by our own liquid templates and is not part of the original eICR data (not in the XML nor viewable in the HTML).
