### ISSUE TITLE
BUG: Missing additional contact information for emergency contact

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2733]
## Description

- Emergency contact is missing additional phone number

## Steps to reproduce

1. Visit [15f1b9f4-7797-42c8-aac0-0a5cafe6e473](http://localhost:3000/view-data?id=1.2.840.114350.1.13.299.3.7.8.688883.7202)
2. Patient Info -> Emergency Contact

## Expected Result

- All contact methods should appear for the emergency contact

## Actual result

- Only the first phone number appears
![image](https://github.com/user-attachments/assets/a714c775-42a4-4cd2-b129-0c0f545cef86)

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

- All contact information is already in the bundle, only the FHIR paths need to be updated
- Add tests for this case

**Comment by mcmcgrath13** [comment]
This is nominally already done, but @ashton-skylight could you weigh in on how it's displayed?

<img width="1088" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVBDQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8690a584a7b48d60dc654482d984dfaa743e97ff/image.png" alt="image.png" />

**Comment by ashton-skylight** [comment]
Thanks so much! Can you try posting the picture again? It's not displaying for me

**Comment by mcmcgrath13** [comment]
@ashton-skylight trying again 🤞 
![image](https://github.com/user-attachments/assets/05ce7228-2fb2-4568-ab64-32e2409474b9)

**Comment by ashton-skylight** [comment]
Thanks @mcmcgrath13! This looks great. If there are multiple numbers, could there be a line break in between? 

Mobile: 555-555-555 
Home: 310-555-1212

**Comment by mcmcgrath13** [comment]
on it!
