### ISSUE TITLE
BUG: Pending Results is not displayed

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2746]
## Description

For the eCRs below, the Pending Results information is not being converted to FHIR and displayed in the eCR Viewer. Please fix the FHIR conversion process for this section and ensure that it is displayed in the eCR Viewer.

## Steps to reproduce

Example eCRs:
- `3e0d3f9b-4b26-47d2-9ddd-3ac4d7045382`: [Plan of Treatment (Pending result) isn’t displayed in the eCR Viewer](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724102690823459)
- `7f02b35a-b172-4845-af55-d173574e5579`: [Plan of Treatment is not displaying available Pending Results (”Pending Tests”)](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724725925433779)

## Expected Result

If pending result information is available, it should be displayed in the eCR Viewer under the Pending Results sub-section of the Plan of Treatment (Clinical Info section).

## Actual result

Example from `3e0d3f9b-4b26-47d2-9ddd-3ac4d7045382`:
<img width="1473" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGc3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--964500043f30a6d595ccffb317015bd1a413c5da/image.png" alt="image.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [x] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

FHIR conversion will be required for this ticket.

**Comment by mcmcgrath13** [comment]
One piece of this bug is a quick fix, but another root cause seems to be a garbage in, garbage out situation ([slack tread](https://skylight-hq.slack.com/archives/C05B5R8K0TF/p1730214053475979)). The garbage in/out piece doesn't seem to have any viable fixes within the scope of this ticket. @emmastephenson is there another ticket to generally track getting raw html in these cases?

**Comment by emmastephenson** [comment]
@mcmcgrath13 there's not another ticket that I know of! If you could write one it would be much appreciated.
