### ISSUE TITLE
FILTER: Backend condition filtering

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2750]
## What needs to be done

Implement condition filtering on the backend. When given a list of conditions, this action can filter the returned eCRs for the Library to only those that match the condition.

## Why it needs to be done

This is the backend component needed to make filtering by condition functional. This feature is likely to be heavily used by our pilot partners using the non-integrated Viewer.

## Acceptance Criteria

- [ ] When passed a condition list, only eCRs with that condition in the RR are returned
- [ ] No other eCRs are visible
- [ ] If an eCR is multi-condition, any of those conditions can be filtered on

**Comment by angelathe** [comment]
11/20/24 Noting that the current endpoint for listing all eCR Library info is limited to using postgres. Creating a ticket to enable table to also pull data from SQL Server (high priority?)
