### ISSUE TITLE
FILTER: Filter By Date (Part 1 - Default selections)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2752]
## User Story

As a user of the eCR Library, I want to filter by date, so that I can only see eCRs from within a given date range.

Example: I only want to see eCRs for the last week, so I can identify issues.

## Acceptance Criteria

- [x] "Filter By Received Date" implemented for:
    - [x] Last 24 hours
    - [x] Last 7 days
    - [x] Last 30 days
    - [x] Last 3 months 
    - [x] Last 6 months
    - [x] Last year
- [x] When user applies filter for any of the above, only eCRs received in that date range are included
- [x] My selection is shown as the button text (e.g. "Last 7 days")
- [x] By default, only eCRs from the last 24h are shown

## Scenarios

_Scenario 1_
- I click on the date filter button
- A menu appears with selectable presets
- I choose "Last 7 days"
- I click "Apply Filter"
- Only eCRs from the last week are shown

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=4804-35705&node-type=instance&m=dev)
[Link to Figma prototype](https://www.figma.com/proto/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=4806-39714&node-type=canvas&m=dev&scaling=min-zoom&content-scaling=fixed&page-id=4032%3A9311&starting-point-node-id=4806%3A39674)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_
<img width="518" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVUvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81a4ee9cebeb85fd9ec81f93a5d60178f5b1f9dd/Screenshot%202024-10-11%20at%208.27.15%E2%80%AFAM.png" alt="Screenshot 2024-10-11 at 8.27.15 AM.png" />

## Additional context

This ticket does NOT include implementing or showing the custom date filter - that is a separate ticket.

This ticket includes both the frontend design implementation and the backend querying needed for full functionality.

**Comment by emmastephenson** [comment]
Notes from Planning:
* "Last year" == today's date minus one year (whatever the JS default is)
* May need a different default from dev mode (since last 24h is too fresh for our data)
* "Received Date" is what we're filtering by here - NOT by "Encounter Date"

**Comment by angelathe** [comment]
@emmastephenson Would it be alright if I assigned myself to this, or at least added my current ticket "Filter by conditions" as a blocker? There's a lot of code overlap and it would probably save a lot of time if this got worked on after my other ticket is merged to main

**Comment by emmastephenson** [comment]
@angelathe yes please, adding your ticket as a blocker makes sense to me!

**Comment by angelathe** [comment]
@emmastephenson Thinking ahead to the custom date range ticket, should there always be a start AND end date? Or is it possible a user could input only a start date filter or only an end date filter?

**Comment by angelathe** [comment]
@emmastephenson Also, I know the default is `Last 24 hours`, but would there ever be a case where we would want to see all eCRs (no date filter at all)? Or should there always be a date range included in the query?

**Comment by ashton-skylight** [comment]
Hello @angelathe @emmastephenson! Yes, if the user wants to see eCRs for all time, they can specify that in the custom date range, but for right now, we won't provide that as a filter.
