### ISSUE TITLE
remove dependency on turbo and shared resources from ecr-viewer

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2762]
## What needs to be done

- Remove Turbo from ecr-viewer
- Delete shared resources

## Why it needs to be done
- Additional unused overhead should be removed

## Acceptance Criteria

- [ ] eCR Viewer no longer relies on turbo to build
- [ ] eCR Viewer no longer has a dependency on shared resources
- [ ] shared resources is deleted

## Technical Notes

- Use these PRs to see what changes were made #2044 and possibly #2147

**Comment by emmastephenson** [comment]
* Reverting #2044 and maybe #2147
* Changing Dockerfile; changing Github Action workflows; code deletion; moving any shared resources back into the eCR Viewer container
