### ISSUE TITLE
BUG: Encounter Type should use <originalText> over <displayName>

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2771]
## Description

In the example eCRs below, the Encounter Type shows as Ambulatory in the eCR Viewer, but displays as Office Visit in the eICR HTML.

This is because the `displayName` vs. `originalText` values of an encompassing encounter name are different values. "Ambulatory" comes from `displayName`, but "Office Visit" comes from `original Text. The eCR Viewer chooses to display the `displayName`, but the HTML view uses the `original Text.

For this ticket, please fix the FHIR conversion so that it prioritizes pulling the encounter type value from `<originalText>`, and if that doesn't exist, then to pull the information from `<displayName>`.

IMPORTANT: Please confirm this with Emma/Robert Mitchell/Brady Fausett/etc. first. Making the change above would require changing the conditional order in `DataType/_Coding.liquid`, and would therefore affect other resources that use this Coding data type.

## Steps to reproduce

**Example eCRs:**
- `0aa7a9c2-87e4-4115-876e-b0253bb8dabf`: [Incorrectly shows Encounter Type as "Ambulatory"](https://skylight-hq.slack.com/files/U06UT86N8QH/F07JED7UXFA/1a.png)
- `4aca74f4-c3b7-49ce-a437-1c8594451926`: [eCR viewer shows encounter type ambulatory, but in the HTML it is Office Visit](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724156931766029)
- `5ff5928a-6c29-4a0c-bbe5-c96484bbd22c`: [Encounter type shows as Ambulatory in eCR viewer, but Office Visit in eICR.](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724270874159479)
- `6a6bcd7d-7bad-48f6-9e0b-39a4ec9e063e`: [Encounter type shows as Ambulatory in eCR viewer, but Office Visit in eICR.](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724350211923399)
- `8fd139db-e099-4d34-90ad-3c3e70d8704a`: [Encounter type shows as Ambulatory in eCR viewer, but Office Visit in eICR.](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724873183517419)
- `TN_sample eCR6`: [The "orginalText" "Office Visit" is not displayed](https://skylight-hq.slack.com/files/U03KCCTMPRB/F07LM0Z5P6C/image.png)

**Relevant files:**
- `Resource/_Encounter.liquid`
- `DataType/_Coding.liquid`

## Expected Result

The encounter type displayed in the eCR viewer should match the information displayed in the eICR HTML.

## Actual result

Example from `4aca74f4-c3b7-49ce-a437-1c8594451926`:
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFpSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8a36879e2bc2bd7adfe91839275c29876039709/image.png" alt="image.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [x] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

FHIR conversion would be required for this ticket.

**Comment by mcmcgrath13** [comment]
After chatting with @ashton-skylight, we decided to close this out. The display is typically the most appropriate thing to display and to our target audience, "Ambulatory" is just a synonym for "Office Visit", so shouldn't degrade the functional information available
