### ISSUE TITLE
BUG: Administered Medications not displaying available medication names

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2772]
## Description

In several eCRs, the Administered Medications (Clinical Info) section does not display available medication name information. Please fix the FHIR conversion templates to ensure that all available medication name info gets properly converted and displayed in the eCR Viewer.

Relevant Files:
`Header.liquid` -> `Resource/_Medication.liquid` -> `DataType/_CodeableConcept.liquid` -> `DataType/_Coding.liquid`

NOTE: This ticket only deals with the missing medication **names**. Other tickets are being written to dates not being displayed/other fields that are missing from the eCR Viewer.

## Steps to reproduce

**Example eCRs:**
- 2ff3119d-b933-4236-8746-53726e291449: [Medications Administered is not displayed](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1723750366890869)
    - Medication name: under consumable -> manufatcturedMaterial -> code -> displayName?
    - I'm not actually sure why the Medications aren't rendering for this eCR
- 7f02b35a-b172-4845-af55-d173574e5579: [Administered Medications is not displaying available info](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724725972335359)
    - Medication name: under consumable -> manufatcturedMaterial -> code -> originalText -> reference -> value -> Would need to grab reference value (`rxmed-1`)
- ffa9550f-9a88-4348-9da3-4ca4a1e5f554: [Administered Medications is not displayed when info is available](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724871094188729)
    - Medication name: under consumable -> manufatcturedMaterial -> code -> originalText -> reference -> value -> Would need to grab reference value (`rxmed-1`)
- TN_sample eCR4: [Administered Medications is not displaying when info is available](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1725029014369549)
    - Medication name: under consumable -> manufatcturedMaterial -> code -> originalText -> reference -> value -> Would need to grab reference value (`med32`)

## Expected Result

If Administered Medication names are available, it should be displayed under Clinical Info -> Treatment Details -> Administered Medications.

## Actual result

Example from `2ff3119d-b933-4236-8746-53726e291449`:
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHBSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24ca082213c28cb1baa377764315b2b649bce1a8/image.png" alt="image.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [x] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

FHIR conversion & updating seed data is likely required.

Context: We need to fix how medication names are being converted. Right now, medication names are not being added to the FHIR bundle, and therefore medications with no names are put into the `Unavailable Info` section (see: `evaluateAdministeredMedication`).

**Comment by JNygaard-Skylight** [comment]
Moved 2 eCRs into their own ticket
