### ISSUE TITLE
BUG: Administered Medications not display available date/time info

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2773]
## Description

In several eCRs, the Administered Medications (Clinical Info) section does not display available date/time info. Please fix the FHIR conversion templates to ensure that all available medication date/time info gets properly converted and displayed in the eCR Viewer.

**Relevant Files:**
`Resource/_MedicationAdministration.liquid`

NOTE: This ticket only deals with the missing medication **dates and times**. Other tickets are being written for names not being displayed/other fields that are missing from the eCR Viewer.

## Steps to reproduce

**Example eCRs:**
- 7f02b35a-b172-4845-af55-d173574e5579: [Administered Medications not displaying date/time info](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724725972335359)
- ffa9550f-9a88-4348-9da3-4ca4a1e5f554: [Administered Medications not displaying date/time info](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724871094188729)
- TN_sample eCR4: [Administered Medications not displaying date/time info](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1725029014369549)
- 0aa7a9c2-87e4-4115-876e-b0253bb8dabf: [Administered Medications not displaying date/time info](https://skylight-hq.slack.com/files/U06UT86N8QH/F07HJ81S5K8/7.png)

## Expected Result

If Administered Medications information is available, it should be displayed under Clinical Info -> Treatment Details -> Administered Medications. Date info should fall under the "Start Date" column of the table.

## Actual result

Example from `7f02b35a-b172-4845-af55-d173574e5579`:
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWRSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68e80dc3f666418c45202e010422092705122d86/image.png" alt="image.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [x] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

FHIR conversion & updating seed data is likely required.

Context: We need to fix how medication date/times are being converted. Right now, medication date/times are not always being added to the FHIR bundle.

**Comment by JNygaard-Skylight** [comment]
It looks like we only ever display the date portion of the datetime. Is that okay or do we need to add the times?

**Comment by JNygaard-Skylight** [comment]
`0aa7a9c2-87e4-4115-876e-b0253bb8dabf` will likely be resolved with [this PR](https://github.com/CDCgov/phdi/pull/2816).

**Comment by angelathe** [comment]
@JNygaard-Skylight Did question ever get resolved?

(If not, I think we always want to display times if the info is available)

**Comment by JNygaard-Skylight** [comment]
Administrated medications are correctly shown for the above eCRs.
