### ISSUE TITLE
BUG: Lab date/times do not always display when available

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2775]
## Description

In the example eCRs below, the lab info section does not display analysis date-times and/or collection date-times when the information is available. Please make any necessary changes to ensure that the datetime values are displayed in the Viewer.

`Lab Test Result Date` OR `Result Date` in the XML/HTML corresponds to `Analysis Time` in the eCR Viewer
`Collection Date` in the XML/HTML corresponds to `Collection Time` in the eCR Viewer

## Steps to reproduce

Example eCRs:
- Analysis Date - `3a6febc6-cc0f-4706-8322-da0cd16bb7c6`: [Not displaying **Analysis Date** (shows up as Lab Test Result Date in HTML) — relevant to all lab results](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1723840953475069). Note that screenshot incorrectly circles Collection Date, but Lab Test Result Date = Analysis Date.
- Analysis Date - `12aa8d10-c131-44f6-9a34-5873d2148084`: [Lab Result date (**Analysis Date**) not displayed](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1723824167663039)
- Collection & Analysis Date - `TN_sample eCR2`: [Lab **Collection Date** & **Analysis Dates** are not displayed when info is available](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724877679703979)

## Expected Result

If lab date/time data is available, it should be displayed under the appropriate date/time field in the eCR Viewer.

## Actual result

Example from `12aa8d10-c131-44f6-9a34-5873d2148084`:
<img width="1573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0de4ce3d4e99dbb60a50461f89b4105b6276eb0/image.png" alt="image.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [x] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_

**Comment by austin-hall-skylight** [comment]
Fixed by #2830
