### ISSUE TITLE
BUG: Pregnancy status is not displayed when info is available

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2778]
## Description

For the examples below, we are not displaying pregnancy status information in the eCR Viewer even when the information is available. Please modify the FHIR conversion templates to pull the pregnancy observation information (just status), and update the Viewer so that it displays this value.

From XML: Pregnancy status value is code 77386006 and `displayName` is pregnant

<img width="1848" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e421c1f2585e75f99631419294125b00bb429dc3/image.png" alt="image.png" />

(Note that for the eCRs below, the HTML table actually indicates that the user is not pregnant. However, since we consider the XML data as the source of truth, please source pregnancy status information from the XML observation even though it conflicts with the HTML values.)

## Steps to reproduce

Example eCRs:
- 4aca74f4-c3b7-49ce-a437-1c8594451926: [Missing pregnancy status](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724149457460799)
- 7f02b35a-b172-4845-af55-d173574e5579: [Pregnancy Status is not displaying available info](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724725907439729)
- ffa9550f-9a88-4348-9da3-4ca4a1e5f554: [Pregnancy status is not displayed when info is available](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724871060663159)

## Expected Result

If pregnancy status (boolean) information is available, it should be displayed under Patient Info -> Social History -> Pregnancy Status.

## Actual result

Example from `4aca74f4-c3b7-49ce-a437-1c8594451926`:
<img width="963" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN05SQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84fafe335e0a7d80cc0c35d27c8a8f8b4739d952/image.png" alt="image.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

FHIR conversion will be required for this ticket.

Note, this ticket only deals with adding **pregnancy status**. Other tickets will be written to address the other missing fields (i.e., Expected Date of Delivery, Observation Date, etc.)

**Comment by emmastephenson** [comment]
Closing this for now - would require a larger feature effort to search for pregnancy status anywhere in the FHIR bundle.

**Comment by angelathe** [comment]
@emmastephenson Just FYI, this is the pregnancy status that we can pull directly from the XML (it is coded as a pregnancy observation) -- it doesn't refer to those cases where we'd have to search through the text / other sections to find pregnancy info
