### ISSUE TITLE
Update MPI with the results of record linkage

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#282]
### Why are we doing this?
There are two possible cases after a bundle has been run through record linkage:
1. A match is found to an existing person record in the MPI
2. No match is found (meaning this is a new person)

In either case, the MPI will need to be updated.

### Action Requested
In either case, a new row representing the encounter should be added to the patient table.

If a match is found, then a new link is formed between the patient record and the person row they're associated with.
If no match is found, then a new person record should be added to the MPI.

### Acceptance Criteria
After record linkage is finished for a given record, the conclusions are reflected in the MPI.

### Additional Information
- Input: boolean from linkage algorithm
- If a patient record matches an existing record, add the existing person resource (Master Patient ID?...I’m not totally sure of the language here) to the patient resource
- If a patient record does not match an existing record, create a new Master Patient ID and add a new person resource to the patient resource
- Output: return new ID if a new person resource needs to be created (or something like that)

**Comment by emmastephenson** [comment]
@m-goggins and @bamader, can you review this ticket and update where needed? TIA!

**Comment by m-goggins** [comment]
@emmastephenson This looks good to me! The only thing I am wondering about is, in the case of needing to create a new ID, would we need a helper function to check whether the new ID already exists in the MPI, or can we use the UUID in from the FHIR bundle?

**Comment by emmastephenson** [comment]
Discussed offline! Decision was made to use a newly generated UUID for representing the "id" field in the Person table.
