### ISSUE TITLE
Add code coverage check to ecr-viewer pipeline

### ISSUE THREAD

**Issue by austin-hall-skylight** [CDCgov/phdi#2901]
## What needs to be done
- Add code coverage check to the Test ecr-viewer Container / test-node-containers workflow

## Why it needs to be done
- This needs to be done so we can have a high confidence that the ecr-viewer is thoroughly tested.

## Acceptance Criteria

- [ ] Determine which code coverage tool we want to use
- [ ] Test ecr-viewer Container / test-node-containers workflow fails if code coverage is below [discuss with team]%

**Comment by emmastephenson** [comment]
Notes from planning:
* We use pytest-cov for the Python services (but don't have a threshold for passing)
* Jest should be able to provide this code coverage - but not sure how to fashion that into a check
* CodeCov was previously used on the project? May want to revisit.

**Comment by austin-hall-skylight** [comment]
https://jestjs.io/docs/configuration#coveragethreshold-object
