### ISSUE TITLE
SPIKE: Terminology Exchange Service

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2915]
## What needs to be done

Investigate APHL's new Terminology Exchange Service (TES) as an alternative to the eRSD API currently powering the DIBBs Trigger Code Reference service.

## Why it needs to be done

The TES is APHL's new service that's intended to power their "grouping and filtering" service - essentially, identifying what portions of an eCR are actually relevant to the reported condition. We want to investigate this service to see if it can be incorporated into the TCR service to ultimately provide better condition summaries for the eCR Viewer.

## Timebox

5 Days?

## To Do

1. Review the API docs and figure out how to call the TES
2. Try incorporating TES into eCR Viewer workflow, and compare the condition summaries powered by TES with the ones that are currently generated by the eRSD-powered TCR service
3. Determine if we should move forward with a migration to the TES instead of eRSD

## Resources

- TES website: https://tes.tools.aimsplatform.org/ 
   - You will likely need to make an account and request an API key
- [Notes on the TES](https://docs.google.com/document/d/1yoqCJ8AeYGG95CqjRIX6s3CgUH40WB0hXbP5jcejOls/edit?usp=sharing) from the APHL <> DIBBs sync
- [TES overview documentation](https://drive.google.com/file/d/1uJZkuOvLf4rGJRYfvfhME1rab9yyEq-j/view?usp=sharing) from APHL
- [TES page on APHL Confluence](https://aphlinformatics.atlassian.net/wiki/spaces/EKM/pages/2761228290/Terminology+Exchange+Service)
    - Account will also be needed to access - chat with Emma about getting one.

## Additional context

The Query Connector team also uses the TCR to power their queries, and the TES may not be able to meet their needs yet.(They need the codes to be filtered by resource type, and our APHL contact didn't think that the initial iteration of TES would do this.) We'll need to keep in close coordination with the QC team about this spike and our path forward.

**Comment by JNygaard-Skylight** [comment]
> API
The Application Programming Interface (API) for the Terminology Exchange Service (TES) is a FHIR server that supports standard [FHIR REST](https://hl7.org/fhir/R4/http.html) and [FHIR Search](https://hl7.org/fhir/R4/search.html) functionality. The API is protected by API Key-based authentication and authorization.
FHIR Endpoints
Production – [https://tes.tools.aimsplatform.org/api/fhir](https://tes.tools.aimsplatform.org/api/fhir)
API Key Authentication
Users can generate an API key from within the TES application. The API Key should be included as an X-API-KEY header in requests that are submitted to the application.
API Key Authorization
The TES currently defines the following roles: Viewer, Publisher, Admin. All three will have full read access. Only publishers and admins will be able to publish new content to the repository.

**Comment by JNygaard-Skylight** [comment]
## Summary
I made a quick and dirty script that pulls data from TES in [this branch ](https://github.com/CDCgov/phdi/tree/josh/tes-data). I query all ValueSets with the `useContext` of `"system": "http://terminology.hl7.org/CodeSystem/usage-context-type", "code": "focus"}` and save the  information for conditions and concepts, with a linking table between them. By doing this I get the following results, compared to the ERSD script:
### TES
- Conditions: 242
- Concepts:  54,089
### ERSD
- Conditions: 242
-  Concepts: 45,273

I was able to get 8,816 additional Concepts, 19% more than ERSD.

## Comparison
I ran the eCR Viewer seed script and compared 6 LA eCRs using main (commit f414c65ce) and my `tes-data` branch. All 6 had identical "Condition Summary"s apart from `74f8f383-87aa-410b-b6e2-c32e95c47f3a` which I an additional "Active Problem": 
### TES
<img width="774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmNPQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--886364172ffcc8ee75e5bf35cfb88aed2e98a8e2/image.png" alt="image.png" />

### Main
<img width="803" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmdPQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71477067050742cb2ef63f62a4dfcbc856a0b146/image.png" alt="image.png" />

List of all of the eCRs I checked:
- LA/12aa8d10-c131-44f6-9a34-5873d2148084/bundle.json
- LA/1c1393a3-2481-45a5-8610-392683aaef4a/bundle.json
- LA/3e0d3f9b-4b26-47d2-9ddd-3ac4d7045382/bundle.json
- LA/74f8f383-87aa-410b-b6e2-c32e95c47f3a/bundle.json
- LA/78a77635-1fb2-43cf-9294-ed182e8d9626/bundle.json
- LA/88f5bb61-e63a-4870-8eaa-ffb2d6a5a0b0/bundle.json

## Next Steps
From the TES API I did get get any information on the "type" of concept ("dxtc", "ostc", "lotc", "lrtc", "mrtc", "sdtc"). This should be possible (I think) but was more complicated than I really wanted it to be. The current TCR Service  `stamp_condition_extensions` endpoint uses the types to restrict what concepts are considered depending on the resource type. Here's the dictionary used for that:
```
RESOURCE_TO_SERVICE_TYPES = {
    "Observation": ["dxtc", "ostc", "lotc", "lrtc", "mrtc", "sdtc"],
    "Condition": ["dxtc", "sdtc"],
    "Immunization": ["ostc", "lotc", "lrtc"],
    "DiagnosticReport": ["dxtc", "ostc", "lotc", "lrtc", "mrtc", "sdtc"],
}
```
As far as I can tell this removing this did not effect the results of the endpoint. However I believe other teams use this information. Before TES can be integrated into our code we would need to still get this information.

**Comment by JNygaard-Skylight** [comment]
`https://tes.tools.aimsplatform.org/api/fhir/ValueSet/dxtc`, or any other type will return a list of concepts of that type. This does not return the display value of the concept, but we do not use that anyway.
