### ISSUE TITLE
Create checks for unit tests in FHIR converter

### ISSUE THREAD

**Issue by austin-hall-skylight** [CDCgov/phdi#2918]
## Description
Now that our custom FHIR converter code has been moved into the Skylight FHIR Converter repo, we need to create a workflow to run the tests.

## What needs to be done
Create a workflow with steps to run unit tests for the dotnet tests as well as the liquid template tests.

## Why it needs to be done
This needs to be done so we can have make sure that we don't merge code with bugs.

## Acceptance Criteria

- [x] Dotnet unit tests run on creation of a PR.
- [ ] Liquid template tests run on creation of a PR.

**Comment by mcmcgrath13** [comment]
The dotnet unit tests already run on creation of a PR. Which ones are the liquid template tests?

**Comment by mcmcgrath13** [comment]
Ah, I see now that this is blocked on those tests coming into existence 😅
