### ISSUE TITLE
Security, test, and 508 scans for eCR Viewer

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2924]
## What needs to be done

Create/gather the following artifacts for CDC review:
* Security scan of the application (Snyk?)
* Test report of the application (Github CI analysis reports?) - should be in excel format
* 508 accessibility check (Deque or Lighthouse?)

## Why it needs to be done

These have been requested for our project by CDC compliance.

## Acceptance Criteria

- 3 artifacts listed above have been shared with our CDC PO

## Additional Context
Requested by MW on 11/18.

**Comment by JNygaard-Skylight** [comment]
I don't know how fancy we have to be, but the Snyk reports are hidden behind their enterprise subscription.
