### ISSUE TITLE
Create function to generate `block_data`

### ISSUE THREAD

**Issue by m-goggins** [CDCgov/phdi#295]
### Why are we doing this?
Until now, the record linkage blocking process has relied on knowing both the columns the user wishes to block on as well as the values of the block, e.g., "ZIP" and "90210". To run in production, we intend for the user to input the columns they wish to block on, e.g., ZIP, and the value for the block to be extracted from an incoming record, e.g., the zip in a FHIR bundle. 

### Action Requested
Create a function to generate `block_data` for single record in a FHIR bundle.

### Acceptance Criteria
It's possible to generate `block_data` to be used in `_generate_block_query` that specifies the columns you wish to use for blocking and the value for the incoming record. The function searches the FHIR bundle for the input of columns (errors if no match) and extracts the value corresponding to the input columns.

Input: list of column names, FHIR bundle
Output: `block_data` dictionary contain key value pairs of the column to be used in blocking and the data of the incoming record, e.g., 
`
{"zip": 90210,
"first4": "MARC"
}

### Additional Information
Since the FHIR bundle will not include some of the blocking columns we plan to use in the LAC pilot, e.g., Address4 (the first four characters of an address after the whitespace is stripped out), we may need the user to input slightly more information than just the column names. Something like `{"column_name1": transformation, "column_name2":transformation}` where `transformation` defaults to `None` but could include `first 4 char` and any additional transformations we decide to support.

**Comment by m-goggins** [comment]
### Why are we doing this?
Until now, the record linkage blocking process has relied on knowing both the columns the user wishes to block on as well as the values of the block, e.g., "ZIP" and "90210". To run in production, we intend for the user to input the columns they wish to block on, e.g., ZIP, and the value for the block to be extracted from an incoming record, e.g., the zip in a FHIR bundle. 

### Action Requested
Create a function to generate `block_data` for single record in a FHIR bundle.

### Acceptance Criteria
It's possible to generate `block_data` to be used in `_generate_block_query` that specifies the columns you wish to use for blocking and the value for the incoming record. The function searches the FHIR bundle for the input of columns (errors if no match) and extracts the value corresponding to the input columns.

Input: list of column names, FHIR bundle
Output: `block_data` dictionary contain key value pairs of the column to be used in blocking and the data of the incoming record, e.g., 
`
{"zip": 90210,
"first4": "MARC"
}

### Additional Information
Since the FHIR bundle will not include some of the blocking columns we plan to use in the LAC pilot, e.g., Address4 (the first four characters of an address after the whitespace is stripped out), we may need the user to input slightly more information than just the column names. Something like `{"column_name1": transformation, "column_name2":transformation}` where `transformation` defaults to `None` but could include `first 4 char` and any additional transformations we decide to support.

**Comment by emmastephenson** [comment]
@m-goggins Adding a transformations parameter makes sense to me. Maybe we make that an `enum` with the supported transformations? `None` and `first 4 char` to begin with?
