### ISSUE TITLE
Fix critical accessibility issue with lab result accordion buttons

### ISSUE THREAD

**Issue by austin-hall-skylight** [CDCgov/phdi#2965]
## Background
Expanding a lab report accordion item reveals a critical vulnerability when running accessibility tests.

**Description:** Ensure all ARIA attributes have valid values
**Help URL:** https://dequeuniversity.com/rules/axe/4.10/aria-valid-attr-value?application=AxeChrome
**Summary:** Fix all of the following:
  Invalid ARIA attribute value: aria-controls="Drugs Of Abuse Comprehensive Screen, Ur"
**Selector:** [".accordion-rr.accordion_d46ea14e-251a-ab52-3a32-89b12270d9e6.usa-accordion:nth-child(6) > h5 > .usa-accordion__button"]
**Source Code:** `<button type="button" class="usa-accordion__button" aria-expanded="true" aria-controls="Drugs Of Abuse Comprehensive Screen, Ur" data-testid="accordionButton_Drugs Of Abuse Comprehensive Screen, Ur">`
**Test URL:** http://localhost:3000/view-data?id=1.2.840.114350.1.13.297.3.7.8.688883.567479

## Action Requested
Ensure all ARIA attributes have valid values.

## Acceptance Criteria (Requirements)
- [ ] Axe accessibility scans return 0 critical or high severity issues with lab report accordions opened or closed.

**Comment by emmastephenson** [comment]
There may also be an aria issue somewhere with labs - look for aria description of "[object]"
