### ISSUE TITLE
Make RL index by column name instead of index

### ISSUE THREAD

**Issue by bamader** [CDCgov/phdi#327]

**Comment by bamader** [comment]
Our record linkage algorithm currently uses a mapping between column indices and functions to apply to those columns in order to make linkage work. This was initially done due to convenience out of working with lists of lists. However, once the MPI communication lands and we can retrieve and operate on data in FHIR form, we don't have to index on number anymore. The scope of this ticket then is to change the record linkage code (the parts used by the container and API endpoints) so that column names are used in defining function comparators, rather than column indices. This will also necessitate a change to data/record "unpacking", e.g., once a record comes in from a client caller, it must be structured in such a way as to make the column mapping valid.

**Comment by emmastephenson** [comment]
This work can be taken on after the LAC MOU.
