### ISSUE TITLE
[EPIC] Create hand off plan for LAC

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#347]
### Why are we doing this?
To ensure LAC is set up for success with the tools we’ve provided them and able to continue making progress without the DIBBs team. 
Before creating a hand off plan and any documentation to support LAC, we need to conduct research with LAC to better understand what they will need.

### Team Members (RACI)
Amrita: responsible & accountable 
Sarah: responsible & accountable 
Peggy: collaborating & consulted
Jill: collaborating & consulted 

### Action Requested
- Find external resources for handoffs  - Jill Fromewick ping #general
- Develop a research plan 
 - Define how we want to answer open questions 
- Define a timeline for this work 
- Create an initial outline for LAC to review 

**Immediate next steps:** 
- Translate both of these “docs” into Epics on Zenhub Amrita Bhatti
- Start research plan/strategy for LAC handoff plan Peggy Chau + Sarah Tress
 -- Include previous Q&A and info from discovery sessions and conversations
 -- Internally align on questions we want to answer with LAC - come up with draft questions and circulate with Emma, Brady, Dan before presenting to LAC
  - Answers we need is different from questions we ask 
- Start a draft for summary findings - ® Amrita Bhatti with Ann Millspaugh + Matt Goldberg support 

### Logistics
Overlap with Usability testing work 
Have something to deliver by early May 

### Acceptance Criteria
LAC has all of the materials and support they need to continue to use the DIBBs pipeline at the end of our MOU

### Things we want to learn
What does LAC want to do with the work we set up in this pilot after we leave (desired outcomes)?
For ex: do they want our tools for educational purposes or do they eventually want to get our tools running in production?
What does success look like after this pilot for LAC?
Who in LAC will be the users of our handoff plan?
Do they want us to have a smaller team continue supporting them beyond May – need to have answered by April 30th 
Contingent upon work completed by the end of April 
What barriers does LAC face to continue running with the pipeline in their production environment?   

### Handoff plan contents
**Documentation**- include user onboarding documentation 
Work that @matt is doing - making sure our services are documented well
**Training plan**
Sarah Tress & Ann Millspaugh Execution Guide development + training
**Ongoing support plan** 
TBD - what does support look like 
Are they going to continue using the pipeline after the pilot is over? 
**Recommended next steps** 
Plenty of features and development that we won't get to 
Outline “here’s the state of the pilot” as of mid May - if we were to continue the work we have in progress, what would we continue to work on, how would we prioritize it and why
What would it take to get all eCR into production? 
Currently: do a weekly incident and person level linkage, unmatched cases go into blob store for manual review – don’t have confidence that our system is doing a good enough job with matches to ensure our system isn’t flooding their system with new cases 

### Relevant artifacts/links
- [Add personas here once done]
- [LAC Discovery GDrive folder](https://drive.google.com/drive/folders/1vLki-4JnYQ-TxMKwjBZuQFV98tSffyVK?usp=share_link)
- Interviews where hand off plan was discussed:
  - [Cloud infrastructure training summary notes](https://docs.google.com/document/d/1Y4Ak7WiaZJ7LDrJ8gQFuf8a67j8tNnklFly4kiRyIY4/edit?usp=sharing) where we talked briefly about a hand off plan
  - [PHDI and eng collaboration interview summary notes](https://docs.google.com/document/d/1p76Nx6KF5Vj9XFit1Rai25iL1mtpABIBSAN3YoYtqSs/edit?usp=sharing) also mentioning hand off plan

Link to notes in Drive: https://docs.google.com/document/d/1jfNneOa86bnl1NFXshIwPC1MIErh6juLHIl7nK1bIbg/edit#

**Comment by pkchau-skylight** [comment]
**Notes from sync**

Research
- competitive analysis (Skylight + general best practices for consultant handoffs)
- asking LAC users what they want

**Comment by emmastephenson** [comment]
Goals for next sprint: Share handoff plan with LAC (5/1). Slide deck and spreadsheet available as content guides. Content creation is underway.

**Comment by emmastephenson** [comment]
On track.
