### ISSUE TITLE
[EPIC] Conduct usability testing of the Execution Guide

### ISSUE THREAD

**Issue by sarahtress** [CDCgov/phdi#348]
### Why are we doing this?
LAC engineers who haven't worked with our team closely are going to be learning how to use our pipeline by running eCR data manually through our pipeline in their UAT environment. We are going to use this opportunity to conduct usability testing of our Execution Guide with LAC engineers

### Action Requested
- Separate the execution guide (step 3) from the implementation guide and have it live as a standalone doc in our repo
- Create research plan to conduct usability testing of the execution guide
- Peggy to coordinate and conduct dry runs of execution guide before conducting usability tests
- Conduct usability testing, synthesize findings, and share findings with team

### Acceptance Criteria
We have actionable findings to improve our Execution Guide based on LAC's feedback

### Relevant artifacts/links
- [Folder](https://docs.google.com/document/d/1sXuqxEnHdDBXW5aaA7ppFiiuRkmTUvL8tJU6cGi8t2s/edit?usp=sharing) for prior usability testing of implementation guide
  - [Usability testing guide](https://docs.google.com/document/d/1v4vvd8GmshpvqPz5duxcaNTNYkthP-XzAHdo6fvx2pc/edit?usp=sharing)
  - [Usability testing script](https://docs.google.com/document/d/1p4FaY_DYuVyGmYs89xAOBm6N524Ws3ZloLW25pgoWqs/edit?usp=sharing)

**Comment by aathwal3** [comment]
**Sprint Goals**
- Conduct usability testing with 4-5 testing sessions 
- Revise the execution guide based on usability tests 
- Make any additional tickets based on user feedback from user testing 
- Prep for phase 2 of user research: prepare github templates and instructions for submitting feedback when running pipeline independently
