### ISSUE TITLE
Make edits to execution guide based on user feed back

### ISSUE THREAD

**Issue by pkchau-skylight** [CDCgov/phdi#388]
### Why are we doing this?
From our dry run with Sarah, we identified a number of action items for updating the execution guide, ensuring LAC users will have the necessary set up and permissions/authentication, and updating the VXU messages. These action items will need to be completed prior to the user tests with LAC.

### Action Requested
Peggy will make an initial pass with updates to the execution guide that don't require new content (which would require product/dev input) by submitting a [pull request on GitHub](https://github.com/CDCgov/phdi-azure/edit/edits-executionguide/docs/execution-guide.md) by EOD April 5 Wednesday. She will then tag in Ann and Dan/Nick Clyde for review and additional edits as needed. 

### Acceptance Criteria
The execution guide has been updated with all edits identified from the initial dry run with Sarah Tress. 

### Additional Information
[Sarah's Dry Run Notes + Next Steps](https://docs.google.com/document/d/1oJ8VmPYs9lKJJINKoBAyBwa0WpPe7VgzFhEnl-g9290/edit?usp=sharing)

**Comment by emmastephenson** [comment]
Not going to make additional edits to execution guide aside from detailing error handling.
