### ISSUE TITLE
Update containers to use the BaseService instance

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#395]
### Why are we doing this?

In an effort to DRY up our containers, a new `BaseService` class has been created. This class automatically instantiates the health check endpoint, and sets up FastApi for you so less boilerplate is needed. Now that this class exists, we should refactor our existing containers to use it.

### Action Requested

Rework the existing containers (alerts, fhir converter, ingestion, message parser, record linkage, validation, and tabulation) to extend this base class rather than create FastAPI instances and health check endpoints manually. 

### Acceptance Criteria

The following containers extend BaseService:
- Alerts
- fhir-converter
- ingestion
- message-parser
- record-linkage
- tabulation
- validation

### Additional Context

See the [original ticket](https://github.com/CDCgov/phdi/issues/262) and [PR](https://github.com/CDCgov/phdi/pull/345/files) to create the BaseService class.

**Comment by robertmitchellv** [comment]
This one is done, save `fhir-converter`, which is not using it because of dependency issues related to installing `phdi` and maintaining the versions listed in the requirements doc.
