### ISSUE TITLE
[EPIC] Automate data reads/writes from IRIS using Azure Synapse

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#407]
## Why are we doing this work? 
For the LAC pilot to be successful, we need to read LAC patient and case data, and write extracts of eCR data that has passed through our pipeline. This is best accomplished through Azure Synapse, as it will allow us to read and transform data on a regular, scheduled basis using SQL/Python notebooks.

These tasks are likely to require more compute/memory resources than are available in our Azure Container Apps, hence the need to use Synapse. (Synapse is roughly the Azure equivalent of Databricks).

## Background and strategic fit 
This work is necessary for:
1. Data from our pipeline to be ingested into IRIS
2. Patient and incident record linkage to be performed accurately

## How does the user interact with this service?
Post-pilot, LAC systems engineers will interact directly with Azure Synapse to make any required tweaks or adjustments.

## Acceptance Criteria (Requirements)
Once this epic is completed, the final step of our pipeline will be complete - the MPI and MCI are being seeded from IRIS, and tsv extracts are being sent from our data stores to populate IRIS eCR forms.

## Solution Design Doc/Implementation Plan 
![Azure Synapse Analytics](https://user-images.githubusercontent.com/80282552/230690843-c13f8c24-f420-4dcf-b45c-6ed54d58a172.jpg)
Link: https://drive.google.com/file/d/1bl5OkgZz-XyeRgN2A7SEAnJ5nIPobTvQ/view?usp=sharing

**Comment by aathwal3** [comment]
**Sprint Goals**
- Synthetic MPI seed data has been created 
- It is possible to convert seed data to a FHIR bundle

**Comment by emmastephenson** [comment]
Update 4/14:
* PRs out for both of the above
* IaC coverage for Synapse is in place; working on authentication between Synapse and blob storage.

**Comment by DanPaseltiner** [comment]
Auth between Synapse and storage as well as Synapse and Postgres MPI has be solved.

**Comment by DanPaseltiner** [comment]
Work to get code for seeding MPI with LAC extract running in Synapse is happening now.

**Comment by emmastephenson** [comment]
Sprint goal for next sprint: Everything other than creating the TSVs that go to LAC are complete. Updates, joins on eCR data store/MPI/MCI are complete, so all the data is available.

The sprint after that - going from that data to LAC's custom TSV spec.

**Comment by emmastephenson** [comment]
Mid-sprint checkin: All Synapse jobs are working; just one clarification question on dates. Next step is to make sure the Synapse jobs are run automatically.
Dummy delta lake is merged.

**Comment by emmastephenson** [comment]
End of next sprint: All the Synapse jobs are running and working as intended.

Marcelle, Brandon, Robert, Nick C, Dan, and Kenneth will be working on this effort.
(Marcelle, Robert, Kenneth, and probably Nick C for only half the sprint)

**Comment by emmastephenson** [comment]
Work to create TSV extracts for IRIS is in progress.

Work to filter by COVID labs is also in progress.

**Comment by emmastephenson** [comment]
Goal for final sprint:

1. Seed patient data from IRIS is properly inserted to the MPI
2. All Synapse jobs are Devops-ified
3. The Synapse jobs are confirmed to work end-to-end

**Comment by emmastephenson** [comment]
We think it's done!
