### ISSUE TITLE
Create a Master Case Index

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#430]
### Why are we doing this?

Much like patient record linkage and the MPI, we'll need a master case index (MCI) to perform incident-level record linkage. This ticket tracks the work needed to create this resource.

### Action Requested

Create a new data schema for the MCI. This should likely be a distinct database from the MPI, in case we decide to deploy case and patient record linkage separately later.

Once the schema is created, we'll need to provision the appropriate Azure resources for it.

The basic table structure for this resource has been laid out here:
![MCI Arch](https://user-images.githubusercontent.com/80282552/231609215-659dc08d-f9fb-4f32-9c68-37fcdb62e5e7.jpg)

### Acceptance Criteria

An MCI is available to use with incident-level linkage.

### Additional Context

Should definitely revisit the question of a distinct Postgres database from the MPI before this ticket is picked up, to make sure everyone is in alignment.

**Comment by DanPaseltiner** [comment]
Need further discussion. Should this be a new table in the existing MPI DB or a new table in a separate DB?

**Comment by emmastephenson** [comment]
Decision: MCI will live in a separate database, but within the same Postgres server we already have stood up for the MPI.

More context: https://skylight-hq.slack.com/archives/C04T9HFFETX/p1681752385033069

**Comment by emmastephenson** [comment]
After further team discussion, we've decided to store the MCI data in a delta table, rather than as a separate database. In the LAC architecture, the data from this MCI will only be used weekly, and in a large batch job to check against all the records stored in our eCR data store. The benefits that a Postgres database would provide (quick querying to specific rows) is thus unnecessary, so this ticket will be closed.
For further context, see [this Slack thread](https://skylight-hq.slack.com/archives/C04T9HFFETX/p1681835738192129).
