### ISSUE TITLE
[SPIKE] Standardize Assets

### ISSUE THREAD

**Issue by m-goggins** [CDCgov/phdi#441]
### Why are we doing this?
The assets folder is difficult to navigate and we have no standardize set of assets to use for testing.

### Action Requested
Assess each item in the assets folder; remove unnecessary assets

Re-label in-use assets with TBD convention

Investigate how we might leverage [fhir.resources](https://pypi.org/project/fhir.resources/#:~:text=Example%3A%203%3A%20This%20example%20creates%20a%20new%20Patient%20resource%20from%20json%20object(py%20dict)%3A) to develop standardized assets on the fly

### Acceptance Criteria
Assets folder is organized and clearly labeled

All tests have been updated to use appropriate assets

**Comment by millzpaugh** [comment]
@BradySkylight already completed this! Closing.
