### ISSUE TITLE
Expand system monitoring metrics for Azure App Insights UI

### ISSUE THREAD

**Issue by millzpaugh** [CDCgov/phdi#445]
## Why are we doing this?
It will be helpful to have metrics about how the data pipeline is functioning. Let's timebox X number of days to provide a dashboard with out-of-the-box monitoring metrics. This may require investigation into how Terraform supports dashboard resource settings. 

## Acceptance Criteria
- Have a dashboard in Azure App Insights that incorporates out-of-the-box metrics around system health - computing resources, errors, etc...

**Comment by emmastephenson** [comment]
Create epic dedicated to error handling and monitoring, and move this ticket to that epic.
