### ISSUE TITLE
[EPIC] Conduct quality assurance (QA) testing of Execution Guide & Pipeline

### ISSUE THREAD

**Issue by pkchau-skylight** [CDCgov/phdi#456]

**Comment by emmastephenson** [comment]
Goal for EO next sprint: anon and non-anon data going through pipeline.
By the sprint after - have the daily non-anon eCR messages coming into our directory.

**Comment by emmastephenson** [comment]
Sarran: Working on a microservice in their dev env to pick up messages and put them in the pipeline. These are the anonymized messages from AIMS; 20-30 per day.

Production will be unzipping and moving messages manually. Not sure if the same microservice can be repurposed; the data doesn't live in S3 for production.

**Comment by emmastephenson** [comment]
Mid-sprint checkin: Hoping to finish current round of dev testing by EOD Wednesday; getting the non-anon data in the UAT environment ready to go.

**Comment by emmastephenson** [comment]
Done!
