### ISSUE TITLE
Add error investigation documentation

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#475]
### Why are we doing this?
One of the resources it would be helpful for LAC to have after the pilot concludes is an investigation guide that lets their engineers troubleshoot the pipeline independently.

### Action Requested
Create an error investigation guide in the phdi-azure repository. This will be broken out from the execution guide and will explain expected errors in the pipeline and how to understand errors in Azure. This should include links to the dashboard that will be developed and any other resources on how to investigate errors.

### Acceptance Criteria
Separate execution guide exists in the phdi-azure repo and is available in LAC's repository.

### Additional Information
n/a

**Comment by emmastephenson** [comment]
@emmastephenson finish writing this ticket

**Comment by emmastephenson** [comment]
Peggy and Ann to own this work.

**Comment by emmastephenson** [comment]
Error messages haven't been clear to engineers as to where errors are occurring, and there also aren't docs around what to do next when encountering a specific error.

Error logging - cases where we have to switch between logs in data factory vs storage accounts. Docs on when to switch between errors would be helpful.

**Comment by emmastephenson** [comment]
Could also take a look at some specific error messages and potentially change them.

**Comment by gordonfarrell** [comment]
Scoping this for a first ticket: 

Create a basic ADF guide for finding and diagnosing failures
Also, Walkthrough of pass and fail states for the 3 portions of the pipeline that write errors out to storage
