### ISSUE TITLE
Add error FAQ document

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#476]
### Why are we doing this?
One of the resources we'd like to share with LAC is an error FAQ document that details common errors and their resolution.

### Action Requested
Create a list of common errors that occur when running the pipeline.

### Acceptance Criteria
An error FAQ is available within the phdi-azure repository, as well as LAC's repo.

### Additional Information
Check Dovetail for some notes. Peggy and Ann to be on the lookout for common errors during LAC usability and quality testing.

[Spreadsheet documeting errors encountered during QA testing](https://docs.google.com/spreadsheets/d/1uLm-PXZTAuz3ik9upPbYiauqEGby4s970Adaj95cmdA/edit?usp=sharing)

**Comment by emmastephenson** [comment]
@emmastephenson to own this work.

**Comment by pkchau-skylight** [comment]
will plan to create FAQ after QA testing

**Comment by emmastephenson** [comment]
Iceboxing until after Gordon's work is complete, at which point we'll see if anything else needs to be done.

**Comment by emmastephenson** [comment]
Review the need for this after DiRT exercises are complete.

**Comment by pkchau-skylight** [comment]
spreadsheet of errors that QA testers are encountering: https://docs.google.com/spreadsheets/d/1uLm-PXZTAuz3ik9upPbYiauqEGby4s970Adaj95cmdA/edit?usp=sharing
