### ISSUE TITLE
Add agile tooling guide to hand off plan

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#493]
### Why are we doing this?
LAC requested documentation around our agile practices and the specific ways we have implemented them with meetings, tools, etc. 

### Action Requested
Add documentation for the above tools in the handoff guide.

Specific links might include:
- Zenhub/Github how-to guides
- MURAL templates (user manuals, etc)
- Epic and Github issue templates
- Skylight project management templates

### Acceptance Criteria
Handoff guide has a section for team tooling.

### Additional Information
We're also planning to record a quick walkthrough of all the above.

**Comment by aathwal3** [comment]
Document in progress: https://docs.google.com/document/d/13aXPaMy5Ze0E0aCaD7REd0lGGoB-b8ihbjg5aUi-cbk/edit#heading=h.uf0atn1vq79q

**Comment by millzpaugh** [comment]
Ann to link PPT here by EOW April 28th to share during Wednesday standing time either Wednesday May 3rd or Wednesday May 10th.

**Comment by emmastephenson** [comment]
@sarahtress to link the new PPT once it's been design-updated.

**Comment by sarahtress** [comment]
[new slide deck](https://docs.google.com/presentation/d/1g5RL2eJekxfA7fCqad2V9dwF0ye_zIKO5gZp67xoIkc/edit?usp=sharing)
