### ISSUE TITLE
Share DIBBs Roadmap with LAC

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#494]
### Why are we doing this?
LAC has expressed interest in a roadmap of DIBBs plans post-pilot. If we have more clarity on our post-pilot future by then, we should create a tentative roadmap to share with them.

### Action Requested
Create roadmap of DIBBs work through Q3.

### Acceptance Criteria
Roadmap has been added to the handoff plan.

### Additional Information
"What BBs LAC might expect to be in development in the future at a high level"

**Comment by aathwal3** [comment]
project resource work in progress: https://docs.google.com/presentation/d/1L7RpKxqycZoJiU42le5stKcMi4omZeBXBVPJLSCORes/edit#slide=id.g23b11cbbf7c_0_688

**Comment by aathwal3** [comment]
https://docs.google.com/spreadsheets/d/1I8gB3x3P46hC8svDEAUIUN1TpYfSQ8835m9586zMMgo/edit#gid=0
