### ISSUE TITLE
Complete LAC Deployment

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#497]
### Why are we doing this?
To fulfill our commitment to continuous delivery, we need to deploy to the LAC private repository on a regular basis. This ticket is a placeholder "reminder" to kick off that PR/deployment process for the sprint starting 4/24.

### Action Requested
Open a PR in the LAC repository with our recent changes and shepherd it through approvals and merging.

### Acceptance Criteria
LAC repo is up-to-date with changes, and the changes have been deployed to their Azure environment.

**Comment by emmastephenson** [comment]
Ideally this is done early in the sprint so pipeline is current for quality testing.

Blocked on the record linkage bug.

**Comment by nickclyde** [comment]
https://github.com/LACountyDPH/phdi-azure/pull/4
