### ISSUE TITLE
Run "real" eCR messages through the Azure Starter Kit in uat env

### ISSUE THREAD

**Issue by millzpaugh** [CDCgov/phdi#499]
## Why are we doing this?
- In order to have confidence in the quality and scalability of our system, we need to do quality testing. See documentation on the QA plan [here](https://docs.google.com/document/d/1WFFuB6oGQGhEy_GFN5eKrkZxYQp9vN36YkGZFGS3i5g/edit#heading=h.diglxxe25j7d).

## Action Requested
- 4 LAC QA testers run 20-30 "real" eCR messages through the Starter Kit pipeline in the uat environment. 

## Acceptance Criteria
- All 4 LAC QA testers have run 20-30 "real" eCR messages through the Starter Kit pipeline in the uat environment and logged any issues in the CDCgov phdi-azure repo.

**Comment by pkchau-skylight** [comment]
I believe this is completed as of Friday of last week (all LAC QA testers ran real eCR data in the UAT environment), so I'm going to close this ticket! @emmastephenson @millzpaugh
