### ISSUE TITLE
Write a synapse job to match cases between the MCI and eCR data store

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#504]
We need to match individual eCRs (rows in the eCR datastore) with case in the MCI. If a record in the eCR datastore matches a record on the MCI on `iris_id` and the eCR was generated within 90 days of the case's initial specimen collection date then the `incident_id` from the MCI should be added the eCR data store.

GIVEN the eCR datastore and the MCI
WHEN the synapse job runs
THEN records in the eCR datastore are updated with the `incident_ids` of the Iris incidents that they should be associated with.

**Comment by emmastephenson** [comment]
Marcelle to stub out this service until the fake eCR data store for development is complete.

**Comment by emmastephenson** [comment]
To filter our by COVID tests, we need two data dictionaries - one for detecting positive tests and one for detecting COVID.

LAC has a list of triggers that indicate COVID for eICRs, which can be sent tomorrow (5/9).

They also have a data dictionary of positive result triggers.

**Comment by emmastephenson** [comment]
We'll store the triggers in a configuration file, so we can use dummy data for the first pass at COVID/positive filtering.
