### ISSUE TITLE
Filter message parsing by message type.

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#508]
Currently all messages moving through the pipeline will be sent to the message parsing service regardless of message type. This means that currently if an ELR message is processed the pipeline will send it to the message parsing service and the eCR parsing schema will be applied. We need to implement some kind of gate or filter so that only eCR messages are passed to the message parsing service.

In the future we could develop message parsing schemas for other incoming message types so that data beyond just eCR can be sent to the message parsing service.

**Comment by emmastephenson** [comment]
@nickbristow fixed this already.
