### ISSUE TITLE
Deploy recent changes to LAC UAT environment

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#527]
### Why are we doing this?
LAC is nearing the point of needing to test in the UAT environment. We've deployed recent changes to their dev environment, but UAT is out of date.

### Action Requested
Deploy changes from `phdi-azure` into the LAC UAT environment.

### Acceptance Criteria
The LAC UAT environment has the most recent changes from `phdi-azure`.

### Additional Information
We may want to hold off on creating a deployment until after #523 is merged - otherwise the LAC testers will run into the same issues in UAT that they did for dev.

**Comment by nickclyde** [comment]
https://github.com/LACountyDPH/phdi-azure/pull/5
