### ISSUE TITLE
Create suggested job descriptions for LAC 

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#533]
### Why are we doing this?
LAC requested JDs they can take back to their stakeholders, with suggested skillsets needed to maintain and improve the pipeline.

### Action Requested
Create job descriptions for work needed to maintain and improve the pipeline.

### Acceptance Criteria
JDs are incorporated in handoff docs.

**Comment by aathwal3** [comment]
Work in progress: https://docs.google.com/spreadsheets/d/1I8gB3x3P46hC8svDEAUIUN1TpYfSQ8835m9586zMMgo/edit#gid=0
