### ISSUE TITLE
Add instructions to access Azure Insights Dashboard in error investigation guide

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#614]
### Why are we doing this?
During DiRT testing, we saw that the team frequently used the Azure Insights Dashboard to check the progress of the pipeline and pinpoint batches of errors. Adding instructions on how to access this dashboard to the error investigation guide would be helpful.

### Action Requested
Add a section on accessing Azure Insights Dashboard to error investigation guide.

### Acceptance Criteria
Users have documentation available on how and when to access the dashboard.

**Comment by gordonfarrell** [comment]
This is already in there actually!
