### ISSUE TITLE
(SPIKE) Translate validation Building Block to Kubernetes(K8s)

### ISSUE THREAD

**Issue by nickbristow** [CDCgov/phdi#670]
### Why are we doing this?

Spike: 
In order to make deployment on multiple cloud environments easier, we will translate the building block containers to work using kubernetes.

Build a kubernetes package to deploy the Validation Building Block. 

### Action Requested

Build the Validation Building block in kubernetes

### Acceptance Criteria

- Validation building block can be run with Kubernetes
- Steps for running the validation BB are documented in the relevant readme
- Validation BB has a working health check endpoint that returns `ok` status
- Reuse the docker container

**Comment by emmastephenson** [comment]
Timeboxing this to a week (ending on 6/27). Will re-evaluate then.

**Comment by emmastephenson** [comment]
Done, this is working!
