### ISSUE TITLE
Replace app in azure with Kubernetes(K8) version

### ISSUE THREAD

**Issue by nickbristow** [CDCgov/phdi#671]
### Why are we doing this?

In order to make the app more portable, we are moving the entire app to Kubernetes, so the rework for deploying to new cloud providers is as painless as possible.

The entire app should be deployed with kubernetes in azure.

### Action Requested

Package to deploy app with kubernetes in azure

### Acceptance Criteria

- All building blocks are built with K8
- App deployment process is updated to use K8 versions
- K8 version of app is successfully deploy
- Data can be run through the app
- Steps to deploy are documented

**Comment by emmastephenson** [comment]
Replaced by #679
