### ISSUE TITLE
SPIKE: Translate FHIR Converter building block to K8s

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#678]
### Why are we doing this?

Spike: 
In order to make deployment on multiple cloud environments easier, we will translate the building block containers to work using kubernetes.

Build a kubernetes package to deploy the FHIR Converter Building Block. 

### Action Requested

Build the FHIR Converter Building block in kubernetes

### Acceptance Criteria

- FHIR Converter building block can be run with Kubernetes
- Steps for running the FHIR Converter BB are documented in the relevant readme
- FHIR Converter BB has a working health check endpoint that returns `ok` status
- Reuse the docker container

**Comment by emmastephenson** [comment]
Timeboxing this to a week (ending on 6/27). Will re-evaluate then.

**Comment by millzpaugh** [comment]
This hasn't been started yet. We're extending "timeboxing" to end of sprint 6/30.

**Comment by emmastephenson** [comment]
Running in K8s, still need to add docs.

**Comment by emmastephenson** [comment]
Done, this is working!
