### ISSUE TITLE
SPIKE: Ensure K8s services are only accessible within Azure

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#703]
## Action Requested
Investigate how to ensure K8s endpoints are only accessible from within Azure, not publicly accessible from the internet.

_As a BUILDING BLOCK USER, I want my endpoints to be private 
SO THAT I'm not being charged for traffic from anywhere._

## Acceptance Criteria
- Solution for restricting traffic has been decided on
- Tickets written to implement solution

This solution should ensure that:
- Accessing containers deployed on K8s requires an Azure login.
- Azure Data Factory can still access the endpoints.

_GIVEN an access attempt on our K8s containers 
WHEN you are unauthenticated 
THEN your request is not served._

## Background & Context
Even though our containers are largely stateless and won't serve any PII to clients, the endpoints should still be private so that only authorized users can access the services. Otherwise it's possible users hosting the services would be charged for things like bot traffic.

## Additional Information
As always, a cloud-agnostic solution is preferred if multiple solutions are available, but for authentication it's inevitable that some Azure-specific tools will probably be required. An ingress/ingress controller may be the appropriate way to restrict traffic in K8s, but we'll need to combine it with Azure permissions.

**Comment by KennethSkylight** [comment]
Based on research, the recommended way by Josh, Rin, and Zedd is to use the vnet that is created when generating a private AKS. 

Note: you cannot take an existing public AKS and make it private, it has to be private upon creation

The closest tutorial that may help is this: https://ikshitijsharma.medium.com/accessing-azure-kubernetes-service-private-cluster-services-via-azure-private-link-service-and-78ef9c72fcfa

There is an azure service called private link service that can give certain instances of Azure services access to the private AKS. Private endpoints are created in the Azure services to link with the private endpoint. However when following the tutorial I got an "error with payload" that I never figured out. 

To create a private AKS cluster and to run kubectl on it, you can use this tutorial to access it: https://www.youtube.com/watch?v=8e8vBLZiIhQ

**Comment by emmastephenson** [comment]
This should be covered with the VNET.
