### ISSUE TITLE
Create Documentation  for Users of TSV Extracts

### ISSUE THREAD

**Issue by aathwal3** [CDCgov/phdi#719]
Per the [UAT Testing Plan](https://docs.google.com/document/d/15bFc0cHK6mtPlPJaGd6AQcQ_73oXQVWNHTUYP45fTYA/edit):

**Users**: Meredith’s Data Integrations team: TBD
**User Needs**: know what schedule that TSVs are generated on and how to access TSVs in Azure, how to review and identify matches and nonmatches, know who to contact is there are issues w/ TSVs

**Comment by m-goggins** [comment]
Duplicate; deleting and moving to phdi-azure
