### ISSUE TITLE
Apply virtual network to Azure services

### ISSUE THREAD

**Issue by KennethSkylight** [CDCgov/phdi#736]
### Action Requested
Investigate how to ensure K8s endpoints are only accessible from within Azure, not publicly accessible from the internet.

As a BUILDING BLOCK USER, I want my endpoints to be private
SO THAT I'm not being charged for traffic from anywhere. 

Note that the Azure Data Factory instance that pulls from our AKS cluster will still need to be public. 

### Acceptance Criteria
Accessing containers deployed on K8s requires an Azure login. IP addresses of deployed services cannot be accessed by the public.
Azure Data Factory can still access the endpoints.
Azure Data Factory still works with the full pipeline run through.
GIVEN an access attempt on our K8s containers
WHEN you are unauthenticated
THEN your request is not served.

### Background & Context
Even though our containers are largely stateless and won't serve any PII to clients, the endpoints should still be private so that only authorized users can access the services. Otherwise it's possible users hosting the services would be charged for things like bot traffic.

Based on research, the recommended way by Josh, Rin, and Zedd is to use the Azure VNET that is created when generating a private AKS.

Note: you cannot take an existing public AKS and make it private, it has to be private upon creation

The closest tutorial that may help is this: https://ikshitijsharma.medium.com/accessing-azure-kubernetes-service-private-cluster-services-via-azure-private-link-service-and-78ef9c72fcfa

There is an Azure service called Private Link Service that can give certain instances of Azure services access to the private AKS. Private endpoints are created in the Azure services to link with the private endpoint. However when following the tutorial I got an "error with payload" that I never figured out.

To create a private AKS cluster and to run kubectl on it, you can use this tutorial to access it: https://www.youtube.com/watch?v=8e8vBLZiIhQ

Another recommendation is to possibly have two VNETs set up, one private VNET that only has the cluster and ADF to enable communication with each other and to limit access to the AKS cluster. The other VNET is public for ADF to still be accessible to users. 

### Additional Information
As always, a cloud-agnostic solution is preferred if multiple solutions are available, but for authentication it's inevitable that some Azure-specific tools will probably be required. An ingress/ingress controller may be the appropriate way to restrict traffic in K8s, but we'll need to combine it with Azure permissions.

**Comment by emmastephenson** [comment]
Note: We should also likely look into creating separate managed identities for Kubernetes and the pipeline runner. See [this PR comment](https://github.com/CDCgov/phdi-azure/pull/221#discussion_r1272935543) for more detail.

**Comment by emmastephenson** [comment]
This ticket will only be for putting a vnet in place around our Kubernetes services. There will be a separate ticket for wrapping that vnet around all our other services (like the pipeline, MPI, etc.)
