### ISSUE TITLE
Create skeleton frontend application for MVP

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#772]
## Action Requested
Set up the new frontend application in `phdi-playground`. This doesn't need any functionality for now; it's just to get something stood up for future development.

## Acceptance Criteria
Frontend application has been created with NextJS in `phdi-playground`.

This ticket does NOT include setting up the CI/CD pipeline to host/publish this site; it's only the "hello world" application creation.

## Background & Context
We need to start somewhere to develop this MVP!

## Additional Information
The engineering team discussed creating this as a React/Typescript/NextJS application - see notes [here](https://docs.google.com/document/d/1amsZs4BLgJxBG50F5j3l8sDakgZs0B6Otzb-zUPvqTo/edit?usp=sharing).

**Comment by nickclyde** [comment]
https://github.com/CDCgov/phdi-playground/pull/1
