### ISSUE TITLE
Create stubbed endpoints for the orchestration API

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#783]
## Action Requested
Create a stubbed processing endpoint for the orchestration building block.

## Acceptance Criteria
The orchestration building block can be run locally, and will respond with a generic message like "functionality missing" if the processing endpoint is hit.

## Background & Context
This is the first step in creating the orchestration API - we'll add true functionality to the endpoint later.

**Comment by nickbristow** [comment]
health check /get
processing /post
configuration /put

See message parser

**Comment by nickbristow** [comment]
https://github.com/CDCgov/phdi/pull/790
