### ISSUE TITLE
Process message given configuration in Orchestration API

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#785]
## Action Requested
Given a configuration (starting with the default) process a message end-to-end via the orchestration API.

## Acceptance Criteria
A user can hit the processing endpoint of the orchestration BB with an eICR/RR and receive a processed message that's gone through the other building blocks as defined in the default configuration.

There is an endpoint that the UI can hit to upload a zip file. The zip files are then dropped into the orchestration flow

## Background & Context
This is the work needed to make #784 actually useful and process messages. It needs to be extensible enough to allow users to input their own configuration as well.

**Comment by millzpaugh** [comment]
@emmastephenson will re-review next week!
