### ISSUE TITLE
Autoscale Kubernetes pods based on HTTP request traffic

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#798]
## Action Requested
Add a HorizontalPodAutoscaling rule to our Kubernetes pods. The rule should increase the number of pods in correlation to the number of HTTP requests. For exact thresholds (# of requests, # of replicas), check the autoscaling rules present on the existing Azure Container Apps.

## Acceptance Criteria
Pods autoscale given enough request traffic. 

## Background & Context
This is the last piece of functionality needed to get us to feature parity with ACA!

## Additional Information
See the [Azure docs](https://learn.microsoft.com/en-us/azure/application-gateway/ingress-controller-autoscale-pods) for information on how to do this.

**Comment by nickclyde** [comment]
Ran into a bit of a snag with this: the method described in the docs linked has actually been archived on GitHub:
https://github.com/Azure/azure-k8s-metrics-adapter

There is a note that recommends using a different actively developed method, "Keda":
https://keda.sh/docs/2.11/scalers/azure-monitor/

And found these Azure docs that talk about how to integrate Keda:
https://learn.microsoft.com/en-us/azure/azure-monitor/containers/integrate-keda

Luckily, it looks easy enough to deploy with Helm. Just trying to get the manifests right before testing this out!

**Comment by nickclyde** [comment]
Resolved by https://github.com/CDCgov/phdi-playground/pull/11
