### ISSUE TITLE
Create basic processing status page for demo UI

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#813]
## Action Requested
Create the basic processing page for the demo UI. Don't add styling yet, as we're waiting for high-fidelity designs.

## Acceptance Criteria
A processing status page exists on the demo UI site. It doesn't have functionality yet.

## Background & Context
See the [v2 Figma designs](https://www.figma.com/file/MCslzKLzoWPJ2G7U6okylG/DIBBs-eCR-LoFi-Wireframes?type=whiteboard&node-id=0-1&t=ANJOxxmu6erzdfEb-0) for the basic user journey.

This is the skeleton page for the status system.

**Comment by KennethSkylight** [comment]
This was already done when I created the upload page
