### ISSUE TITLE
Add functionality to data export page

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#817]
## Action Requested
Process back the response from the `process` endpoint of the orchestration service, and let the user download the data that's returned.

## Acceptance Criteria
The user can download a JSON of data after it's passed through the DIBBs pipeline. The specific return value is the JSON of fields back from the message parsing service.

## Background & Context
Uploading an eCR and downloading the data that comes back is the basic functionality of the demo UI - we'll add more on top of it. Exporting to CSV is NOT part of this ticket; that will come later.

## Additional Information
High fidelity wireframes: https://www.figma.com/file/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Demo-Site?type=design&node-id=0-1&mode=design

**Comment by KennethSkylight** [comment]
The upload page should upload the file, when the process is done it will take them to the export page where they can download it.

We will skip the progress bar for this ticket
