### ISSUE TITLE
Spec out ideal payload from message parsing service  for HTML BB

### ISSUE THREAD

**Issue by millzpaugh** [CDCgov/phdi#834]
### Overview

Since we are taking in the output of the Message Parsing service for the HTML BB, we also want the important information to be surfaced to the top. 

### Acceptance Criteria
- The message parser building block also returns custom spec filters and fields that the user wants to be surfaced in the html.
- Spec out the needs for an additional endpoint in the message parsing service to support the output format (likely JSON) and additional metadata needed for the HTML BB.

**Comment by emmastephenson** [comment]
Decision here - add a new endpoint to message parsing service that returns both metadata and parsed fields.
