### ISSUE TITLE
Update process_ecr page to high fidelity designs (happy path)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#847]
## Action Requested
Update the process_ecr page in the Demo UI to reflect the high-fidelity designs.

## Acceptance Criteria
Design approval for the process_ecr page is given.

## Additional Information
[High-fidelity Figma designs](https://www.figma.com/file/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Demo-Site?type=design&node-id=0-1&mode=design&t=XIl4OZUYnm7Ldvpu-0)
[Clickable Prototype](https://www.figma.com/proto/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Demo-Site?page-id=0%3A1&type=design&node-id=1-2&viewport=145%2C312%2C0.19&t=Z8I2xoOpxZHXCtiZ-1&scaling=min-zoom&starting-point-node-id=1%3A2)

**Comment by sarahtress** [comment]
whoever picks this up, if you could meet with me before getting too far that would be great! I have some ideas for the loading experience that I'd like to chat through feasibility wise (i.e. I'm not sure what's possible in terms of customizing USWDS components)
