### ISSUE TITLE
Update upload_file page to high fidelity designs (happy path)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#848]
## Action Requested
Update the upload_file page in the Demo UI to reflect the high-fidelity designs.

## Acceptance Criteria
Design approval for the upload_file page is given.

## Additional Information
[High-fidelity Figma designs](https://www.figma.com/file/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Demo-Site?type=design&node-id=0-1&mode=design&t=XIl4OZUYnm7Ldvpu-0)
[Clickable Prototype](https://www.figma.com/proto/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Demo-Site?page-id=0%3A1&type=design&node-id=1-2&viewport=145%2C312%2C0.19&t=Z8I2xoOpxZHXCtiZ-1&scaling=min-zoom&starting-point-node-id=1%3A2)

**Comment by KennethSkylight** [comment]
Here are the screenshots:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemFDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39d1014a09ce4c0d17abfe61cc5f3dba4ba99986/Screenshot%202023-10-30%20at%209.08.42%20AM.png)

**Comment by KennethSkylight** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56d5170cb6632c432957cbd27856ee06c73673db/Screen%20Recording%202023-10-30%20at%209.08.58%20AM.mov)

**Comment by sarahtress** [comment]
thanks for sending these @KennethSkylight 

few questions/things to update:
- would you be able to make the design centered in the window? right now it's a good bit left of center. after you update this, would you also be able to send a video of what it looks like when you make the browser window narrower? (just want to see if it'll stay centered smoothly while changing the browser size)
- spacing between the navigation and the "Upload your eCR" header looks a little small. could you confirm it's set to 48px?
- is the font size on "what are the zip file requirements?" set to 16? it looks small
- is it possible to have the arrow icon be to the left of the "what are the zip file requirements?" text? it's no biggie if it's too hard to change

for the expanding/collapsing interaction, I think that looks totally fine to me! thanks for adding the video :)

**Comment by KennethSkylight** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e37397380ac3b524bec354c28d9fb321d2a4e204/Screenshot%202023-10-30%20at%201.57.11%20PM%20%282%29.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmlFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9157340b5b6c64d7f5707492e535df924ef784fa/Screenshot%202023-10-30%20at%201.57.04%20PM%20%282%29.png)


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm1FQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9e4278cfa0ebc386eb6179b5d545debad1c0635/Screen%20Recording%202023-10-30%20at%201.59.36%20PM.mov)

**Comment by KennethSkylight** [comment]
I couldn't get the arrow to go to the other side, it's designed like that on the USWDS style that I am using

**Comment by sarahtress** [comment]
@KennethSkylight this all looks great! no more changes from my end
