### ISSUE TITLE
Add integration tests for ingestion service

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#856]
## Action Requested
Add a set of integration tests for the ingestion service. These should send a request to a running Docker container and make assertions on the responses.

## Acceptance Criteria
Integration tests for the ingestion service cover all the possible responses (successful parse, failed to fetch configuration, etc.)

## Background & Context
We should likely continue to use the `testcontainers` library with Docker Compose to set up this integration test.

One special thing to consider about ingestion is the use of third-party APIs for geocoding. We'll have to decide if we want the tests to make requests to our actual production Smarty/Census service, or if we should cache those responses somehow (I've used [WireMock](https://wiremock.org/) on a previous Java project, imagine there's something similar for Python.)

## Additional Information
See other integration tests (FHIR converter, validation) for integration test samples. The unit tests for ingestion also likely have some sample requests/responses we can use.

**Comment by gordonfarrell** [comment]
Check if we're good first in case this ticket is old news
