### ISSUE TITLE
Publish playground frontend to permanent URL

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#894]
## Action Requested
Publish the Demo UI to a permanent URL that end users can access.

## Acceptance Criteria
The demo site is live and running in Azure.

## Testing
No unusual testing requirements. 

## Background & Context
We don't currently have a plan for how to set this up. We should look into:
1. Whether or not Github Pages can be used for this case (we do have a backend, so potentially unlikely)
2. What Azure's recommended solution for a basic web app like this is

**Comment by emmastephenson** [comment]
Goal for sprint wasabi: determine a URL this could be hosted through.

**Comment by robertandremitchell** [comment]
@BobanL and @KennethSkylight , I was wondering if there might be some time this week I might be able to shadow on this issue this week? I've been working on Demo UI work where this ticket could have some implications for the work.
