### ISSUE TITLE
Update product offerings page content

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#902]
## Action Requested
Change "Our product offerings" page to "Our products" page, and match content.

## Acceptance Criteria

- [ ] Content has been updated throughout the page
    - Add new image to "Starter Kit Pipeline" section
    - Change styling of Building Blocks section; add/update content
    - Remove SDK block
- [ ] PR has gone through design review

## Testing
No unusual testing requirements. 

## Background & Context
Page needs to match updated site designs. 

## Additional Information
See the [Figma designs](https://www.figma.com/file/3VaLNvirF5Tq2RFHsD32g1/Website?type=design&node-id=1414-2549&mode=design&t=pmnu4dNF59pgtgFn-0) for source of truth on content.

**Comment by emmastephenson** [comment]
https://drive.google.com/file/d/1UiYGSPDmgAegLv6sePRaevwkbhwg7SoH/view?usp=sharing

**Comment by sarahtress** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGV0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f614fbc5e22b6d4693d7840571ee9000da16969e/LAC%20End%20State%20%28Azure%29-no%20IRIS.drawio.png)

**Comment by emmastephenson** [comment]
@sarahtress requesting a design review, please!

### Desktop
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e205b5f82eb59110cb0f00656c1f991897b31db/Screenshot%202023-11-14%20at%202.51.30%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVBWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0d85cf76eab4a0b9fc3414d9e870f971131cc72/Screenshot%202023-11-14%20at%202.51.37%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVRWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d204994fb441fd4bc66a793a8f20c48f396d60c0/Screenshot%202023-11-14%20at%202.51.43%20PM.png)

### Mobile
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVhWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1e978717c9ffb1649f0c112645d570f4a618b2b/Screenshot%202023-11-14%20at%203.05.32%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWJWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e107b11c608415dbe88a88fc703a0ff1fc19b5fd/Screenshot%202023-11-14%20at%203.05.44%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWZWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb1de86c964c4d6ee3d1026afd3ddba62878f104/Screenshot%202023-11-14%20at%203.05.53%20PM.png)

**Comment by sarahtress** [comment]
thanks @emmastephenson! just a few minor things for the web view:

- can you take the title off the architecture diagram? (the title that's built into the image itself. I think I just cropped it in Figma, but should've taken it out of the source diagram too)
- looks like the names of the building blocks and the icons are slightly misaligned. would it be possible to center them so the middle of the icon aligns with the middle of the building block name (message parser and FHIR converter look misaligned to me in particular)
- can we reduce the vertical spacing above Standardization and Geocoding to be like half of what it is now? sorry this is an issue in the original design!
- can you add a little more margin for the white box below the message parser text? looks small compared to the design. should be about 40 px
- everything in mobile designs look good!

changing the navigation titles is another ticket right?

**Comment by emmastephenson** [comment]
@sarahtress yep, nav titles are a separate ticket! but will work on everything else, thanks!

**Comment by emmastephenson** [comment]
@sarahtress I think I addressed all your comments! Mind taking another look?

![Screenshot 2023-11-15 at 2 54 20 PM](https://github.com/CDCgov/phdi/assets/80282552/b6351323-324c-4a43-ac11-c6abe71dc1b6)
![Screenshot 2023-11-15 at 2 54 34 PM](https://github.com/CDCgov/phdi/assets/80282552/024fac35-aa1c-420c-aa78-67ace3601f16)

**Comment by emmastephenson** [comment]
Message parser icon is throwing me a bit - this is how it looks when aligned the same as the other icons, but it doesn't look as "centered" to me. Up to you though Sarah!

<img width="1156" alt="Screenshot 2023-11-15 at 3 02 12 PM" src="https://github.com/CDCgov/phdi/assets/80282552/6c40f408-63cd-4c44-9831-4d40ddeffd1d">

**Comment by sarahtress** [comment]
@emmastephenson everything looks good to me! I prefer the second Message Parser alignment you sent!
