### ISSUE TITLE
Update "partner with us" page content

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#904]
## Action Requested
Change "Partner with us" page to "Engage with us" page, and match content in designs.

## Acceptance Criteria

- [ ] Content has been updated throughout the page
    - "Partner with us" becomes "How to engage with us"
    - Content matches designs
    - Community of Practice block is removed
- [ ] PR has gone through design review

## Testing
No unusual testing requirements. 

## Background & Context
Page needs to match updated site designs. 

## Additional Information
See the [Figma designs](https://www.figma.com/file/3VaLNvirF5Tq2RFHsD32g1/Website?type=design&node-id=1414-2549&mode=design&t=pmnu4dNF59pgtgFn-0) for source of truth on content.

**Comment by emmastephenson** [comment]
@sarahtress requesting another design review, please! :) 

I know the whitespace at the bottom is much bigger than called for in the designs, but without it the footer floats above the bottom of a standard screen.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ac30d186de2b963553099e658a439be8f541abb/Screenshot%202023-11-16%20at%2010.19.49%20AM.png)

**Comment by sarahtress** [comment]
@emmastephenson looks all good to me! no changes :)
