### ISSUE TITLE
Add links to about page

### ISSUE THREAD

**Issue by KennethSkylight** [CDCgov/phdi#936]
# Action Requested
The about page on the static page has links on the bottom for 
- DIBBs Overview PDF
- Virginia Whitepaper
- Los Angeles County Pilot - Executive Brief
- Los Angeles County Pilot - Summary Findings Report

These are currently unlinked. The files will be supported by the static site. Ask Matt Goldberg for the files

# Acceptance Criteria
Users can click the links and it will take them to a PDF that is linked to our static site

**Comment by gordonfarrell** [comment]
Setting this down as ATO change is eating all my time

**Comment by BobanL** [comment]
It seems like the Virginia Whitepaper pilot is already link, but the other 3 are not yet ready.
![image](https://github.com/CDCgov/phdi/assets/10108172/a9902405-5a5a-463b-9673-8fcd9c4a1ad9)

@mattmgoldberg to update this issue when the these become available: 
DIBBs Overview PDF
Los Angeles County Pilot - Executive Brief
Los Angeles County Pilot - Summary Findings Report

**Comment by emmastephenson** [comment]
@mattmgoldberg any updates on this? Do we have the finalized documents available?

**Comment by emmastephenson** [comment]
Going to close this ticket; since we're going to redesign the entire website.
