### ISSUE TITLE
HTML work to showcase fields in eCR in human readable way

### ISSUE THREAD

**Issue by jankimo** [CDCgov/phdi#983]

**Comment by robertandremitchell** [comment]
https://github.com/CDCgov/phdi/blob/main/containers/message-parser/app/default_schemas/ecr_with_metadata.json#L12-L17

One thought I had around beautifying the HTML message is implementing the `metadata` dictionary in the `ecr.json`. This would mean that we only display values that have a `metadata` value in the dictionary.

For context, there are fields we have in the `ecr.json` that are not currently needed. In addition, adding new fields going forward to the HTML would only then require updating the `ecr.json` with the appropriate category, subcategory, and name in eCR viewer noted here: https://docs.google.com/spreadsheets/d/1S-swX3cmwbwEpS10UxTGeklp9s4CTw7Wwu3BQssy-8Y/edit#gid=0.

**Comment by robertandremitchell** [comment]
also, looking at this: https://github.com/CDCgov/phdi/tree/main/containers/html-converter
