### ISSUE TITLE
Change URL of GitHub "About"

### ISSUE THREAD

**Issue by mjradwin** [CDCgov/phdi#993]
### Environment

Any browser

### Description

The "About" section of the https://github.com/CDCgov/phdi page currently links to [cdcgov.github.io/phdi-site/](https://cdcgov.github.io/phdi-site/) but it needs to be updated to [cdcgov.github.io/dibbs-site/](https://cdcgov.github.io/dibbs-site/)

### Steps to Reproduce

Visit https://github.com/CDCgov/phdi and note old URL

<img width="1135" alt="CDCgov_phdi" src="https://github.com/CDCgov/phdi/assets/3769045/db918d1e-585d-4909-85a7-b8ced350a27b">

### Expected Behavior

We expect this to link to [cdcgov.github.io/dibbs-site/](https://cdcgov.github.io/dibbs-site/)

**Comment by emmastephenson** [comment]
Thanks for noting, Michael! Resolved:

<img width="343" alt="Screenshot 2023-12-20 at 9 10 30 AM" src="https://github.com/CDCgov/phdi/assets/80282552/192a8be6-857e-4711-b933-a8fd4122a5b2">
